/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:29 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/SDActivityRequestRecord.h>

@class NSData;

@interface SDActivityPayloadRequestRecord : SDActivityRequestRecord {

	NSData* _advertisementPayload;

}

@property (nonatomic,copy) NSData * advertisementPayload;              //@synthesize advertisementPayload=_advertisementPayload - In the implementation block
-(id)description;
-(NSData *)advertisementPayload;
-(void)setAdvertisementPayload:(NSData *)arg1 ;
@end

