/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:28 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData, SDURLSessionProxySessionMessage, NSURLSessionConfiguration;

@interface SDURLSessionProxyCreateSession : PBCodable <NSCopying> {

	NSData* _configuration;
	SDURLSessionProxySessionMessage* _session;
	BOOL _delegateImplementsDidReceiveResponse;
	BOOL _delegateImplementsSessionAuthChallenge;
	BOOL _delegateImplementsTaskAuthChallenge;
	BOOL _delegateImplementsWillPerformRedirection;
	BOOL _delegateImplementsWillSendRequest;
	BOOL _supportsRedirects;
	SCD_Struct_SD4 _has;

}

@property (setter=_setActualConfiguration:,retain) NSURLSessionConfiguration * _actualConfiguration; 
@property (nonatomic,readonly) BOOL hasSession; 
@property (nonatomic,retain) SDURLSessionProxySessionMessage * session;                                           //@synthesize session=_session - In the implementation block
@property (nonatomic,readonly) BOOL hasConfiguration; 
@property (nonatomic,retain) NSData * configuration;                                                              //@synthesize configuration=_configuration - In the implementation block
@property (assign,nonatomic) BOOL hasSupportsRedirects; 
@property (assign,nonatomic) BOOL supportsRedirects;                                                              //@synthesize supportsRedirects=_supportsRedirects - In the implementation block
@property (assign,nonatomic) BOOL hasDelegateImplementsWillSendRequest; 
@property (assign,nonatomic) BOOL delegateImplementsWillSendRequest;                                              //@synthesize delegateImplementsWillSendRequest=_delegateImplementsWillSendRequest - In the implementation block
@property (assign,nonatomic) BOOL hasDelegateImplementsSessionAuthChallenge; 
@property (assign,nonatomic) BOOL delegateImplementsSessionAuthChallenge;                                         //@synthesize delegateImplementsSessionAuthChallenge=_delegateImplementsSessionAuthChallenge - In the implementation block
@property (assign,nonatomic) BOOL hasDelegateImplementsTaskAuthChallenge; 
@property (assign,nonatomic) BOOL delegateImplementsTaskAuthChallenge;                                            //@synthesize delegateImplementsTaskAuthChallenge=_delegateImplementsTaskAuthChallenge - In the implementation block
@property (assign,nonatomic) BOOL hasDelegateImplementsWillPerformRedirection; 
@property (assign,nonatomic) BOOL delegateImplementsWillPerformRedirection;                                       //@synthesize delegateImplementsWillPerformRedirection=_delegateImplementsWillPerformRedirection - In the implementation block
@property (assign,nonatomic) BOOL hasDelegateImplementsDidReceiveResponse; 
@property (assign,nonatomic) BOOL delegateImplementsDidReceiveResponse;                                           //@synthesize delegateImplementsDidReceiveResponse=_delegateImplementsDidReceiveResponse - In the implementation block
-(NSURLSessionConfiguration *)_actualConfiguration;
-(void)_setActualConfiguration:(id)arg1 ;
-(BOOL)hasSession;
-(BOOL)hasConfiguration;
-(void)setSupportsRedirects:(BOOL)arg1 ;
-(void)setHasSupportsRedirects:(BOOL)arg1 ;
-(BOOL)hasSupportsRedirects;
-(void)setDelegateImplementsWillSendRequest:(BOOL)arg1 ;
-(void)setHasDelegateImplementsWillSendRequest:(BOOL)arg1 ;
-(BOOL)hasDelegateImplementsWillSendRequest;
-(void)setDelegateImplementsSessionAuthChallenge:(BOOL)arg1 ;
-(void)setHasDelegateImplementsSessionAuthChallenge:(BOOL)arg1 ;
-(BOOL)hasDelegateImplementsSessionAuthChallenge;
-(void)setDelegateImplementsTaskAuthChallenge:(BOOL)arg1 ;
-(void)setHasDelegateImplementsTaskAuthChallenge:(BOOL)arg1 ;
-(BOOL)hasDelegateImplementsTaskAuthChallenge;
-(void)setDelegateImplementsWillPerformRedirection:(BOOL)arg1 ;
-(void)setHasDelegateImplementsWillPerformRedirection:(BOOL)arg1 ;
-(BOOL)hasDelegateImplementsWillPerformRedirection;
-(void)setDelegateImplementsDidReceiveResponse:(BOOL)arg1 ;
-(void)setHasDelegateImplementsDidReceiveResponse:(BOOL)arg1 ;
-(BOOL)hasDelegateImplementsDidReceiveResponse;
-(BOOL)supportsRedirects;
-(BOOL)delegateImplementsWillSendRequest;
-(BOOL)delegateImplementsSessionAuthChallenge;
-(BOOL)delegateImplementsTaskAuthChallenge;
-(BOOL)delegateImplementsWillPerformRedirection;
-(BOOL)delegateImplementsDidReceiveResponse;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setConfiguration:(NSData *)arg1 ;
-(id)dictionaryRepresentation;
-(NSData *)configuration;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(SDURLSessionProxySessionMessage *)session;
-(void)setSession:(SDURLSessionProxySessionMessage *)arg1 ;
@end

