/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:30 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface SDURLSessionProxySessionMessage : PBCodable <NSCopying> {

	long long _idsPriority;
	unsigned long long _sequenceNumber;
	NSString* _launchUUID;
	NSString* _sessionIdentifier;
	NSString* _uuidString;
	SCD_Struct_SD10 _has;

}

@property (nonatomic,readonly) BOOL hasSessionIdentifier; 
@property (nonatomic,retain) NSString * sessionIdentifier;                   //@synthesize sessionIdentifier=_sessionIdentifier - In the implementation block
@property (nonatomic,readonly) BOOL hasUuidString; 
@property (nonatomic,retain) NSString * uuidString;                          //@synthesize uuidString=_uuidString - In the implementation block
@property (assign,nonatomic) BOOL hasSequenceNumber; 
@property (assign,nonatomic) unsigned long long sequenceNumber;              //@synthesize sequenceNumber=_sequenceNumber - In the implementation block
@property (assign,nonatomic) BOOL hasIdsPriority; 
@property (assign,nonatomic) long long idsPriority;                          //@synthesize idsPriority=_idsPriority - In the implementation block
@property (nonatomic,readonly) BOOL hasLaunchUUID; 
@property (nonatomic,retain) NSString * launchUUID;                          //@synthesize launchUUID=_launchUUID - In the implementation block
-(NSString *)launchUUID;
-(void)setLaunchUUID:(NSString *)arg1 ;
-(void)setUuidString:(NSString *)arg1 ;
-(long long)idsPriority;
-(void)setIdsPriority:(long long)arg1 ;
-(BOOL)hasLaunchUUID;
-(BOOL)hasUuidString;
-(void)setHasIdsPriority:(BOOL)arg1 ;
-(BOOL)hasIdsPriority;
-(NSString *)uuidString;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(NSString *)sessionIdentifier;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(BOOL)hasSequenceNumber;
-(void)setHasSequenceNumber:(BOOL)arg1 ;
-(unsigned long long)sequenceNumber;
-(void)setSequenceNumber:(unsigned long long)arg1 ;
-(BOOL)hasSessionIdentifier;
-(void)setSessionIdentifier:(NSString *)arg1 ;
@end

