/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:30 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/SDURLSessionProxyService.h>
#import <libobjc.A.dylib/NSXPCListenerDelegate.h>

@class NSMutableDictionary, NSString;

@interface SDURLSessionProxyClientService : SDURLSessionProxyService <NSXPCListenerDelegate> {

	NSMutableDictionary* _sessionManagers;
	unsigned long long _directWiFiRetainCount;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedService;
-(void)_onqueue_remoteDeviceStartedUp;
-(void)_onqueue_devicesDisconnected;
-(void)_onqueue_devicesConnected;
-(void)_onqueue_handleFailedMessageSend:(id)arg1 ofType:(unsigned short)arg2 ;
-(void)_onqueue_handleReceivedMessage:(id)arg1 ofType:(unsigned short)arg2 withReply:(/*^block*/id)arg3 ;
-(void)releaseDirectWiFi;
-(void)retainDirectWiFi;
-(id)init;
-(void)start;
-(BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
@end

