/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:28 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SFUnlockProtocol <NSObject>
@required
-(void)enableUnlockWithDevice:(id)arg1 fromKey:(BOOL)arg2 withPasscode:(id)arg3 completionHandler:(/*^block*/id)arg4;
-(void)disableUnlockWithDevice:(id)arg1 completionHandler:(/*^block*/id)arg2;
-(void)establishStashBagWithCompletionHandler:(/*^block*/id)arg1;
-(void)unlockStateForDevice:(id)arg1 completionHandler:(/*^block*/id)arg2;
-(void)unlockEnabledWithDevice:(id)arg1 completionHandler:(/*^block*/id)arg2;

@end

