/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:29 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <sharingd/sharingd-Structs.h>
@class NSData, NSString, SDSharePointBrowser;

@interface TXTQuery : NSObject {

	NSData* _recordData;
	DNSServiceRef_tRef _service;
	NSString* _networkProtocol;
	SDSharePointBrowser* _browser;

}

@property (retain) NSData * recordData;                        //@synthesize recordData=_recordData - In the implementation block
@property (assign) DNSServiceRef_tRef service;                 //@synthesize service=_service - In the implementation block
@property (retain) NSString * networkProtocol;                 //@synthesize networkProtocol=_networkProtocol - In the implementation block
@property (__weak) SDSharePointBrowser * browser;              //@synthesize browser=_browser - In the implementation block
-(NSData *)recordData;
-(void)setRecordData:(NSData *)arg1 ;
-(NSString *)networkProtocol;
-(void)setNetworkProtocol:(NSString *)arg1 ;
-(void)setService:(DNSServiceRef_tRef)arg1 ;
-(DNSServiceRef_tRef)service;
-(SDSharePointBrowser *)browser;
-(void)setBrowser:(SDSharePointBrowser *)arg1 ;
@end

