/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:36 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/wcd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <wcd/WCDSystemObserver.h>

@class NSNumber, NSString;

@interface WCDFirstUnlockManager : NSObject <WCDSystemObserver> {

	BOOL _remoteDeviceFirstUnlocked;
	BOOL _receivedFirstUnlockState;
	NSNumber* _localDeviceFirstUnlocked;

}

@property (nonatomic,retain) NSNumber * localDeviceFirstUnlocked;              //@synthesize localDeviceFirstUnlocked=_localDeviceFirstUnlocked - In the implementation block
@property (assign,nonatomic) BOOL remoteDeviceFirstUnlocked;                   //@synthesize remoteDeviceFirstUnlocked=_remoteDeviceFirstUnlocked - In the implementation block
@property (assign,nonatomic) BOOL receivedFirstUnlockState;                    //@synthesize receivedFirstUnlockState=_receivedFirstUnlockState - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)updateLocalFirstUnlockState;
-(void)sendStateIfNeccessary;
-(void)subscribeToAllNotifications;
-(void)debugInfoRequested:(id)arg1 ;
-(void)handlLocalFirstUnlockStateChanged;
-(id)stateDump;
-(NSNumber *)localDeviceFirstUnlocked;
-(id)loadRemoteAcknowledgedState;
-(void)requestFirstUnlockStateIfNeccessary;
-(void)sendFirstUnlockState;
-(void)clearRemoteAcknowledgedState;
-(void)setLocalDeviceFirstUnlocked:(NSNumber *)arg1 ;
-(void)saveRemoteAcknowledgedState:(id)arg1 ;
-(void)setRemoteDeviceFirstUnlocked:(BOOL)arg1 ;
-(BOOL)remoteDeviceFirstUnlocked;
-(void)sendFirstUnlockAck:(BOOL)arg1 ;
-(void)setReceivedFirstUnlockState:(BOOL)arg1 ;
-(void)saveRemoteFirstUnlockState;
-(id)loadRemoteFirstUnlockState;
-(BOOL)receivedFirstUnlockState;
-(void)sendFirstUnlockRequest;
-(void)systemObserverPairedListChanged;
-(void)handleFirstUnlockAck:(id)arg1 ;
-(void)handleFirstUnlockState:(id)arg1 ;
-(void)initializeRemoteFirstUnlockState;
-(void)handleFirstUnlockRequest:(id)arg1 ;
-(void)dealloc;
-(id)init;
@end

