/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:36 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/wcd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol WCDSystemObserver <NSObject>
@optional
-(void)systemObserverInitialSetUpComplete;
-(void)systemObserverActiveDeviceSwitchStarted;
-(void)systemObserverActiveDeviceConnectedChanged;
-(void)systemObserverPairedListChanged;
-(void)systemObserverRemoteFirstUnlockedChanged;
-(void)systemObserverGlanceIdentifiersChanged;
-(void)systemObserverNotificationIdentifiersChanged;
-(void)systemObserverInstalledApplicationsChanged;
-(void)systemObserverWatchAppsInstalledChanged;
-(void)systemObserverComplicationsInstalledChanged;
-(void)systemObserverActiveComplicationsChanged;
-(void)systemObserverUIActiveStateChanged;
-(void)systemObserverAppDidSuspendForBundleID:(id)arg1;
-(void)systemObserverAppDidTerminateForBundleID:(id)arg1;
-(void)systemObserverProcessStateChangedForBundleID:(id)arg1;

@end

