/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:39 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/sbin/wifid
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface WiFiAWDManager : NSObject
+(void)dispatchLeakyAPStatsMetricConfigOnMainThread:(id)arg1 ;
+(void)dispatchInterfaceStatsCollectionOnMainThread:(id)arg1 ;
+(void)dispatchAwdlUsageSubmissionOnMainThread:(id)arg1 ;
+(void)dispatchMetricQueryCallbackOnMainThread:(id)arg1 ;
@end

