/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:25 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/mobileactivationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct {
	void field1;
	char* field2;
	char* field3;
	long long field4;
	unsigned field5;
	int field6;
	int field7;
	int field8;
	int field9;
} SCD_Struct_MA0;

typedef struct __CFString* CFStringRef;

