/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:40 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/sbin/wirelessproxd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <wirelessproxd/CBCentralManagerDelegate.h>
#import <wirelessproxd/CBPeripheralManagerDelegate.h>

@class CBCentralManager, CBPeripheralManager, NSMutableIndexSet, NSMutableDictionary, NSDate, NSMutableArray, NSData, NSString;

@interface DaemonBluetooth : NSObject <CBCentralManagerDelegate, CBPeripheralManagerDelegate> {

	unsigned char _coreBluetoothState;
	BOOL _currentFGInterval;
	long long _centralState;
	long long _peripheralState;
	long long _cbState;
	CBCentralManager* _centralManager;
	CBPeripheralManager* _peripheralManager;
	NSMutableIndexSet* _advancedMatchingRulesIndexSet;
	NSMutableDictionary* _advancedMatchingRulesDict;
	NSDate* _unlockTime;
	NSMutableArray* _unlockTimers;
	NSMutableDictionary* _trackedPeers;
	NSMutableDictionary* _currentAdvertisers;
	NSMutableArray* _currentAdverisersPriorityQueue;
	NSMutableIndexSet* _currentlyAdveritisingIndexSet;
	NSData* _currentlyAdvertisingData;

}

@property (assign) long long centralState;                                         //@synthesize centralState=_centralState - In the implementation block
@property (assign) long long peripheralState;                                      //@synthesize peripheralState=_peripheralState - In the implementation block
@property (assign) long long cbState;                                              //@synthesize cbState=_cbState - In the implementation block
@property (assign) unsigned char coreBluetoothState;                               //@synthesize coreBluetoothState=_coreBluetoothState - In the implementation block
@property (retain) CBCentralManager * centralManager;                              //@synthesize centralManager=_centralManager - In the implementation block
@property (retain) CBPeripheralManager * peripheralManager;                        //@synthesize peripheralManager=_peripheralManager - In the implementation block
@property (retain) NSMutableIndexSet * advancedMatchingRulesIndexSet;              //@synthesize advancedMatchingRulesIndexSet=_advancedMatchingRulesIndexSet - In the implementation block
@property (retain) NSMutableDictionary * advancedMatchingRulesDict;                //@synthesize advancedMatchingRulesDict=_advancedMatchingRulesDict - In the implementation block
@property (retain) NSDate * unlockTime;                                            //@synthesize unlockTime=_unlockTime - In the implementation block
@property (retain) NSMutableArray * unlockTimers;                                  //@synthesize unlockTimers=_unlockTimers - In the implementation block
@property (retain) NSMutableDictionary * trackedPeers;                             //@synthesize trackedPeers=_trackedPeers - In the implementation block
@property (retain) NSMutableDictionary * currentAdvertisers;                       //@synthesize currentAdvertisers=_currentAdvertisers - In the implementation block
@property (retain) NSMutableArray * currentAdverisersPriorityQueue;                //@synthesize currentAdverisersPriorityQueue=_currentAdverisersPriorityQueue - In the implementation block
@property (retain) NSMutableIndexSet * currentlyAdveritisingIndexSet;              //@synthesize currentlyAdveritisingIndexSet=_currentlyAdveritisingIndexSet - In the implementation block
@property (nonatomic,retain) NSData * currentlyAdvertisingData;                    //@synthesize currentlyAdvertisingData=_currentlyAdvertisingData - In the implementation block
@property (assign) BOOL currentFGInterval;                                         //@synthesize currentFGInterval=_currentFGInterval - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)shared;
-(void)removeAdvertiserForType:(long long)arg1 ;
-(CBPeripheralManager *)peripheralManager;
-(void)stopDeviceScan:(long long)arg1 ;
-(long long)cbState;
-(long long)peripheralState;
-(long long)centralState;
-(void)addAdvertiserForType:(long long)arg1 withData:(id)arg2 fgInterval:(BOOL)arg3 ;
-(BOOL)startDeviceScan:(long long)arg1 rssiThreshold:(id)arg2 blobValue:(id)arg3 maskValue:(id)arg4 options:(id)arg5 ;
-(BOOL)connectPeripheral:(id)arg1 ;
-(void)disconnectPeripheral:(id)arg1 force:(BOOL)arg2 ;
-(long long)startTrackingPeer:(id)arg1 type:(long long)arg2 ;
-(void)stopTrackingPeer:(id)arg1 type:(long long)arg2 ;
-(void)setPeripheralManager:(CBPeripheralManager *)arg1 ;
-(BOOL)startDeviceScan:(long long)arg1 ;
-(BOOL)startDeviceScan:(long long)arg1 rssiThreshold:(id)arg2 blobValue:(id)arg3 maskValue:(id)arg4 ;
-(void)updateScanner;
-(void)addAdvertiserForType:(long long)arg1 withData:(id)arg2 ;
-(void)updateLockState;
-(NSMutableIndexSet *)advancedMatchingRulesIndexSet;
-(id)deviceTypeAsString:(long long)arg1 ;
-(NSMutableArray *)unlockTimers;
-(void)timeAfterUnlockFired:(id)arg1 ;
-(NSMutableDictionary *)advancedMatchingRulesDict;
-(void)setCentralState:(long long)arg1 ;
-(void)setCbState:(long long)arg1 ;
-(unsigned char)coreBluetoothState;
-(void)setCoreBluetoothState:(unsigned char)arg1 ;
-(NSDate *)unlockTime;
-(void)logScanningSet;
-(void)removeScanningRateTypeForDeviceType:(long long)arg1 ;
-(void)setUnlockTime:(NSDate *)arg1 ;
-(void)addScanningRateTypeForDeviceType:(long long)arg1 ;
-(void)setPeripheralState:(long long)arg1 ;
-(NSMutableDictionary *)currentAdvertisers;
-(NSMutableArray *)currentAdverisersPriorityQueue;
-(void)evaluateAdvertising;
-(NSMutableIndexSet *)currentlyAdveritisingIndexSet;
-(void)informClientsAdvertisingPending:(long long)arg1 error:(id)arg2 ;
-(NSData *)currentlyAdvertisingData;
-(BOOL)currentFGInterval;
-(void)setCurrentlyAdvertisingData:(NSData *)arg1 ;
-(void)setCurrentFGInterval:(BOOL)arg1 ;
-(void)setConnectionLatency:(id)arg1 ;
-(void)centralManager:(id)arg1 didLosePeripheral:(id)arg2 forType:(id)arg3 ;
-(id)advertiserPayloadForType:(long long)arg1 ;
-(void)evaluateAdvertisingOSX;
-(void)setAdvancedMatchingRulesIndexSet:(NSMutableIndexSet *)arg1 ;
-(void)setAdvancedMatchingRulesDict:(NSMutableDictionary *)arg1 ;
-(void)setUnlockTimers:(NSMutableArray *)arg1 ;
-(NSMutableDictionary *)trackedPeers;
-(void)setTrackedPeers:(NSMutableDictionary *)arg1 ;
-(void)setCurrentAdvertisers:(NSMutableDictionary *)arg1 ;
-(void)setCurrentAdverisersPriorityQueue:(NSMutableArray *)arg1 ;
-(void)setCurrentlyAdveritisingIndexSet:(NSMutableIndexSet *)arg1 ;
-(void)dealloc;
-(id)init;
-(void)peripheralManagerDidStartAdvertising:(id)arg1 error:(id)arg2 ;
-(void)peripheralManagerDidUpdateState:(id)arg1 ;
-(CBCentralManager *)centralManager;
-(void)setCentralManager:(CBCentralManager *)arg1 ;
-(id)retrievePeripheralsWithIdentifiers:(id)arg1 ;
-(void)centralManagerDidUpdateState:(id)arg1 ;
-(void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4 ;
-(void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2 ;
-(void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3 ;
-(void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3 ;
@end

