/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:40 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/sbin/wirelessproxd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <wirelessproxd/XPCConnectionDelegate.h>

@class XPCConnection, NSString, NSMutableArray;

@interface WPDMagicSwitch : NSObject <XPCConnectionDelegate> {

	BOOL _isScanning;
	BOOL _isAdvertising;
	BOOL _pendingStatusSent;
	XPCConnection* _connection;
	NSString* _processName;
	NSMutableArray* _scanningPeers;

}

@property (assign) BOOL isScanning;                                       //@synthesize isScanning=_isScanning - In the implementation block
@property (assign) BOOL isAdvertising;                                    //@synthesize isAdvertising=_isAdvertising - In the implementation block
@property (assign) BOOL pendingStatusSent;                                //@synthesize pendingStatusSent=_pendingStatusSent - In the implementation block
@property (nonatomic,retain) XPCConnection * connection;                  //@synthesize connection=_connection - In the implementation block
@property (retain) NSString * processName;                                //@synthesize processName=_processName - In the implementation block
@property (nonatomic,retain) NSMutableArray * scanningPeers;              //@synthesize scanningPeers=_scanningPeers - In the implementation block
-(void)reportCoreBluetoothStateChanged;
-(void)advertisingStarted:(id)arg1 ;
-(NSMutableArray *)scanningPeers;
-(id)initWithConnection:(id)arg1 processName:(id)arg2 ;
-(void)setScanningPeers:(NSMutableArray *)arg1 ;
-(BOOL)pendingStatusSent;
-(void)setPendingStatusSent:(BOOL)arg1 ;
-(void)startScanning:(id)arg1 ;
-(void)foundDevice:(id)arg1 ;
-(void)dealloc;
-(NSString *)processName;
-(XPCConnection *)connection;
-(void)setConnection:(XPCConnection *)arg1 ;
-(void)setIsScanning:(BOOL)arg1 ;
-(void)startAdvertising:(id)arg1 ;
-(void)setProcessName:(NSString *)arg1 ;
-(void)stopAdvertising;
-(void)messageArrived:(id)arg1 ;
-(void)connectionDied;
-(BOOL)isScanning;
-(void)stopScanning;
-(BOOL)isAdvertising;
-(void)setIsAdvertising:(BOOL)arg1 ;
@end

