/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:09 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/findmydeviced
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class ACAccountStore;

@interface FMDAppleAccountManager : NSObject {

	ACAccountStore* _accountStore;

}

@property (nonatomic,retain) ACAccountStore * accountStore;              //@synthesize accountStore=_accountStore - In the implementation block
+(id)sharedInstance;
-(void)syncFMIPAccountInfo;
-(id)iCloudACAccount;
-(BOOL)isKnownFMIPAccount:(id)arg1 ;
-(id)_currentFMDFMIPAccount;
-(id)fmipACAccount;
-(void)forceUserAuthForiCloudAccountWithCompletion:(/*^block*/id)arg1 really:(BOOL)arg2 ;
-(void)forceUserAuthForiCloudAccountForApp:(id)arg1 withCompletion:(/*^block*/id)arg2 really:(BOOL)arg3 ;
-(id)fmipHsaToken;
-(BOOL)populateiCloudAccountInfoIntoAccount:(id)arg1 ;
-(void)forceUserAuthForiCloudAccountWithCompletion:(/*^block*/id)arg1 ;
-(void)fixFMIPAuthTokenShouldForce:(BOOL)arg1 ;
-(void)setFMIPDataclass:(BOOL)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setAccountStore:(ACAccountStore *)arg1 ;
-(ACAccountStore *)accountStore;
-(id)initSingleton;
@end

