/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:09 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/findmydeviced
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <findmydeviced/findmydeviced-Structs.h>
@class FMDMessage, AVController, NSTimer, NSArray;

@interface FMDMessageMgr_iOS : NSObject {

	FMDMessage* _activeMessage;
	CFUserNotificationRef _cfNotification;
	AVController* _avController;
	NSTimer* _stopSoundTimer;
	NSArray* _captureDevices;

}

@property (nonatomic,retain) FMDMessage * activeMessage;                        //@synthesize activeMessage=_activeMessage - In the implementation block
@property (nonatomic,retain) CFUserNotificationRef cfNotification;              //@synthesize cfNotification=_cfNotification - In the implementation block
@property (nonatomic,retain) AVController * avController;                       //@synthesize avController=_avController - In the implementation block
@property (nonatomic,retain) NSTimer * stopSoundTimer;                          //@synthesize stopSoundTimer=_stopSoundTimer - In the implementation block
@property (nonatomic,retain) NSArray * captureDevices;                          //@synthesize captureDevices=_captureDevices - In the implementation block
+(id)sharedInstance;
-(void)setCaptureDevices:(NSArray *)arg1 ;
-(NSTimer *)stopSoundTimer;
-(CFUserNotificationRef)cfNotification;
-(FMDMessage *)activeMessage;
-(void)setCfNotification:(CFUserNotificationRef)arg1 ;
-(void)setActiveMessage:(FMDMessage *)arg1 ;
-(id)_vibrationPattern;
-(id)_fillVibrationPattern:(id)arg1 toDuration:(double)arg2 ;
-(void)_playSoundFor:(id)arg1 ;
-(void)stopSound;
-(void)_stopSoundTimerFired:(id)arg1 ;
-(void)setStopSoundTimer:(NSTimer *)arg1 ;
-(void)activateMessage:(id)arg1 ;
-(void)stopAllSounds;
-(NSArray *)captureDevices;
-(void)dealloc;
-(id)init;
-(void)setAvController:(AVController *)arg1 ;
-(AVController *)avController;
-(id)initSingleton;
-(id)_xpcTransactionNameFor:(id)arg1 ;
@end

