/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:09 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/findmydeviced
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <findmydeviced/FMDRequest.h>

@class FMDServiceProvider, CLLocation, NSArray;

@interface FMDRequestTrackedLocations : FMDRequest {

	FMDServiceProvider* _provider;
	CLLocation* _currentLocation;
	NSArray* _trackedLocations;

}

@property (nonatomic,retain) FMDServiceProvider * provider;              //@synthesize provider=_provider - In the implementation block
@property (nonatomic,retain) CLLocation * currentLocation;               //@synthesize currentLocation=_currentLocation - In the implementation block
@property (nonatomic,retain) NSArray * trackedLocations;                 //@synthesize trackedLocations=_trackedLocations - In the implementation block
-(void)deinitializeRequest;
-(id)requestUrl;
-(BOOL)canRequestBeRetriedNow;
-(BOOL)canReplace:(id)arg1 ;
-(id)initWithProvider:(id)arg1 currentLocation:(id)arg2 trackedLocations:(id)arg3 ;
-(void)setTrackedLocations:(NSArray *)arg1 ;
-(NSArray *)trackedLocations;
-(FMDServiceProvider *)provider;
-(void)setProvider:(FMDServiceProvider *)arg1 ;
-(CLLocation *)currentLocation;
-(void)setCurrentLocation:(CLLocation *)arg1 ;
-(id)requestBody;
@end

