/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:09 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/findmydeviced
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <findmydeviced/FMDRequest.h>

@class FMDServiceProvider, CLLocation, NSDictionary;

@interface FMDRequestCurrentLocation : FMDRequest {

	BOOL _finalLocation;
	unsigned char _publishReason;
	FMDServiceProvider* _provider;
	CLLocation* _location;
	NSDictionary* _locateCommand;
	double _accuracyChange;

}

@property (nonatomic,retain) FMDServiceProvider * provider;              //@synthesize provider=_provider - In the implementation block
@property (nonatomic,retain) CLLocation * location;                      //@synthesize location=_location - In the implementation block
@property (assign,nonatomic) BOOL finalLocation;                         //@synthesize finalLocation=_finalLocation - In the implementation block
@property (nonatomic,retain) NSDictionary * locateCommand;               //@synthesize locateCommand=_locateCommand - In the implementation block
@property (assign,nonatomic) unsigned char publishReason;                //@synthesize publishReason=_publishReason - In the implementation block
@property (assign,nonatomic) double accuracyChange;                      //@synthesize accuracyChange=_accuracyChange - In the implementation block
+(id)serializedFormOfLocation:(id)arg1 ;
-(void)deinitializeRequest;
-(id)requestUrl;
-(BOOL)canRequestBeRetriedNow;
-(BOOL)canReplace:(id)arg1 ;
-(void)setLocateCommand:(NSDictionary *)arg1 ;
-(void)setPublishReason:(unsigned char)arg1 ;
-(void)setAccuracyChange:(double)arg1 ;
-(unsigned char)publishReason;
-(double)accuracyChange;
-(NSDictionary *)locateCommand;
-(id)initWithProvider:(id)arg1 location:(id)arg2 finalLocation:(BOOL)arg3 locateCommand:(id)arg4 reason:(unsigned char)arg5 accuracyChange:(double)arg6 ;
-(long long)maxTimerBasedNetworkRetries;
-(long long)maxNonNetworkRelatedRetries;
-(long long)maxConsecutiveNetworkNotificationRetries;
-(CLLocation *)location;
-(void)setLocation:(CLLocation *)arg1 ;
-(FMDServiceProvider *)provider;
-(void)setProvider:(FMDServiceProvider *)arg1 ;
-(void)setFinalLocation:(BOOL)arg1 ;
-(BOOL)finalLocation;
-(id)requestBody;
@end

