/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:10 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/findmydeviced
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <findmydeviced/FMAPSDelegate.h>
#import <findmydeviced/FMDServerInteractionControllerDelegate.h>

@protocol FMDAccountStore;
@class FMDAccount, NSString, FMDLocator, FMDServerInteractionController, NSMutableDictionary;

@interface FMDServiceProvider : NSObject <FMAPSDelegate, FMDServerInteractionControllerDelegate> {

	BOOL _shutdownActivityPending;
	BOOL _waitingToMakeProviderActive;
	BOOL _completedStartupRegister;
	FMDAccount* _account;
	id<FMDAccountStore> _accountStore;
	NSString* _apsToken;
	FMDLocator* _standardLocator;
	FMDServerInteractionController* _serverInteractionController;

}

@property (nonatomic,retain) FMDAccount * account;                                                      //@synthesize account=_account - In the implementation block
@property (nonatomic,readonly) id<FMDAccountStore> accountStore;                                        //@synthesize accountStore=_accountStore - In the implementation block
@property (nonatomic,readonly) NSString * serviceName; 
@property (nonatomic,retain) NSString * apsToken;                                                       //@synthesize apsToken=_apsToken - In the implementation block
@property (nonatomic,retain) FMDLocator * standardLocator;                                              //@synthesize standardLocator=_standardLocator - In the implementation block
@property (assign,nonatomic) BOOL shutdownActivityPending;                                              //@synthesize shutdownActivityPending=_shutdownActivityPending - In the implementation block
@property (assign,nonatomic) BOOL waitingToMakeProviderActive;                                          //@synthesize waitingToMakeProviderActive=_waitingToMakeProviderActive - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * standardDeviceContext; 
@property (nonatomic,readonly) NSMutableDictionary * registerDeviceContext; 
@property (nonatomic,readonly) NSMutableDictionary * volatileDeviceInfo; 
@property (nonatomic,readonly) NSMutableDictionary * fullDeviceInfo; 
@property (nonatomic,readonly) NSMutableDictionary * locationDeviceInfo; 
@property (nonatomic,readonly) BOOL locServicesCapable; 
@property (nonatomic,readonly) BOOL locatesAllowed; 
@property (nonatomic,readonly) NSString * serviceIdentifierInURL; 
@property (nonatomic,retain) FMDServerInteractionController * serverInteractionController;              //@synthesize serverInteractionController=_serverInteractionController - In the implementation block
@property (assign,nonatomic) BOOL completedStartupRegister;                                             //@synthesize completedStartupRegister=_completedStartupRegister - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)setActiveServiceProvider:(id)arg1 ;
+(id)activeServiceProvider;
-(id)urlForRequestType:(id)arg1 ;
-(NSMutableDictionary *)standardDeviceContext;
-(void)didReceiveServerAlertForRequest:(id)arg1 ;
-(void)didReceiveAuthFailureForRequest:(id)arg1 ;
-(NSMutableDictionary *)fullDeviceInfo;
-(NSMutableDictionary *)locationDeviceInfo;
-(NSMutableDictionary *)registerDeviceContext;
-(void)wipeReceived;
-(void)ackLockCommand:(id)arg1 withStatus:(long long)arg2 withCompletion:(/*^block*/id)arg3 ;
-(id)alertActionInfoForAction:(id)arg1 andURL:(id)arg2 ;
-(void)ackMessageCommand:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)registerDeviceWithCause:(id)arg1 force:(BOOL)arg2 ;
-(void)deleteRegisterDigest;
-(void)registerCommonNotifications;
-(void)deregisterCommonNotifications;
-(id)reasonForStartupRegister;
-(void)accountAdded;
-(void)makeProviderInactive;
-(unsigned)essentialServerInfoMissingError;
-(void)tryToFetchAuthToken;
-(void)sendQueueCheckRequest:(id)arg1 ;
-(void)reinitializeProviderWithAccount:(id)arg1 ;
-(id)_constructNonVolatileFullDeviceInfo;
-(id)_constructVolatileFullDeviceInfo;
-(BOOL)waitingToMakeProviderActive;
-(void)makeProviderActive;
-(void)setShutdownActivityPending:(BOOL)arg1 ;
-(id)newLocationManager;
-(BOOL)willMakeProviderActive;
-(void)didMakeProviderActive;
-(void)willMakeProviderInactive;
-(BOOL)isProviderEnabledForLocations;
-(id)commandHandlers;
-(id)machineId;
-(void)accountRemoveRequested;
-(void)performWipe;
-(void)registerDidSucceed;
-(BOOL)locatesAllowed;
-(BOOL)shutdownActivityPending;
-(BOOL)locServicesCapable;
-(FMDLocator *)standardLocator;
-(void)setStandardLocator:(FMDLocator *)arg1 ;
-(void)sendCurrentLocation:(id)arg1 isFinished:(BOOL)arg2 forCmd:(id)arg3 withReason:(unsigned char)arg4 andAccuracyChange:(double)arg5 ;
-(void)ackLocateCommand:(id)arg1 withStatusCode:(long long)arg2 andStatusMessage:(id)arg3 withCompletion:(/*^block*/id)arg4 ;
-(void)_sendWipeAck;
-(void)_abortWipe;
-(void)_wipeNow;
-(void)_accountDidChangeFrom:(id)arg1 to:(id)arg2 ;
-(void)setWaitingToMakeProviderActive:(BOOL)arg1 ;
-(void)setApsToken:(NSString *)arg1 ;
-(void)_sendStartupRegister;
-(unsigned)authInvalidError;
-(void)didMakeProviderInactive;
-(void)deviceNameChanged:(id)arg1 ;
-(void)passcodeStateChanged:(id)arg1 ;
-(void)allowPasscodeModificationChanged:(id)arg1 ;
-(void)locationServicesStateChanged:(id)arg1 ;
-(id)_registerDigestPrefKey;
-(id)_lastForcedRegisterTimePrefKey;
-(id)substituteStandardURLPlaceholders:(id)arg1 ;
-(NSString *)serviceIdentifierInURL;
-(id)_constructStandardDeviceContext;
-(id)_constructNonCriticalFullDeviceInfo;
-(id)_constructLocationDeviceInfo;
-(NSMutableDictionary *)volatileDeviceInfo;
-(id)extraRegistrationInformation;
-(void)_registerDeviceWithCause:(id)arg1 ;
-(id)_registrationInformationDigest;
-(BOOL)completedStartupRegister;
-(void)registerDidFail;
-(void)setCompletedStartupRegister:(BOOL)arg1 ;
-(void)handleQueueCheckResponseWithStatus:(long long)arg1 andBody:(id)arg2 ;
-(void)ackWipeCommand:(id)arg1 withStatus:(long long)arg2 ;
-(id)copyHandlerForCommand:(id)arg1 params:(id)arg2 ;
-(void)showAlertFromServerResponse:(id)arg1 ;
-(void)ackRegisterCommand:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(NSString *)serviceName;
-(void)dealloc;
-(id)init;
-(void)start;
-(BOOL)enqueueRequest:(id)arg1 ;
-(void)updateAccount:(id)arg1 ;
-(void)accountInfoDidChange;
-(id<FMDAccountStore>)accountStore;
-(void)removeAccount:(id)arg1 ;
-(FMDAccount *)account;
-(void)addAccount:(id)arg1 ;
-(void)setAccount:(FMDAccount *)arg1 ;
-(FMDServerInteractionController *)serverInteractionController;
-(void)setServerInteractionController:(FMDServerInteractionController *)arg1 ;
-(void)didReceiveAPSMessage:(id)arg1 ;
-(void)didReceiveAPSToken:(id)arg1 ;
-(NSString *)apsToken;
-(void)localeChanged:(id)arg1 ;
@end

