/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:26 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/nehelper
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_xpc_object, NEHelperDelegate;
@class NSObject, NSString;

@interface NEHelperClient : NSObject {

	NSObject*<OS_xpc_object> _connection;
	id<NEHelperDelegate> _delegate;
	NSString* _name;

}

@property (readonly) NSObject*<OS_xpc_object> connection;              //@synthesize connection=_connection - In the implementation block
@property (readonly) id<NEHelperDelegate> delegate;                    //@synthesize delegate=_delegate - In the implementation block
@property (readonly) NSString * name;                                  //@synthesize name=_name - In the implementation block
-(id<NEHelperDelegate>)delegate;
-(NSString *)name;
-(NSObject*<OS_xpc_object>)connection;
-(id)initWithConnection:(id)arg1 delegate:(id)arg2 ;
@end

