/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:26 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/nehelper
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <nehelper/NEConfigurationManagerDelegate.h>

@protocol OS_dispatch_queue, OS_xpc_object;
@class NSObject, NSMutableArray;

@interface NEHelperServer : NSObject <NEConfigurationManagerDelegate> {

	NSObject*<OS_dispatch_queue> _queue;
	NSObject*<OS_xpc_object> _listener;
	NSMutableArray* _clients;

}

@property (readonly) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
@property (readonly) NSObject*<OS_xpc_object> listener;               //@synthesize listener=_listener - In the implementation block
@property (readonly) NSMutableArray * clients;                        //@synthesize clients=_clients - In the implementation block
+(void)sendReplyForMessage:(id)arg1 result:(long long)arg2 data:(id)arg3 ;
+(BOOL)verifyConnection:(id)arg1 hasEntitlement:(const char*)arg2 ;
+(void)sendAppPathsToEventAgent:(id)arg1 ;
+(void)sendSocketToEventAgent:(int)arg1 ;
+(id)sharedServer;
-(id)clientsWithName:(id)arg1 delegateClassName:(id)arg2 ;
-(void)handleEvent:(id)arg1 ofType:(const char*)arg2 ;
-(void)handleSCPreferencesChangedEvent;
-(void)handleControlSettingsFileChanged;
-(void)handleManagedPreferencesChangedForInitCheck:(BOOL)arg1 ;
-(void)handleNetworkDetectionEvaluateEvent:(id)arg1 ;
-(void)disablePluginType:(id)arg1 ;
-(id)init;
-(void)stop;
-(void)start;
-(NSObject*<OS_dispatch_queue>)queue;
-(NSObject*<OS_xpc_object>)listener;
-(id)initPrivate;
-(void)removeProfile:(id)arg1 ;
-(NSMutableArray *)clients;
-(void)acceptNewConnection:(id)arg1 ;
@end

