/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:20:37 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, SBSAssertion;

@interface IMSpringboardWallpaperManager : NSObject {

	NSObject*<OS_dispatch_queue> _sync;
	unsigned long long _pauseCount;
	SBSAssertion* _pauseAssertion;

}
+(id)sharedManager;
-(void)_incrementPause;
-(void)_decrementPause;
-(void)dealloc;
-(id)init;
-(void)_enterBackground:(id)arg1 ;
-(id)pauseAnimation;
@end

