/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:08 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/biometrickitd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol BiometricKitXpcProtocol <NSObject>
@required
-(void)connect:(id)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)registerDelegate:(BOOL)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)notifyAppIsBackground:(BOOL)arg1;
-(void)notifyAppIsInactive:(BOOL)arg1;
-(void)enroll:(int)arg1 withOptions:(id)arg2 withReplyBlock:(/*^block*/id)arg3;
-(void)match:(id)arg1 withOptions:(id)arg2 withReplyBlock:(/*^block*/id)arg3;
-(void)detectFingerWithOptions:(id)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)cancelWithReplyBlock:(/*^block*/id)arg1;
-(void)updateIdentity:(id)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)removeIdentity:(id)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)getIdentityFromUUID:(id)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)identities:(id)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)registerDSID:(unsigned long long)arg1 withOptions:(id)arg2 withReplyBlock:(/*^block*/id)arg3;
-(void)registerStoreToken:(id)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)getCountersignedStoreTokenWithReplyBlock:(/*^block*/id)arg1;
-(void)diagnostics:(int)arg1 withOptions:(id)arg2 withReplyBlock:(/*^block*/id)arg3;
-(void)timestampEvent:(unsigned long long)arg1 absoluteTime:(unsigned long long)arg2 withReplyBlock:(/*^block*/id)arg3;
-(void)getMaxIdentityCount:(int)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)setUserDSID:(unsigned long long)arg1 withOptions:(id)arg2 withReplyBlock:(/*^block*/id)arg3;
-(void)getIdentitiesDatabaseUUIDWithReplyBlock:(/*^block*/id)arg1;
-(void)getIdentitiesDatabaseHashWithReplyBlock:(/*^block*/id)arg1;
-(void)dropUnlockTokenWithReplyBlock:(/*^block*/id)arg1;
-(void)enrollContinueWithReplyBlock:(/*^block*/id)arg1;
-(void)resetAppleConnectCounterWithReplyBlock:(/*^block*/id)arg1;
-(void)pullAlignmentDataWithReplyBlock:(/*^block*/id)arg1;
-(void)pullMatchTopologyDataWithReplyBlock:(/*^block*/id)arg1;
-(void)pullMatchPolicyInfoDataWithReplyBlock:(/*^block*/id)arg1;
-(void)getNodeTopologyForIdentity:(id)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)getProtectedConfigurationWithReplyBlock:(/*^block*/id)arg1;
-(void)setProtectedConfiguration:(id)arg1 withOptions:(id)arg2 withReplyBlock:(/*^block*/id)arg3;
-(void)getProvisioningStateWithReplyBlock:(/*^block*/id)arg1;
-(void)getBioLockoutStateWithReplyBlock:(/*^block*/id)arg1;
-(void)getSensorCalibrationStatusWithReplyBlock:(/*^block*/id)arg1;
-(void)getCalibrationDataInfoWithReplyBlock:(/*^block*/id)arg1;
-(void)getSensorInfoWithReplyBlock:(/*^block*/id)arg1;
-(void)setDebugImages:(BOOL)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)pullCalibrationDataWithReplyBlock:(/*^block*/id)arg1;
-(void)pullCaptureBufferWithReplyBlock:(/*^block*/id)arg1;
-(void)pullDebugImageData:(BOOL)arg1 rotated:(BOOL)arg2 withReplyBlock:(/*^block*/id)arg3;
-(void)getSerialisedTemplateForIdentity:(id)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)getLogs:(BOOL)arg1 withReplyBlock:(/*^block*/id)arg2;
-(void)isFingerOnWithReplyBlock:(/*^block*/id)arg1;

@end

