/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 11:31:27 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileSMS.app/MobileSMS
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSMS/MobileSMS-Structs.h>
#import <UIKit/UIApplication.h>
#import <libobjc.A.dylib/IMSystemMonitorListener.h>
#import <UIKit/UIApplicationDelegate.h>

@class UIWindow, CKMessagesController, CKRegistrationViewController, NSString, NSArray, BKSProcessAssertion, TLAlert, NSURL;

@interface SMSApplication : UIApplication <IMSystemMonitorListener, UIApplicationDelegate> {

	BOOL _waitToSendFinishLaunching;
	BOOL _isLocked;
	BOOL _isSuspended;
	UIWindow* _window;
	CKMessagesController* _messagesController;
	CKRegistrationViewController* _madridRegistrationController;
	NSString* _defaultPng;
	NSArray* _suspendUnreadMessages;
	BKSProcessAssertion* _backgroundAssertion;
	TLAlert* _alert;
	BOOL _isHandlingLaunchTask;
	NSURL* _deferredLoadURL;
	/*^block*/id _alertViewHandler;

}

@property (nonatomic,retain) NSURL * deferredLoadURL;                                //@synthesize deferredLoadURL=_deferredLoadURL - In the implementation block
@property (nonatomic,retain) CKMessagesController * messagesController;              //@synthesize messagesController=_messagesController - In the implementation block
@property (nonatomic,copy) id alertViewHandler;                                      //@synthesize alertViewHandler=_alertViewHandler - In the implementation block
@property (assign,nonatomic) BOOL isHandlingLaunchTask;                              //@synthesize isHandlingLaunchTask=_isHandlingLaunchTask - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) UIWindow * window; 
-(void)startShowMessagesTest:(id)arg1 ;
-(void)startShowPeoplePickerTest:(id)arg1 ;
-(void)startCancelPeoplePickerTest:(id)arg1 ;
-(void)startSelectContactPeoplePickerTest:(id)arg1 ;
-(void)startShowNewComposeTest:(id)arg1 ;
-(void)startResolveContactTest:(id)arg1 ;
-(void)startScrollConversationsTest:(id)arg1 ;
-(void)startScrollTranscriptTest:(id)arg1 ;
-(void)startRotationTest:(id)arg1 ;
-(void)startPhotoTest:(id)arg1 ;
-(void)dismissPhotoPickerWithCompletion:(/*^block*/id)arg1 ;
-(void)showTranscriptListNotAnimated;
-(void)cleanupCurrentTest;
-(void)showNextMessage;
-(void)showTranscriptList;
-(void)scrollTranscript;
-(BOOL)validateTranscriptVisibility:(id)arg1 expected:(BOOL)arg2 withResultsDictionary:(id)arg3 ;
-(BOOL)validateTranscriptVendingIAV:(id)arg1 expected:(BOOL)arg2 withResultsDictionary:(id)arg3 ;
-(BOOL)validateEntryViewIsFirstResponder:(id)arg1 expected:(BOOL)arg2 withResultsDictionary:(id)arg3 ;
-(BOOL)validateNonzeroTranscriptInsets:(id)arg1 expected:(BOOL)arg2 withResultsDictionary:(id)arg3 ;
-(BOOL)validateBottomInsetGreaterThanIAVHeight:(id)arg1 expected:(BOOL)arg2 withResultsDictionary:(id)arg3 ;
-(BOOL)validateIAVisExpanded:(id)arg1 expected:(BOOL)arg2 withResultsDictionary:(id)arg3 ;
-(BOOL)validateTranscriptIsScrolledToBottom:(id)arg1 expected:(BOOL)arg2 withResultsDictionary:(id)arg3 ;
-(void)_recordResult:(BOOL)arg1 forKey:(id)arg2 comment:(id)arg3 resultsDictionary:(id)arg4 ;
-(BOOL)validateTranscriptNewRecipientState:(id)arg1 expected:(BOOL)arg2 withResultsDictionary:(id)arg3 ;
-(BOOL)validateRecipientSelectionControllerIsFirstResponder:(id)arg1 expected:(BOOL)arg2 withResultsDictionary:(id)arg3 ;
-(void)contactPickerDidHide;
-(void)installNotificationObserverForNotificationName:(id)arg1 notificationName:(id)arg2 forOneNotification:(BOOL)arg3 usingBlock:(/*^block*/id)arg4 ;
-(void)_dismissPeoplePickerWithCompletion:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)newComposeDismissContactPicker:(id)arg1 ;
-(void)_showPeoplePickerTest:(id)arg1 ;
-(void)tearDownShowPeoplePickerTest:(id)arg1 ;
-(void)dissmissComposeSheet;
-(void)_startPeoplePickerTest;
-(void)_startSelectContactPeoplePickerTest;
-(void)_selectContact:(id)arg1 ;
-(void)tearDownSelectContactPeoplePickerTest;
-(void)_startCancelPeoplePickerTest;
-(void)_cancelPeoplePicker;
-(void)tearDownCancelPeoplePickerTest;
-(void)_startResolveContactTest:(id)arg1 ;
-(void)tearDownResolveContactTest:(/*^block*/id)arg1 ;
-(void)_resolveContactTest:(id)arg1 ;
-(void)showPhotoPickerInTranscriptWithCompletion:(/*^block*/id)arg1 ;
-(void)selectAPhotoInPickerWithCompletion:(/*^block*/id)arg1 ;
-(void)clearEntryView;
-(void)sendSelectedPhotoWithCompletion:(/*^block*/id)arg1 ;
-(void)didShowNewCompose;
-(void)UITestDeleteTopChat;
-(void)UITestPushTranscript;
-(void)UITestPushTranscriptWithDraft;
-(void)UITestPushTranscriptKeyboardDownExpandTextEntry;
-(void)UITestPushTranscriptAndDetails;
-(void)UITestPushTranscriptAndDetailsKeyboardUp;
-(void)UITestRotateTranscript;
-(void)UITestRotateTranscriptKeyboardUp;
-(void)UITestRotateTranscriptTwice;
-(void)UITestRotateTranscriptTwiceKeyboardUp;
-(void)UITestPresentNewCompose;
-(void)UITestPresentNewComposeWithDraft;
-(void)UITestSendNewComposeDraft;
-(void)UITestNewComposeDismissContactPicker;
-(void)tearDownShowPeoplePickerTest;
-(void)finishedTest:(id)arg1 extraResults:(id)arg2 ;
-(void)failedTest:(id)arg1 ;
-(void)failedTest:(id)arg1 withFailure:(id)arg2 withResults:(id)arg3 ;
-(BOOL)runTest:(id)arg1 options:(id)arg2 ;
-(void)failedTest:(id)arg1 withFailure:(id)arg2 ;
-(void)showKeyboard;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)didShowAMessage;
-(void)didShowTranscriptList;
-(void)didDeleteChat;
-(void)deleteChat:(id)arg1 ;
-(void)didChangeOrientation:(id)arg1 ;
-(BOOL)_shouldShowMadridRegistrationView;
-(BOOL)isHandlingLaunchTask;
-(BOOL)_restoreState:(out /*^block*/id*)arg1 ;
-(void)setIsHandlingLaunchTask:(BOOL)arg1 ;
-(void)_messageReceived:(id)arg1 ;
-(void)_messageSent:(id)arg1 ;
-(void)_messageSendFailed:(id)arg1 ;
-(void)_handleAccountsChanged:(id)arg1 ;
-(void)_destroyMadridRegistrationView;
-(void)_playMessageReceivedForMessage:(id)arg1 inChat:(id)arg2 ;
-(void)_playSendSoundForMessage:(id)arg1 ;
-(void)setAlertViewHandler:(id)arg1 ;
-(void)_loadURLMessageGUID:(id)arg1 ;
-(void)_activateSiriForConversation:(id)arg1 ;
-(void)_activateSiriForRecipient:(id)arg1 ;
-(void)setWaitToSendFinishLaunching:(BOOL)arg1 ;
-(id)defaultPng;
-(NSURL *)deferredLoadURL;
-(void)setDeferredLoadURL:(NSURL *)arg1 ;
-(void)reportAppLaunchFinished;
-(void)setDefaultPng:(id)arg1 ;
-(void)_storeState;
-(void)_scheduleDeferredSetup;
-(void)_updateMadridRegistrationViewAnimated:(BOOL)arg1 ;
-(BOOL)_restoreState;
-(void)_prepareForResume:(BOOL)arg1 ;
-(void)_showMadridRegistrationViewIfNecessary;
-(void)__updateAppSnapshot;
-(void)_updateAppSnapshot;
-(void)__showMadridRegistrationViewIfNecessary;
-(void)_createMadridRegistrationViewIfNecessary;
-(id)alertViewHandler;
-(BOOL)_isShowingNewComposition;
-(void)dealloc;
-(id)init;
-(void)applicationSignificantTimeChange:(id)arg1 ;
-(void)applicationDidBecomeActive:(id)arg1 ;
-(void)_application:(id)arg1 handleSiriTask:(id)arg2 ;
-(BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 ;
-(void)applicationDidResumeFromUnderLock;
-(BOOL)applicationSuspendWithSettings:(id)arg1 ;
-(BOOL)openURL:(id)arg1 ;
-(void)applicationOpenURL:(id)arg1 ;
-(BOOL)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(/*^block*/id)arg3 ;
-(BOOL)application:(id)arg1 willContinueUserActivityWithType:(id)arg2 ;
-(void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2 ;
-(BOOL)isHandlingURL;
-(BOOL)isLocked;
-(void)handleURL:(id)arg1 ;
-(void)_applicationDidRemoveDeactivationReason:(id)arg1 ;
-(void)_prepareForSuspend;
-(void)_handleDaemonConnected:(id)arg1 ;
-(void)_handleDaemonDisconnected:(id)arg1 ;
-(void)_chatItemsDidChange:(id)arg1 ;
-(CKMessagesController *)messagesController;
-(void)setMessagesController:(CKMessagesController *)arg1 ;
-(void)systemApplicationDidSuspend;
-(void)systemApplicationDidResume;
-(void)systemApplicationDidSuspendForEventsOnly;
-(void)systemApplicationDidResumeForEventsOnly;
-(void)_resetIdleTimer;
-(void)_clearFailureBadge;
@end

