/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:40 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/CoreAuthUI.app/CoreAuthUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreAuthUI/TransitionViewController.h>

@class UIAlertController, TouchIDAlertHeaderView, UIColor;

@interface TouchIdViewController : TransitionViewController {

	UIAlertController* _alertController;
	TouchIDAlertHeaderView* _headerView;
	BOOL _dismissed;
	BOOL _showAlert;
	BOOL _showFallback;
	UIColor* _tintColor;

}
-(void)didReceiveAuthenticationData;
-(void)_setActionButtons;
-(void)_enterPassword;
-(void)dismissChildWithCompletionHandler:(/*^block*/id)arg1 ;
-(int)getPreferenceInt:(id)arg1 ;
-(void)dealloc;
-(void)loadView;
-(void)dismissViewControllerAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)mechanismEvent:(long long)arg1 ;
@end

