/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:17:21 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMAppleConnectImplComponents.h>

@interface ACMExternalAppleConnectImplComponents : ACMAppleConnectImplComponents
+(id)components;
-(id)preferences;
-(id)createHandlerWithClass:(Class)arg1 context:(id)arg2 ;
-(id)twoSVController;
-(id)uiController;
-(id)createAppleConnectImpl;
-(id)createAppleConnectImplWithMasterObject:(id)arg1 ;
-(BOOL)uiControllerLoaded;
-(void)unloadUIController;
-(id)createAuthenticationRequest;
@end

