/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:27 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/nsurlstoraged
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSBlockOperation.h>

@class NSURLStorageTaskManager, NSString;

@interface NSURLStorageTask : NSBlockOperation {

	NSURLStorageTaskManager* _taskManager;
	NSString* _keyForRequest;

}

@property (retain) NSString * keyForRequest;              //@synthesize keyForRequest=_keyForRequest - In the implementation block
-(id)initWithTaskManager:(id)arg1 ;
-(void)beginXPCTransaction;
-(void)endXPCTransaction;
-(NSString *)keyForRequest;
-(void)setKeyForRequest:(NSString *)arg1 ;
-(id)init;
@end

