/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:09 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/coreduetd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <coreduetd/IDSServiceDelegatePrivate.h>
#import <coreduetd/PSYSyncCoordinatorDelegate.h>

@protocol OS_dispatch_queue;
@class NSMutableDictionary, NSMutableSet, NSObject, CDD, CDDCommunicator, IDSService, NSDate, NSString;

@interface CDDCommControl : NSObject <IDSServiceDelegatePrivate, PSYSyncCoordinatorDelegate> {

	NSMutableDictionary* identifierCache;
	NSMutableDictionary* scheduledSendMapping;
	NSMutableSet* registeredDevices;
	NSMutableDictionary* exchangeRecords;
	NSObject*<OS_dispatch_queue> commQueue;
	int nearbyDevicesNotifyToken;
	CDD* cdd;
	CDDCommunicator* comm;
	IDSService* _service;
	NSMutableDictionary* committedTimestamps;
	NSMutableDictionary* committedState;
	NSMutableDictionary* committedTimers;
	NSMutableDictionary* pendingTimestamps;
	NSMutableDictionary* pendingState;
	NSMutableDictionary* pendingTimers;
	NSMutableDictionary* scheduledAttemptCounts;
	NSMutableDictionary* retryTimers;
	NSDate* lastForecastSent;
	NSMutableDictionary* sentRequestedTimestamps;

}

@property (nonatomic,__weak,readonly) CDD * cdd; 
@property (nonatomic,__weak,readonly) CDDCommunicator * comm; 
@property (nonatomic,readonly) NSMutableDictionary * committedTimestamps; 
@property (nonatomic,readonly) NSMutableDictionary * committedState; 
@property (nonatomic,readonly) NSMutableDictionary * committedTimers; 
@property (nonatomic,readonly) NSMutableDictionary * pendingTimestamps; 
@property (nonatomic,readonly) NSMutableDictionary * pendingState; 
@property (nonatomic,readonly) NSMutableDictionary * pendingTimers; 
@property (nonatomic,readonly) NSMutableDictionary * scheduledAttemptCounts; 
@property (nonatomic,readonly) NSMutableDictionary * retryTimers; 
@property (nonatomic,readonly) NSMutableDictionary * sentRequestedTimestamps; 
@property (nonatomic,retain) NSDate * lastForecastSent; 
@property (retain) IDSService * _service;                                                  //@synthesize service=_service - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(CDD *)cdd;
-(void)loadSavedDateIfExist;
-(void)checkDevices:(id)arg1 ;
-(id)synchronize:(id)arg1 interval:(id)arg2 withForecasts:(BOOL)arg3 ;
-(void)saveLastDate;
-(id)deviceDescriptionFromDevice:(id)arg1 ;
-(void)checkForecastSync;
-(void)receiveData:(id)arg1 context:(id)arg2 device:(id)arg3 ;
-(void)setLastForecastSent:(NSDate *)arg1 ;
-(id)deviceFromDeviceDescription:(id)arg1 ;
-(void)persistDeviceState:(id)arg1 ;
-(void)removePendingState:(id)arg1 ;
-(void)checkAccounts:(id)arg1 ;
-(id)initWithCommInstance:(id)arg1 ;
-(void)setupIDSLink;
-(void)setupPairedSyncClient;
-(id)deviceDescriptionOfDefaultPaired;
-(void)triggeredExchange:(id)arg1 opportunistic:(BOOL)arg2 queue:(id)arg3 timeout:(id)arg4 urgent:(BOOL)arg5 ;
-(void)triggeredWorldExchange;
-(id)requestDataFromDevice:(id)arg1 message:(id)arg2 ;
-(id)getDeviceStateToCommit:(id)arg1 ;
-(void)reanimateDevices:(id)arg1 ;
-(void)reanimateDeviceState:(id)arg1 ;
-(void)transactionSucceeded:(BOOL)arg1 identifier:(id)arg2 ;
-(void)scheduleDevice:(id)arg1 fired:(BOOL)arg2 ;
-(int)minBoundaryDelta;
-(int)minCompensationDelta;
-(BOOL)updateState:(long long)arg1 identifier:(id)arg2 dataIdentifier:(id)arg3 time:(id)arg4 timer:(id)arg5 ;
-(CDDCommunicator *)comm;
-(void)set_service:(IDSService *)arg1 ;
-(NSMutableDictionary *)committedTimestamps;
-(NSMutableDictionary *)committedState;
-(NSMutableDictionary *)committedTimers;
-(NSMutableDictionary *)pendingTimestamps;
-(NSMutableDictionary *)pendingTimers;
-(NSMutableDictionary *)scheduledAttemptCounts;
-(NSDate *)lastForecastSent;
-(NSMutableDictionary *)sentRequestedTimestamps;
-(void)addDevice:(id)arg1 ;
-(void)dealloc;
-(NSMutableDictionary *)retryTimers;
-(BOOL)commitTransaction:(id)arg1 ;
-(IDSService *)_service;
-(NSMutableDictionary *)pendingState;
-(void)clearState;
-(void)removeDevice:(id)arg1 ;
-(void)syncCoordinatorDidReceiveStartSyncCommand:(id)arg1 ;
-(void)service:(id)arg1 account:(id)arg2 incomingData:(id)arg3 fromID:(id)arg4 context:(id)arg5 ;
-(void)service:(id)arg1 activeAccountsChanged:(id)arg2 ;
-(void)service:(id)arg1 devicesChanged:(id)arg2 ;
-(void)service:(id)arg1 nearbyDevicesChanged:(id)arg2 ;
-(void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(BOOL)arg4 error:(id)arg5 ;
-(void)service:(id)arg1 didSwitchActivePairedDevice:(id)arg2 acknowledgementBlock:(/*^block*/id)arg3 ;
@end

