/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:09 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/coreduetd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CDDFakeDevice : NSObject {

	BOOL _isNearby;
	BOOL _isDefaultPairedDevice;
	NSString* _modelIdentifier;
	NSString* _name;
	NSString* _service;
	NSString* _idsIdentifier;
	NSString* _uniqueID;

}

@property (nonatomic,retain) NSString * modelIdentifier;              //@synthesize modelIdentifier=_modelIdentifier - In the implementation block
@property (nonatomic,retain) NSString * name;                         //@synthesize name=_name - In the implementation block
@property (nonatomic,retain) NSString * service;                      //@synthesize service=_service - In the implementation block
@property (nonatomic,retain) NSString * idsIdentifier;                //@synthesize idsIdentifier=_idsIdentifier - In the implementation block
@property (nonatomic,retain) NSString * uniqueID;                     //@synthesize uniqueID=_uniqueID - In the implementation block
@property (assign,nonatomic) BOOL isNearby;                           //@synthesize isNearby=_isNearby - In the implementation block
@property (assign,nonatomic) BOOL isDefaultPairedDevice;              //@synthesize isDefaultPairedDevice=_isDefaultPairedDevice - In the implementation block
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(void)setModelIdentifier:(NSString *)arg1 ;
-(void)setService:(NSString *)arg1 ;
-(NSString *)service;
-(void)setIsDefaultPairedDevice:(BOOL)arg1 ;
-(void)setIsNearby:(BOOL)arg1 ;
-(void)setUniqueID:(NSString *)arg1 ;
-(NSString *)uniqueID;
-(BOOL)isDefaultPairedDevice;
-(NSString *)idsIdentifier;
-(void)setIdsIdentifier:(NSString *)arg1 ;
-(NSString *)modelIdentifier;
-(BOOL)isNearby;
@end

