/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:09 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/coreduetd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate;

@interface CDDPLCoreDuetEventInterval : NSObject {

	unsigned long long clientId;
	unsigned long long attributeId;
	NSDate* startDate;
	NSDate* endDate;

}

@property (retain) NSDate * startDate; 
@property (retain) NSDate * endDate; 
@property (assign) unsigned long long clientId; 
@property (assign) unsigned long long attributeId; 
-(void)setClientId:(unsigned long long)arg1 ;
-(unsigned long long)clientId;
-(void)setEndDate:(NSDate *)arg1 ;
-(void)setStartDate:(NSDate *)arg1 ;
-(NSDate *)startDate;
-(NSDate *)endDate;
-(unsigned long long)attributeId;
-(void)setAttributeId:(unsigned long long)arg1 ;
@end

