/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:09 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/coreduetd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSXPCListener.h>
#import <libobjc.A.dylib/NSXPCListenerDelegate.h>
#import <libobjc.A.dylib/_DKDaemonInterface.h>

@protocol OS_dispatch_queue;
@class _DKKnowledgeStorage, NSObject, _DKDataProtectionStateMonitor, _DKRateLimitPolicyEnforcer, _DKPrivacyPolicyEnforcer, NSString;

@interface CDKnowledgeDaemon : NSXPCListener <NSXPCListenerDelegate, _DKDaemonInterface> {

	_DKKnowledgeStorage* _storage;
	NSObject*<OS_dispatch_queue> _responseQueue;
	_DKDataProtectionStateMonitor* _dataProtection;
	_DKRateLimitPolicyEnforcer* _rateLimitEnforcer;
	_DKPrivacyPolicyEnforcer* _privacyEnforcer;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
-(void)maintainPrivacy;
-(id)init;
-(BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
-(void)saveObjects:(id)arg1 reply:(/*^block*/id)arg2 ;
-(void)deleteObjects:(id)arg1 reply:(/*^block*/id)arg2 ;
-(void)executeQuery:(id)arg1 reply:(/*^block*/id)arg2 ;
-(BOOL)isClassCLocked;
-(void)handleError:(id)arg1 ;
@end

