/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:09 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/coreduetd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSArray, NSMutableDictionary, NSMutableArray, NSObject;

@interface CDMonitorManager : NSObject {

	NSArray* _monitorManagers;
	NSMutableDictionary* _monitors;
	NSMutableArray* _lazyMonitorNames;
	/*^block*/id _generalInstantHandler;
	/*^block*/id _generalHistoricalHandler;
	NSMutableDictionary* _instantHandlerMap;
	NSMutableDictionary* _historicalHandlerMap;
	NSObject*<OS_dispatch_queue> _queue;

}
+(id)monitorManagerForEventStreams:(id)arg1 ;
-(void)deliverNotificationEvent:(id)arg1 ;
-(void)setInstantHandler:(/*^block*/id)arg1 ;
-(void)setHistoricalHandler:(/*^block*/id)arg1 ;
-(void)addMonitor:(id)arg1 ;
-(id)_createMonitorManagers;
-(id)initWithEventStreams:(id)arg1 ;
-(void)_setInstantHandler:(/*^block*/id)arg1 forStreamName:(id)arg2 ;
-(void)_setHistoricalHandler:(/*^block*/id)arg1 forStreamName:(id)arg2 ;
-(void)_startMonitorForStreamName:(id)arg1 ;
-(void)_stopMonitorForStreamName:(id)arg1 ;
-(id)_currentEventForStreamName:(id)arg1 ;
-(void)_updateForStreamName:(id)arg1 ;
-(id)_lastUpdateForStreamName:(id)arg1 ;
-(void)setInstantHandler:(/*^block*/id)arg1 forStream:(id)arg2 ;
-(void)setHistoricalHandler:(/*^block*/id)arg1 forStream:(id)arg2 ;
-(void)startMonitorForStream:(id)arg1 ;
-(void)stopMonitorForStream:(id)arg1 ;
-(id)currentEventForStream:(id)arg1 ;
-(void)updateForStream:(id)arg1 ;
-(id)lastUpdateForStream:(id)arg1 ;
-(void)removeMonitor:(id)arg1 ;
-(BOOL)hasMonitor:(id)arg1 ;
-(id)init;
-(void)stop;
-(void)start;
-(void)update;
-(id)currentEvent;
-(id)lastUpdate;
@end

