/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 4:44:44 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/lib/system/introspection/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface OS_object : NSObject
-(void)_xref_dispose;
-(void)_dispose;
-(id)retain;
-(oneway void)release;
-(unsigned long long)retainCount;
-(BOOL)allowsWeakReference;
-(BOOL)retainWeakReference;
@end

