/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:26 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/nsurlsessiond
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NDBackgroundSessionManagerProtocol.h>
#import <nsurlsessiond/NDBackgroundSessionDelegate.h>

@protocol OS_dispatch_queue, NDSessionManagerDelegate;
@class NSMutableDictionary, NSString, NSURL, NSObject, NSXPCConnection;

@interface NDSessionManager : NSObject <NDBackgroundSessionManagerProtocol, NDBackgroundSessionDelegate> {

	NSMutableDictionary* _sessions;
	NSMutableDictionary* _reconnectingProxies;
	NSString* _clientBundleID;
	NSURL* _bundleDirectory;
	NSObject*<OS_dispatch_queue> _sessionArchiveQueue;
	id _boost;
	BOOL _isSpringBoardApp;
	NSObject*<OS_dispatch_queue> _queue;
	NSXPCConnection* _xpcConn;
	id<NDSessionManagerDelegate> _delegate;
	/*^block*/id _obliterationCompletion;

}

@property (retain) NSObject*<OS_dispatch_queue> queue;                 //@synthesize queue=_queue - In the implementation block
@property (__weak) NSXPCConnection * xpcConn;                          //@synthesize xpcConn=_xpcConn - In the implementation block
@property (__weak) id<NDSessionManagerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign) BOOL isSpringBoardApp;                              //@synthesize isSpringBoardApp=_isSpringBoardApp - In the implementation block
@property (copy) id obliterationCompletion;                            //@synthesize obliterationCompletion=_obliterationCompletion - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)archivePath;
-(id)restoreOptionsFromArchivePath:(id)arg1 ;
-(void)archiveState;
-(BOOL)connection:(id)arg1 canUseSharedContainerIdentifier:(id)arg2 ;
-(id)copyAndSanitizeClientConfiguration:(id)arg1 ;
-(void)setObliterationCompletion:(id)arg1 ;
-(void)obliterate;
-(id)obliterationCompletion;
-(void)clientApplicationWasReinstalled;
-(void)sessionCompleted:(id)arg1 withCompletionHandler:(/*^block*/id)arg2 ;
-(id)initWithDelegate:(id)arg1 bundleID:(id)arg2 isSpringBoardApp:(BOOL)arg3 ;
-(id)downloadDirectoryDataPath;
-(id)restoreState:(BOOL*)arg1 ;
-(id)getSessionWithIdentifier:(id)arg1 ;
-(BOOL)isSpringBoardApp;
-(void)setIsSpringBoardApp:(BOOL)arg1 ;
-(void)boost;
-(void)createSessionWithConfiguration:(id)arg1 clientProxy:(id)arg2 cachesDirectory:(id)arg3 options:(id)arg4 reply:(/*^block*/id)arg5 ;
-(void)sendPendingCallbacksForIdentifier:(id)arg1 reply:(/*^block*/id)arg2 ;
-(void)dropBoost;
-(void)okayToSendPendingCallbacksForIdentifier:(id)arg1 reply:(/*^block*/id)arg2 ;
-(void)releaseAssertionForSession:(id)arg1 reply:(/*^block*/id)arg2 ;
-(void)getActiveSessionIdentifiersWithReply:(/*^block*/id)arg1 ;
-(void)obliterateAllSessionsWithReply:(/*^block*/id)arg1 ;
-(void)setDelegate:(id<NDSessionManagerDelegate>)arg1 ;
-(id<NDSessionManagerDelegate>)delegate;
-(NSObject*<OS_dispatch_queue>)queue;
-(NSXPCConnection *)xpcConn;
-(void)setXpcConn:(NSXPCConnection *)arg1 ;
-(void)cleanupWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
@end

