/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:26 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/nsurlsessiond
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <nsurlsessiond/NDApplicationObserver.h>

@protocol OS_dispatch_queue, OS_dispatch_source;
@class NSURLSessionTask, NSString, NSObject, NSMutableArray, NDApplication, NDDuetReporter, UMUserSyncTask;

@interface NDTaskMonitor : NSObject <NDApplicationObserver> {

	NSURLSessionTask* _task;
	NSString* _clientBundleIdentifier;
	NSString* _clientSecondaryIdentifier;
	NSObject*<OS_dispatch_queue> _queue;
	NSObject*<OS_dispatch_source> _throughputTimer;
	NSMutableArray* _progressTimestamps;
	NSMutableArray* _progressValues;
	unsigned long long _throughputInterval;
	NDApplication* _monitoredApplication;
	NDDuetReporter* _duetReporter;
	double _throughputMonitoringStartTime;
	BOOL _startedDuetReporter;
	BOOL _connectionIsCellular;
	BOOL _hasTransferredData;
	BOOL _discretionary;
	BOOL _explicitlyDiscretionary;
	BOOL _performsNonDiscretionaryThrougputMonitoring;
	BOOL _mayBeDemotedToDiscretionary;
	UMUserSyncTask* _UMSyncTask;
	int _powerMonitorToken;
	long long _basePriority;

}

@property (assign) long long basePriority;                          //@synthesize basePriority=_basePriority - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)taskWillResume;
-(void)taskWillSuspend;
-(id)initWithTask:(id)arg1 taskInfo:(id)arg2 clientBundleIdentifier:(id)arg3 secondaryIdentifier:(id)arg4 monitoredApplication:(id)arg5 priority:(long long)arg6 options:(unsigned long long)arg7 queue:(id)arg8 ;
-(void)taskTransferredData:(unsigned long long)arg1 countOfBytesReceived:(unsigned long long)arg2 ;
-(void)applicationWasQuitFromAppSwitcher:(id)arg1 ;
-(void)backgroundUpdatesDisabledForApplication:(id)arg1 ;
-(void)applicationEnteredForeground:(id)arg1 ;
-(void)applicationNoLongerInForeground:(id)arg1 ;
-(double)currentThroughputThreshold;
-(void)setThroughputTimerForCurrentInterval;
-(long long)currentIntervalEndDelta;
-(void)startThroughputMonitoringIfAppropriate;
-(void)calculateThroughput;
-(void)stopThroughputMonitoring;
-(void)startThroughputMonitoring;
-(long long)basePriority;
-(void)setBasePriority:(long long)arg1 ;
-(void)cancel;
@end

