/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:26 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/nsurlsessiond
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_xpc_object;
@class NSObject, NSDictionary, NSMutableDictionary;

@interface NDUserEventAgentConnection : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	NSObject*<OS_xpc_object> _connection;
	NSObject*<OS_xpc_object> _listener;
	NSDictionary* _registeredClients;
	NSMutableDictionary* _pendingWakes;

}
+(id)sharedUserEventAgentConnection;
-(void)removePendingWakeForClient:(id)arg1 sessionIdentifier:(id)arg2 ;
-(void)wakeClientUponNotification:(id)arg1 sessionIdentifier:(id)arg2 ;
-(void)launchProcessWithIdentifier:(id)arg1 sessionIdentifier:(id)arg2 ;
-(BOOL)canLaunchProcessWithIdentifier:(id)arg1 ;
-(id)init;
-(void)start;
-(void)handleNewConnection:(id)arg1 ;
@end

