/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:19:04 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotifier.h>

@class NSSet, BluetoothManager;

@interface RTBluetoothManager : RTNotifier {

	BOOL _observingConnections;
	NSSet* _connectedDevices;
	long long _carKitConnectionState;

}

@property (nonatomic,readonly) BluetoothManager * bluetoothManager; 
@property (nonatomic,retain) NSSet * connectedDevices;                           //@synthesize connectedDevices=_connectedDevices - In the implementation block
@property (assign,nonatomic) BOOL observingConnections;                          //@synthesize observingConnections=_observingConnections - In the implementation block
@property (assign,nonatomic) long long carKitConnectionState;                    //@synthesize carKitConnectionState=_carKitConnectionState - In the implementation block
+(id)sharedInstance;
+(id)carKitConnectionStateToString:(long long)arg1 ;
-(BOOL)interestedInDeviceType:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(NSSet *)connectedDevices;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(long long)carKitConnectionState;
-(BluetoothManager *)bluetoothManager;
-(void)setConnectedDevices:(NSSet *)arg1 ;
-(long long)getCarKitConnectionStateFromConnectedDevices:(id)arg1 ;
-(void)setCarKitConnectionState:(long long)arg1 ;
-(void)updateConnections;
-(void)setObservingConnections:(BOOL)arg1 ;
-(void)shouldObserveConnections;
-(void)_fetchCarKitConnectedStateWithHandler:(/*^block*/id)arg1 ;
-(void)fetchCarKitConnectedStateWithHandler:(/*^block*/id)arg1 ;
-(BOOL)observingConnections;
@end

