/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:37 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/sbin/BTServer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCoreServices/LSApplicationWorkspaceObserver.h>

@protocol UninstallObserverProtocol;
@class NSObject;

@interface UninstallObserver : LSApplicationWorkspaceObserver {

	NSObject*<UninstallObserverProtocol> _delegate;

}

@property (assign,nonatomic) NSObject*<UninstallObserverProtocol> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)setDelegate:(NSObject*<UninstallObserverProtocol>)arg1 ;
-(void)dealloc;
-(id)init;
-(NSObject*<UninstallObserverProtocol>)delegate;
-(void)applicationsDidUninstall:(id)arg1 ;
@end

