/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:19:20 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Calculator.app/Frameworks/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/Swift._ContiguousArrayStorageBase.h>

@interface Swift._EmptyArrayStorage : Swift._ContiguousArrayStorageBase {

	 countAndCapacity;

}
-(id)initWith_doNotCallMe:(void)arg1 ;
-(id)init;
@end

