/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 11:31:33 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Reminders.app/PlugIns/RemindersWidget.appex/RemindersWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <RemindersWidget/RemindersWidget-Structs.h>
#import <UIKit/UIViewController.h>
#import <RemindersWidget/NCWidgetProviding.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>
#import <RemindersWidget/RemindersCheckboxCellDelegate.h>

@class UITableView, NSString;

@interface RemindersWidgetViewController : UIViewController <NCWidgetProviding, UITableViewDataSource, UITableViewDelegate, RemindersCheckboxCellDelegate> {

	UITableView* _table;
	double _leftMargin;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedModel;
-(void)reloadReminders:(/*^block*/id)arg1 ;
-(double)_calculatePreferredHeight;
-(unsigned long long)cellContentsMaskForReminder:(id)arg1 ;
-(unsigned long long)positionOfDeadlineInCells;
-(id)dueDateStringForReminder:(id)arg1 ;
-(void)_recalculatePreferredViewSize;
-(void)checkboxCellDidTapCheckbox:(id)arg1 ;
-(void)eventStoreChanged;
-(void)dealloc;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3 ;
-(BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didUnhighlightRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)tableViewDidFinishReload:(id)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)_significantTimeChange:(id)arg1 ;
-(void)widgetPerformUpdateWithCompletionHandler:(/*^block*/id)arg1 ;
-(UIEdgeInsets)widgetMarginInsetsForProposedMarginInsets:(UIEdgeInsets)arg1 ;
@end

