/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:18 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class ALActivityOverrideMsg, ALCLAllDayHeartRate, ALCLBodyMetrics, ALCMCalorieData, ALCMCoarseElevation, ALCLElevation, ALCMFitnessTracking, ALCLIDSStatus, ALCLJacksonData, ALMotionState, ALCLNatalieDataDeprecated, ALCLOdometer, ALCLRowingModel, ALCLSedentaryAlarmData, ALCLSedentaryAlarmDataDeprecated, ALCLSessionCatherine, ALCLStairClimbingModel, ALCLStepCountEntry, ALCLStrideCalEntry, ALCLStrideCalEntryDeprecated;

@interface ALActivityLog : PBCodable <NSCopying> {

	double _timestamp;
	ALActivityOverrideMsg* _activityOverrideMsg;
	ALCLAllDayHeartRate* _allDayHeartRate;
	ALCLBodyMetrics* _bodyMetrics;
	ALCMCalorieData* _calorieData;
	ALCMCoarseElevation* _coarseElevation;
	ALCLElevation* _elevation;
	ALCMFitnessTracking* _fitnessTracking;
	ALCLIDSStatus* _idsStatus;
	ALCLJacksonData* _jacksonData;
	ALMotionState* _motionState;
	ALCLNatalieDataDeprecated* _natalieData;
	ALCLOdometer* _odometer;
	ALCLRowingModel* _rowingModel;
	ALCLSedentaryAlarmData* _sedentaryAlarmData;
	ALCLSedentaryAlarmDataDeprecated* _sedentaryAlarmDataDeprecated;
	ALCLSessionCatherine* _sessionCatherineData;
	ALCLStairClimbingModel* _stairClimbingModel;
	ALCLStepCountEntry* _stepCountData;
	ALCLStrideCalEntry* _strideCalData;
	ALCLStrideCalEntryDeprecated* _strideCalDataDeprecated;

}

@property (assign,nonatomic) double timestamp;                                                             //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasActivityOverrideMsg; 
@property (nonatomic,retain) ALActivityOverrideMsg * activityOverrideMsg;                                  //@synthesize activityOverrideMsg=_activityOverrideMsg - In the implementation block
@property (nonatomic,readonly) BOOL hasBodyMetrics; 
@property (nonatomic,retain) ALCLBodyMetrics * bodyMetrics;                                                //@synthesize bodyMetrics=_bodyMetrics - In the implementation block
@property (nonatomic,readonly) BOOL hasMotionState; 
@property (nonatomic,retain) ALMotionState * motionState;                                                  //@synthesize motionState=_motionState - In the implementation block
@property (nonatomic,readonly) BOOL hasStepCountData; 
@property (nonatomic,retain) ALCLStepCountEntry * stepCountData;                                           //@synthesize stepCountData=_stepCountData - In the implementation block
@property (nonatomic,readonly) BOOL hasSessionCatherineData; 
@property (nonatomic,retain) ALCLSessionCatherine * sessionCatherineData;                                  //@synthesize sessionCatherineData=_sessionCatherineData - In the implementation block
@property (nonatomic,readonly) BOOL hasJacksonData; 
@property (nonatomic,retain) ALCLJacksonData * jacksonData;                                                //@synthesize jacksonData=_jacksonData - In the implementation block
@property (nonatomic,readonly) BOOL hasStrideCalData; 
@property (nonatomic,retain) ALCLStrideCalEntry * strideCalData;                                           //@synthesize strideCalData=_strideCalData - In the implementation block
@property (nonatomic,readonly) BOOL hasSedentaryAlarmData; 
@property (nonatomic,retain) ALCLSedentaryAlarmData * sedentaryAlarmData;                                  //@synthesize sedentaryAlarmData=_sedentaryAlarmData - In the implementation block
@property (nonatomic,readonly) BOOL hasAllDayHeartRate; 
@property (nonatomic,retain) ALCLAllDayHeartRate * allDayHeartRate;                                        //@synthesize allDayHeartRate=_allDayHeartRate - In the implementation block
@property (nonatomic,readonly) BOOL hasCalorieData; 
@property (nonatomic,retain) ALCMCalorieData * calorieData;                                                //@synthesize calorieData=_calorieData - In the implementation block
@property (nonatomic,readonly) BOOL hasCoarseElevation; 
@property (nonatomic,retain) ALCMCoarseElevation * coarseElevation;                                        //@synthesize coarseElevation=_coarseElevation - In the implementation block
@property (nonatomic,readonly) BOOL hasFitnessTracking; 
@property (nonatomic,retain) ALCMFitnessTracking * fitnessTracking;                                        //@synthesize fitnessTracking=_fitnessTracking - In the implementation block
@property (nonatomic,readonly) BOOL hasOdometer; 
@property (nonatomic,retain) ALCLOdometer * odometer;                                                      //@synthesize odometer=_odometer - In the implementation block
@property (nonatomic,readonly) BOOL hasElevation; 
@property (nonatomic,retain) ALCLElevation * elevation;                                                    //@synthesize elevation=_elevation - In the implementation block
@property (nonatomic,readonly) BOOL hasIdsStatus; 
@property (nonatomic,retain) ALCLIDSStatus * idsStatus;                                                    //@synthesize idsStatus=_idsStatus - In the implementation block
@property (nonatomic,readonly) BOOL hasStairClimbingModel; 
@property (nonatomic,retain) ALCLStairClimbingModel * stairClimbingModel;                                  //@synthesize stairClimbingModel=_stairClimbingModel - In the implementation block
@property (nonatomic,readonly) BOOL hasRowingModel; 
@property (nonatomic,retain) ALCLRowingModel * rowingModel;                                                //@synthesize rowingModel=_rowingModel - In the implementation block
@property (nonatomic,readonly) BOOL hasNatalieData; 
@property (nonatomic,retain) ALCLNatalieDataDeprecated * natalieData;                                      //@synthesize natalieData=_natalieData - In the implementation block
@property (nonatomic,readonly) BOOL hasSedentaryAlarmDataDeprecated; 
@property (nonatomic,retain) ALCLSedentaryAlarmDataDeprecated * sedentaryAlarmDataDeprecated;              //@synthesize sedentaryAlarmDataDeprecated=_sedentaryAlarmDataDeprecated - In the implementation block
@property (nonatomic,readonly) BOOL hasStrideCalDataDeprecated; 
@property (nonatomic,retain) ALCLStrideCalEntryDeprecated * strideCalDataDeprecated;                       //@synthesize strideCalDataDeprecated=_strideCalDataDeprecated - In the implementation block
-(void)setActivityOverrideMsg:(ALActivityOverrideMsg *)arg1 ;
-(void)setBodyMetrics:(ALCLBodyMetrics *)arg1 ;
-(void)setMotionState:(ALMotionState *)arg1 ;
-(void)setStepCountData:(ALCLStepCountEntry *)arg1 ;
-(void)setSessionCatherineData:(ALCLSessionCatherine *)arg1 ;
-(void)setJacksonData:(ALCLJacksonData *)arg1 ;
-(void)setStrideCalData:(ALCLStrideCalEntry *)arg1 ;
-(void)setSedentaryAlarmData:(ALCLSedentaryAlarmData *)arg1 ;
-(void)setAllDayHeartRate:(ALCLAllDayHeartRate *)arg1 ;
-(void)setCalorieData:(ALCMCalorieData *)arg1 ;
-(void)setCoarseElevation:(ALCMCoarseElevation *)arg1 ;
-(void)setFitnessTracking:(ALCMFitnessTracking *)arg1 ;
-(void)setStairClimbingModel:(ALCLStairClimbingModel *)arg1 ;
-(void)setRowingModel:(ALCLRowingModel *)arg1 ;
-(void)setNatalieData:(ALCLNatalieDataDeprecated *)arg1 ;
-(void)setSedentaryAlarmDataDeprecated:(ALCLSedentaryAlarmDataDeprecated *)arg1 ;
-(void)setStrideCalDataDeprecated:(ALCLStrideCalEntryDeprecated *)arg1 ;
-(BOOL)hasActivityOverrideMsg;
-(BOOL)hasBodyMetrics;
-(BOOL)hasMotionState;
-(BOOL)hasStepCountData;
-(BOOL)hasSessionCatherineData;
-(BOOL)hasJacksonData;
-(BOOL)hasStrideCalData;
-(BOOL)hasSedentaryAlarmData;
-(BOOL)hasAllDayHeartRate;
-(BOOL)hasCalorieData;
-(BOOL)hasCoarseElevation;
-(BOOL)hasFitnessTracking;
-(BOOL)hasOdometer;
-(BOOL)hasElevation;
-(BOOL)hasIdsStatus;
-(BOOL)hasStairClimbingModel;
-(BOOL)hasRowingModel;
-(BOOL)hasNatalieData;
-(BOOL)hasSedentaryAlarmDataDeprecated;
-(BOOL)hasStrideCalDataDeprecated;
-(ALActivityOverrideMsg *)activityOverrideMsg;
-(ALCLBodyMetrics *)bodyMetrics;
-(ALMotionState *)motionState;
-(ALCLStepCountEntry *)stepCountData;
-(ALCLSessionCatherine *)sessionCatherineData;
-(ALCLJacksonData *)jacksonData;
-(ALCLStrideCalEntry *)strideCalData;
-(ALCLSedentaryAlarmData *)sedentaryAlarmData;
-(ALCLAllDayHeartRate *)allDayHeartRate;
-(ALCMCalorieData *)calorieData;
-(ALCMCoarseElevation *)coarseElevation;
-(ALCMFitnessTracking *)fitnessTracking;
-(ALCLStairClimbingModel *)stairClimbingModel;
-(ALCLRowingModel *)rowingModel;
-(ALCLNatalieDataDeprecated *)natalieData;
-(ALCLSedentaryAlarmDataDeprecated *)sedentaryAlarmDataDeprecated;
-(ALCLStrideCalEntryDeprecated *)strideCalDataDeprecated;
-(ALCLElevation *)elevation;
-(void)setElevation:(ALCLElevation *)arg1 ;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(double)timestamp;
-(void)setTimestamp:(double)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(ALCLOdometer *)odometer;
-(void)setOdometer:(ALCLOdometer *)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setIdsStatus:(ALCLIDSStatus *)arg1 ;
-(ALCLIDSStatus *)idsStatus;
@end

