/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:20 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface ALCLNatalieDataDeprecated : PBCodable <NSCopying> {

	long long _basalNatalies;
	double _duration;
	double _mets;
	long long _natalies;
	double _timestamp;
	int _activityType;
	float _basalMETs;
	int _recordId;
	BOOL _isStanding;
	BOOL _regularEntry;
	SCD_Struct_AL43 _has;

}

@property (assign,nonatomic) BOOL hasRecordId; 
@property (assign,nonatomic) int recordId;                         //@synthesize recordId=_recordId - In the implementation block
@property (assign,nonatomic) int activityType;                     //@synthesize activityType=_activityType - In the implementation block
@property (assign,nonatomic) BOOL isStanding;                      //@synthesize isStanding=_isStanding - In the implementation block
@property (assign,nonatomic) BOOL hasMets; 
@property (assign,nonatomic) double mets;                          //@synthesize mets=_mets - In the implementation block
@property (assign,nonatomic) BOOL hasBasalMETs; 
@property (assign,nonatomic) float basalMETs;                      //@synthesize basalMETs=_basalMETs - In the implementation block
@property (assign,nonatomic) long long natalies;                   //@synthesize natalies=_natalies - In the implementation block
@property (assign,nonatomic) BOOL hasBasalNatalies; 
@property (assign,nonatomic) long long basalNatalies;              //@synthesize basalNatalies=_basalNatalies - In the implementation block
@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) double timestamp;                     //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasDuration; 
@property (assign,nonatomic) double duration;                      //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) BOOL regularEntry;                    //@synthesize regularEntry=_regularEntry - In the implementation block
-(BOOL)regularEntry;
-(void)setRegularEntry:(BOOL)arg1 ;
-(void)setHasRecordId:(BOOL)arg1 ;
-(void)setIsStanding:(BOOL)arg1 ;
-(BOOL)isStanding;
-(void)setMets:(double)arg1 ;
-(void)setHasMets:(BOOL)arg1 ;
-(BOOL)hasMets;
-(void)setBasalMETs:(float)arg1 ;
-(void)setHasBasalMETs:(BOOL)arg1 ;
-(BOOL)hasBasalMETs;
-(void)setBasalNatalies:(long long)arg1 ;
-(void)setHasBasalNatalies:(BOOL)arg1 ;
-(BOOL)hasBasalNatalies;
-(float)basalMETs;
-(void)setNatalies:(long long)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(double)timestamp;
-(double)duration;
-(void)setDuration:(double)arg1 ;
-(void)setTimestamp:(double)arg1 ;
-(int)activityType;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(double)mets;
-(long long)natalies;
-(long long)basalNatalies;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasTimestamp;
-(BOOL)hasDuration;
-(void)setHasDuration:(BOOL)arg1 ;
-(void)setActivityType:(int)arg1 ;
-(void)setRecordId:(int)arg1 ;
-(BOOL)hasRecordId;
-(int)recordId;
@end

