/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:18 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, NSLock;

@interface CalTrackFinder : NSObject {

	double _meanPace;
	long long _session;
	/*^block*/id _calTrackHandler;
	double _paceFitFactor;
	NSMutableArray* _positions;
	NSMutableArray* _paces;
	NSMutableArray* _locFiltWindow;
	NSLock* _calLock;

}

@property (copy) id calTrackHandler;                            //@synthesize calTrackHandler=_calTrackHandler - In the implementation block
@property (assign) double paceFitFactor;                        //@synthesize paceFitFactor=_paceFitFactor - In the implementation block
@property (retain) NSMutableArray * positions;                  //@synthesize positions=_positions - In the implementation block
@property (retain) NSMutableArray * paces;                      //@synthesize paces=_paces - In the implementation block
@property (retain) NSMutableArray * locFiltWindow;              //@synthesize locFiltWindow=_locFiltWindow - In the implementation block
@property (retain) NSLock * calLock;                            //@synthesize calLock=_calLock - In the implementation block
-(NSLock *)calLock;
-(void)closeCurrentTrack;
-(NSMutableArray *)locFiltWindow;
-(id)processLocFilterWindow;
-(void)addPositionToTrack:(id)arg1 ;
-(NSMutableArray *)positions;
-(NSMutableArray *)paces;
-(void)updateMeanPace;
-(id)calTrackHandler;
-(void)clearPositions;
-(void)updateSession:(long long)arg1 ;
-(void)updatePosition:(id)arg1 ;
-(void)setCalTrackHandler:(id)arg1 ;
-(double)paceFitFactor;
-(void)setPaceFitFactor:(double)arg1 ;
-(void)setPositions:(NSMutableArray *)arg1 ;
-(void)setPaces:(NSMutableArray *)arg1 ;
-(void)setLocFiltWindow:(NSMutableArray *)arg1 ;
-(void)setCalLock:(NSLock *)arg1 ;
-(void)dealloc;
-(id)init;
-(void)stop;
@end

