/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:19 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface CLCandy : NSObject
+(BOOL)verifyData:(id)arg1 matchesSignature:(id)arg2 ;
+(id)signData:(id)arg1 ;
@end

