/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:20 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ProtocolBuffer/PBRequester.h>
#import <libobjc.A.dylib/NSURLConnectionDelegate.h>

@class NSString;

@interface CLCustomAuthPBRequester : PBRequester <NSURLConnectionDelegate> {

	NSString* _sslHostname;

}

@property (nonatomic,retain) NSString * sslHostname;                //@synthesize sslHostname=_sslHostname - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithURL:(id)arg1 andDelegate:(id)arg2 validatingAgainstHostname:(id)arg3 ;
-(void)setSslHostname:(NSString *)arg1 ;
-(id)createHostValue;
-(NSString *)sslHostname;
-(void)dealloc;
-(void)start;
-(void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2 ;
-(id)initWithURL:(id)arg1 andDelegate:(id)arg2 ;
@end

