/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:20 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <locationd/locationd-Structs.h>
@class NSMutableArray, GEOTileKeyList;

@interface CLMapDataSourceBase : NSObject {

	BOOL _debug;
	NSMutableArray* _cacheHints;
	NSMutableArray* _cache;
	GEOTileKeyList* _pending;
	BOOL _allowsNetworkUsage;
	int _tileSetStyle;
	long long _zoomLevel;

}

@property (assign,nonatomic) BOOL allowsNetworkUsage;              //@synthesize allowsNetworkUsage=_allowsNetworkUsage - In the implementation block
@property (assign,nonatomic) int tileSetStyle;                     //@synthesize tileSetStyle=_tileSetStyle - In the implementation block
@property (assign,nonatomic) long long zoomLevel;                  //@synthesize zoomLevel=_zoomLevel - In the implementation block
@property (assign,nonatomic) BOOL debug;                           //@synthesize debug=_debug - In the implementation block
-(void)addCacheHint:(id)arg1 ;
-(void)openConnections;
-(void)updateTileCache;
-(void)downloadTilesForKeys:(id)arg1 ;
-(id)initWithTileSetStyle:(int)arg1 zoomLevel:(long long)arg2 ;
-(void)removeCacheHint:(id)arg1 ;
-(void)removeAllCacheHints;
-(void)closeConnections;
-(void)clearTileCache;
-(BOOL)allowsNetworkUsage;
-(void)setAllowsNetworkUsage:(BOOL)arg1 ;
-(void)setDebug:(BOOL)arg1 ;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(BOOL)debug;
-(id)tileForKey:(GEOTileKey*)arg1 ;
-(void)setZoomLevel:(long long)arg1 ;
-(int)tileSetStyle;
-(void)setTileSetStyle:(int)arg1 ;
-(long long)zoomLevel;
@end

