/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:21 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSUUID, NSNumber, NSString, NSData;

@interface CLWPZone : NSObject <NSCopying> {

	NSUUID* _proximityUUID;
	NSNumber* _major;
	NSNumber* _minor;
	NSString* _identifier;
	NSData* _advertisementData;

}

@property (copy,readonly) NSUUID * proximityUUID;                    //@synthesize proximityUUID=_proximityUUID - In the implementation block
@property (copy,readonly) NSNumber * major;                          //@synthesize major=_major - In the implementation block
@property (copy,readonly) NSNumber * minor;                          //@synthesize minor=_minor - In the implementation block
@property (copy,readonly) NSString * identifier;                     //@synthesize identifier=_identifier - In the implementation block
@property (retain,readonly) NSData * advertisementData;              //@synthesize advertisementData=_advertisementData - In the implementation block
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(NSString *)identifier;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSNumber *)major;
-(NSNumber *)minor;
-(NSData *)advertisementData;
-(NSUUID *)proximityUUID;
-(id)initWithProximityUUID:(id)arg1 major:(id)arg2 minor:(id)arg3 identifier:(id)arg4 ;
@end

