/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:20 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CMStrideCalibratorServiceProtocol <CLIntersiloServiceProtocol>
@required
-(void)setBins:(id)arg1;
-(void)resetBins;
-(id)syncgetDefaultBins;
-(BOOL)syncgetIsCalibrationConvergedForSpeed:(double)arg1;
-(void)setGizmoSession:(long long)arg1;
-(double)syncgetKValueForSpeed:(double)arg1;
-(id)syncgetBins;
-(BOOL)syncgetIsWalkCalibrationAvailable;
-(BOOL)syncgetIsRunCalibrationAvailable;
-(void)setLatestTrack:(id)arg1;
-(void)setLatestInvalidGradientTrack:(id)arg1;

@end

