/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:20 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, CRLocation, CRCellNeighborsGroup, NSMutableArray;

@interface CRLteCellTowerLocation : PBCodable <NSCopying> {

	double _cellLatitude;
	double _cellLongitude;
	NSString* _appBundleId;
	int _bandInfo;
	int _ci;
	int _ecn0;
	CRLocation* _location;
	int _mcc;
	int _mnc;
	CRCellNeighborsGroup* _neighborGroup;
	NSMutableArray* _neighbors;
	NSString* _operatorName;
	int _pid;
	int _rscp;
	int _rssi;
	int _serverHash;
	int _tac;
	int _uarfcn;
	SCD_Struct_AL5 _has;

}

@property (assign,nonatomic) int mcc;                                           //@synthesize mcc=_mcc - In the implementation block
@property (assign,nonatomic) int mnc;                                           //@synthesize mnc=_mnc - In the implementation block
@property (assign,nonatomic) int tac;                                           //@synthesize tac=_tac - In the implementation block
@property (assign,nonatomic) int ci;                                            //@synthesize ci=_ci - In the implementation block
@property (assign,nonatomic) BOOL hasUarfcn; 
@property (assign,nonatomic) int uarfcn;                                        //@synthesize uarfcn=_uarfcn - In the implementation block
@property (assign,nonatomic) BOOL hasPid; 
@property (assign,nonatomic) int pid;                                           //@synthesize pid=_pid - In the implementation block
@property (assign,nonatomic) BOOL hasBandInfo; 
@property (assign,nonatomic) int bandInfo;                                      //@synthesize bandInfo=_bandInfo - In the implementation block
@property (nonatomic,retain) CRLocation * location;                             //@synthesize location=_location - In the implementation block
@property (nonatomic,readonly) BOOL hasAppBundleId; 
@property (nonatomic,retain) NSString * appBundleId;                            //@synthesize appBundleId=_appBundleId - In the implementation block
@property (nonatomic,readonly) BOOL hasOperatorName; 
@property (nonatomic,retain) NSString * operatorName;                           //@synthesize operatorName=_operatorName - In the implementation block
@property (assign,nonatomic) BOOL hasCellLatitude; 
@property (assign,nonatomic) double cellLatitude;                               //@synthesize cellLatitude=_cellLatitude - In the implementation block
@property (assign,nonatomic) BOOL hasCellLongitude; 
@property (assign,nonatomic) double cellLongitude;                              //@synthesize cellLongitude=_cellLongitude - In the implementation block
@property (assign,nonatomic) BOOL hasServerHash; 
@property (assign,nonatomic) int serverHash;                                    //@synthesize serverHash=_serverHash - In the implementation block
@property (assign,nonatomic) BOOL hasEcn0; 
@property (assign,nonatomic) int ecn0;                                          //@synthesize ecn0=_ecn0 - In the implementation block
@property (assign,nonatomic) BOOL hasRscp; 
@property (assign,nonatomic) int rscp;                                          //@synthesize rscp=_rscp - In the implementation block
@property (assign,nonatomic) BOOL hasRssi; 
@property (assign,nonatomic) int rssi;                                          //@synthesize rssi=_rssi - In the implementation block
@property (nonatomic,retain) NSMutableArray * neighbors;                        //@synthesize neighbors=_neighbors - In the implementation block
@property (nonatomic,readonly) BOOL hasNeighborGroup; 
@property (nonatomic,retain) CRCellNeighborsGroup * neighborGroup;              //@synthesize neighborGroup=_neighborGroup - In the implementation block
-(int)mcc;
-(int)mnc;
-(BOOL)hasUarfcn;
-(int)uarfcn;
-(void)setMcc:(int)arg1 ;
-(void)setMnc:(int)arg1 ;
-(void)setServerHash:(int)arg1 ;
-(void)setHasServerHash:(BOOL)arg1 ;
-(BOOL)hasServerHash;
-(int)serverHash;
-(void)setNeighbors:(NSMutableArray *)arg1 ;
-(void)setNeighborGroup:(CRCellNeighborsGroup *)arg1 ;
-(unsigned long long)neighborsCount;
-(void)clearNeighbors;
-(BOOL)hasAppBundleId;
-(BOOL)hasOperatorName;
-(void)setEcn0:(int)arg1 ;
-(void)setHasEcn0:(BOOL)arg1 ;
-(BOOL)hasEcn0;
-(void)setRscp:(int)arg1 ;
-(void)setHasRscp:(BOOL)arg1 ;
-(BOOL)hasRscp;
-(BOOL)hasNeighborGroup;
-(int)ci;
-(void)setCi:(int)arg1 ;
-(int)ecn0;
-(int)rscp;
-(NSMutableArray *)neighbors;
-(CRCellNeighborsGroup *)neighborGroup;
-(void)setUarfcn:(int)arg1 ;
-(void)setTac:(int)arg1 ;
-(void)setBandInfo:(int)arg1 ;
-(void)setHasUarfcn:(BOOL)arg1 ;
-(void)setHasBandInfo:(BOOL)arg1 ;
-(BOOL)hasBandInfo;
-(void)setCellLatitude:(double)arg1 ;
-(void)setHasCellLatitude:(BOOL)arg1 ;
-(BOOL)hasCellLatitude;
-(void)setCellLongitude:(double)arg1 ;
-(void)setHasCellLongitude:(BOOL)arg1 ;
-(BOOL)hasCellLongitude;
-(int)tac;
-(int)bandInfo;
-(double)cellLatitude;
-(double)cellLongitude;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(CRLocation *)location;
-(id)dictionaryRepresentation;
-(void)setLocation:(CRLocation *)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(NSString *)appBundleId;
-(void)setAppBundleId:(NSString *)arg1 ;
-(id)neighborAtIndex:(unsigned long long)arg1 ;
-(void)addNeighbor:(id)arg1 ;
-(void)setPid:(int)arg1 ;
-(void)setHasPid:(BOOL)arg1 ;
-(BOOL)hasPid;
-(int)pid;
-(void)setRssi:(int)arg1 ;
-(void)setHasRssi:(BOOL)arg1 ;
-(BOOL)hasRssi;
-(int)rssi;
-(NSString *)operatorName;
-(void)setOperatorName:(NSString *)arg1 ;
@end

