/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:19 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface CRWifiLocation : PBCodable <NSCopying> {

	double _latitude;
	double _longitude;
	double _timestamp;
	float _altitude;
	float _horizontalAccuracy;
	int _motionContext;
	float _verticalAccuracy;
	SCD_Struct_AL4 _has;

}

@property (assign,nonatomic) double timestamp;                      //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) double latitude;                       //@synthesize latitude=_latitude - In the implementation block
@property (assign,nonatomic) double longitude;                      //@synthesize longitude=_longitude - In the implementation block
@property (assign,nonatomic) float horizontalAccuracy;              //@synthesize horizontalAccuracy=_horizontalAccuracy - In the implementation block
@property (assign,nonatomic) BOOL hasVerticalAccuracy; 
@property (assign,nonatomic) float verticalAccuracy;                //@synthesize verticalAccuracy=_verticalAccuracy - In the implementation block
@property (assign,nonatomic) BOOL hasAltitude; 
@property (assign,nonatomic) float altitude;                        //@synthesize altitude=_altitude - In the implementation block
@property (assign,nonatomic) BOOL hasMotionContext; 
@property (assign,nonatomic) int motionContext;                     //@synthesize motionContext=_motionContext - In the implementation block
-(BOOL)hasMotionContext;
-(void)setMotionContext:(int)arg1 ;
-(void)setHasMotionContext:(BOOL)arg1 ;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(double)timestamp;
-(void)setTimestamp:(double)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHorizontalAccuracy:(float)arg1 ;
-(BOOL)hasAltitude;
-(float)altitude;
-(void)setVerticalAccuracy:(float)arg1 ;
-(void)setHasVerticalAccuracy:(BOOL)arg1 ;
-(BOOL)hasVerticalAccuracy;
-(void)setAltitude:(float)arg1 ;
-(void)setHasAltitude:(BOOL)arg1 ;
-(int)motionContext;
-(void)setLatitude:(double)arg1 ;
-(void)setLongitude:(double)arg1 ;
-(float)verticalAccuracy;
-(float)horizontalAccuracy;
-(double)latitude;
-(double)longitude;
@end

