#import <locationd/CMMotionUtils.h>
#import <locationd/CLStreamedLocationProviderAdapter.h>
#import <locationd/ALMotionState.h>
#import <locationd/ALCMMotionContextMotionState.h>
#import <locationd/ALCLStrideCalEntry.h>
#import <locationd/ALCLStepCountEntry.h>
#import <locationd/ALCLSedentaryAlarmData.h>
#import <locationd/ALCLNatalieFeatures.h>
#import <locationd/ALCLBodyMetrics.h>
#import <locationd/ALCLMotionActivity.h>
#import <locationd/ALActivityOverrideMsg.h>
#import <locationd/ALActivityLog.h>
#import <locationd/CLActivityLoggerAdapter.h>
#import <locationd/CalibrationTrack.h>
#import <locationd/CalTrackFinder.h>
#import <locationd/CLSedentaryTimerNotifierAdapter.h>
#import <locationd/TRANSITPbTransitTile.h>
#import <locationd/CLMescalSigner.h>
#import <locationd/CLTimeManagerAdapter.h>
#import <locationd/CLTelephonyServiceAdapter.h>
#import <locationd/CRPressureCollectionRequest.h>
#import <locationd/ALCLStrideCalEntryDeprecated.h>
#import <locationd/CLWifiServiceAdapter.h>
#import <locationd/CLHarvestAppRealtimePolygon.h>
#import <locationd/CLLocationStreamingMessage.h>
#import <locationd/CLLocationStreamingConnectionManager.h>
#import <locationd/CMStrideCalibrationData.h>
#import <locationd/CMStrideCalibrationBins.h>
#import <locationd/CLHarvestAppRealtimeAvailabilityTile.h>
#import <locationd/ALCLRowingModel.h>
#import <locationd/TRANSITPbRegionPreloadTile.h>
#import <locationd/CLMotionStateAdapter.h>
#import <locationd/CLCarrierSettingsAdapter.h>
#import <locationd/CLDaemonStatusInternal.h>
#import <locationd/CLDaemonStatusAdapter.h>
#import <locationd/CLAccessoryLocationProviderAdapter.h>
#import <locationd/CLAccessoryObserver.h>
#import <locationd/CLAccessoryObserverHelper.h>
#import <locationd/CLNmeaLocationProviderAdapter.h>
#import <locationd/CLSkyhookLocationProviderAdapter.h>
#import <locationd/CLLocationControllerAdapter.h>
#import <locationd/CLNetworkLocationProviderAdapter.h>
#import <locationd/CLAuthSerializer.h>
#import <locationd/CMSedentaryTimerData.h>
#import <locationd/CLPressureCalibrationDatabaseAdapter.h>
#import <locationd/BatchData.h>
#import <locationd/ALSLocationDelegate.h>
#import <locationd/CLDaemonClientAdapter.h>
#import <locationd/CLWifiLocationProviderAdapter.h>
#import <locationd/TRANSITPbMacModePair.h>
#import <locationd/CLFilteredLocationControllerAdapter.h>
#import <locationd/CLTimeZoneManagerAdapter.h>
#import <locationd/CRPassLocation.h>
#import <locationd/CLCapabilityMonitor.h>
#import <locationd/CLOperatorSettingsAdapter.h>
#import <locationd/CRCellTowerLocation.h>
#import <locationd/CRCellWifiCollectionRequest.h>
#import <locationd/CRCellWifiCollectionResponse.h>
#import <locationd/CLLocationStreamer.h>
#import <locationd/CRLocation.h>
#import <locationd/ALCLElevation.h>
#import <locationd/CRLocationCollectionRequest.h>
#import <locationd/CRLocationCollectionResponse.h>
#import <locationd/CRMeta.h>
#import <locationd/CRWifiAPLocation.h>
#import <locationd/CLCachedLocationControllerAdapter.h>
#import <locationd/ALCLIDSStatus.h>
#import <locationd/CRCellWifiCollectionDelegate.h>
#import <locationd/CRWtwCollectionDelegate.h>
#import <locationd/CRLocationCollectionDelegate.h>
#import <locationd/CRAppCollectionDelegate.h>
#import <locationd/CRPassCollectionDelegate.h>
#import <locationd/CRIndoorCollectionDelegate.h>
#import <locationd/CRPressureCollectionDelegate.h>
#import <locationd/ALCMCoarseElevation.h>
#import <locationd/CLCandy.h>
#import <locationd/CLFenceManagerAdapter.h>
#import <locationd/CLCompanionNotifierAdapter.h>
#import <locationd/CLStarkManager.h>
#import <locationd/CLClientManagerAdapter.h>
#import <locationd/CLGpsControllerAdapter.h>
#import <locationd/CLPBRequestIndexGenerator.h>
#import <locationd/CLStepDistanceEstimator.h>
#import <locationd/CLSignalEnvironmentProviderAdapter.h>
#import <locationd/CLQmiDmsManagerAdapter.h>
#import <locationd/CLQmiPdsManagerAdapter.h>
#import <locationd/CRCdmaCellTowerLocation.h>
#import <locationd/CLPersistentTimerInternal.h>
#import <locationd/CLMotionStateMediatorAdapter.h>
#import <locationd/CLNatalimetryNotifierAdapter.h>
#import <locationd/CMLogItemInternal.h>
#import <locationd/CMLogItem.h>
#import <locationd/CLSimulatedLocationProviderAdapter.h>
#import <locationd/CLOdometerNotifierAdapter.h>
#import <locationd/CRCellNeighborsGroup.h>
#import <locationd/CLVehicleConnectionNotifierAdapter.h>
#import <locationd/CLClientManagerUsageSyncMessage.h>
#import <locationd/CLClientManagerUsageSyncMessageError.h>
#import <locationd/CLUsageSyncManager.h>
#import <locationd/ALCMFitnessTracking.h>
#import <locationd/CLJacksonEstimateNotifierAdapter.h>
#import <locationd/CLGyroCalibrationDatabaseLocalBaseAdapter.h>
#import <locationd/CLCompassDaemonClientNotifierAdapter.h>
#import <locationd/CRWifiLocation.h>
#import <locationd/CMMotionActivity.h>
#import <locationd/CLCompassDatabaseDaemonAdapter.h>
#import <locationd/CLSensorRecorderAccelMeta.h>
#import <locationd/CLSensorRecorderAccelMetaRequestById.h>
#import <locationd/CLSensorRecorderAccelMetaRequestByDateRange.h>
#import <locationd/CLSensorRecorderAccelDataRequestById.h>
#import <locationd/CLSensorRecorderAccelRecordFor.h>
#import <locationd/CLATCSDispatchWrapperAdapter.h>
#import <locationd/CLSimulationControllerAdapter.h>
#import <locationd/CLCompanionTransport.h>
#import <locationd/CLSignificantChangeManagerAdapter.h>
#import <locationd/CLApplicationLifecycleManagerAdapter.h>
#import <locationd/CLPolygonSimplifier.h>
#import <locationd/ALSScdmaCellTower.h>
#import <locationd/CLSignificantVisitManager.h>
#import <locationd/CLBluetoothServiceAdapter.h>
#import <locationd/CLGeomagneticModelProviderDaemonAdapter.h>
#import <locationd/ALCLOdometer.h>
#import <locationd/CLFenceMonitorAdapter.h>
#import <locationd/ALCLNatalieDataDeprecated.h>
#import <locationd/CLHarvestAppRealtimeHarvestRegion.h>
#import <locationd/CRPassCollectionResponse.h>
#import <locationd/ALCLSessionCatherine.h>
#import <locationd/CLUnifiedCellLocationProviderAdapter.h>
#import <locationd/CMActivity.h>
#import <locationd/ALCLSedentaryAlarmDataDeprecated.h>
#import <locationd/CLSensorRecorderNotifierAdapter.h>
#import <locationd/CLFitnessTrackingNotifierAdapter.h>
#import <locationd/TRANSITPbRegionPreloadMarket.h>
#import <locationd/CMStrideCalibrator.h>
#import <locationd/ALCLJacksonData.h>
#import <locationd/CLDataProtectionManagerAdapter.h>
#import <locationd/CLStatusBarIconManagerAdapter.h>
#import <locationd/CMOdometerData.h>
#import <locationd/CLSensorCalibrationControllerAdapter.h>
#import <locationd/ALSNearbyRequest.h>
#import <locationd/CLALSRequester.h>
#import <locationd/ALSLocationRequest.h>
#import <locationd/ALSCdmaCellTower.h>
#import <locationd/ALSCellTower.h>
#import <locationd/ALSLteCellTower.h>
#import <locationd/ALSWirelessAP.h>
#import <locationd/CRLteCellTowerLocation.h>
#import <locationd/TRANSITPbLocationFingerprintV1.h>
#import <locationd/ALSNearbyResponse.h>
#import <locationd/ALSCdmaEvdoTower.h>
#import <locationd/ALSLocationResponse.h>
#import <locationd/CMOnBodyStatus.h>
#import <locationd/ALSLocation.h>
#import <locationd/CLTileSyncSyChange.h>
#import <locationd/CLTileSyncSySerializer.h>
#import <locationd/CLTileSyncDelegate.h>
#import <locationd/CLAutopauseProviderAdapter.h>
#import <locationd/CLTilesManagerAdapter.h>
#import <locationd/TRANSITPbLocationFingerprint.h>
#import <locationd/CMCatherineData.h>
#import <locationd/CLBackgroundTaskAgent.h>
#import <locationd/CLBTAAdapter.h>
#import <locationd/CLOdometerAlarm.h>
#import <locationd/CLOdometerAlarmManager.h>
#import <locationd/CRPressureCollectionResponse.h>
#import <locationd/CLRoutineMonitor.h>
#import <locationd/CLCustomAuthPBRequester.h>
#import <locationd/CLPCPBRequester.h>
#import <locationd/CLURLConnection.h>
#import <locationd/CLURLConnectionSession.h>
#import <locationd/CMPedometerData.h>
#import <locationd/CLMapDataSourceBase.h>
#import <locationd/CLMapDataSource.h>
#import <locationd/CLMapDataCacheHint.h>
#import <locationd/CLBuildingDataSource.h>
#import <locationd/CLMotionSyncStoreAdapter.h>
#import <locationd/CRWifiScanWifiLocation.h>
#import <locationd/CRIndoorCollectionRequest.h>
#import <locationd/ALCLStairClimbingModel.h>
#import <locationd/CRIndoorWifiScan.h>
#import <locationd/CRWtwCollectionResponse.h>
#import <locationd/CLAppMonitorAdapter.h>
#import <locationd/ALCLAllDayHeartRate.h>
#import <locationd/CRAppCollectionRequest.h>
#import <locationd/CRAppCollectionResponse.h>
#import <locationd/CRAppLocation.h>
#import <locationd/CLPushServiceState.h>
#import <locationd/TRANSITPbLocationFingerprintsV1.h>
#import <locationd/CLPipelineXPCBounce.h>
#import <locationd/CLPipelineLocationProviderAdapter.h>
#import <locationd/CRLteCellNeighbor.h>
#import <locationd/CRCdmaCellNeighbor.h>
#import <locationd/CRCellNeighbor.h>
#import <locationd/CLDeviceMotionProperties.h>
#import <locationd/CMNatalieData.h>
#import <locationd/CRIndoorCollectionResponse.h>
#import <locationd/TRANSITPbRegionPreloadManifest.h>
#import <locationd/CLSuggestedActionManagerAppRecommendationResult.h>
#import <locationd/CLSuggestedActionManager.h>
#import <locationd/CLMapDataFeatureBase.h>
#import <locationd/CLMapDataBuildingFeature.h>
#import <locationd/CLMapDataMultiPointFeature.h>
#import <locationd/CLBundleLocationProviderContext.h>
#import <locationd/CLTilesManagerServerAppRecommendationResult.h>
#import <locationd/CLTilesManagerServerAppRecommendationRequest.h>
#import <locationd/CLCompanionSyncAuthObject.h>
#import <locationd/CRWtwCollectionRequest.h>
#import <locationd/CLWPZone.h>
#import <locationd/CLWPBridge.h>
#import <locationd/CLPeripheralManagerDelegate.h>
#import <locationd/CLBTLEFenceManagerAdapter.h>
#import <locationd/CLCatherineNotifierAdapter.h>
#import <locationd/CLGpsAssistantAdapter.h>
#import <locationd/CLDispatchTimerScheduler.h>
#import <locationd/CLDispatchSilo.h>
#import <locationd/CLIntersiloInterfaceSelectorInfo.h>
#import <locationd/CLIntersiloInterface.h>
#import <locationd/CLIntersiloProxy.h>
#import <locationd/CLIntersiloService.h>
#import <locationd/CLServiceVendorHeartbeatRecord.h>
#import <locationd/_Locationd.h>
#import <locationd/_CLMainService.h>
#import <locationd/CLServiceVendor.h>
#import <locationd/CLSilo.h>
#import <locationd/CLAuthSyncManager.h>
#import <locationd/CLTimer.h>
#import <locationd/CLNotifierClientAdapter.h>
#import <locationd/CLNotifierData.h>
#import <locationd/CRSCdmaCellTowerLocation.h>
#import <locationd/CLNotifierServiceAdapter.h>
#import <locationd/CLBTLEBeaconProviderAdapter.h>
#import <locationd/CRPressure.h>
#import <locationd/TRANSITPbLocationFingerprints.h>
#import <locationd/CMActivityAlarm.h>
#import <locationd/CLDarwinNotifierAdapter.h>
#import <locationd/CLRunningAggregatorAWD.h>
#import <locationd/CLLocationHarvesterAdapter.h>
#import <locationd/CRPassCollectionRequest.h>
#import <locationd/CMCalorieUserInfo.h>
#import <locationd/CLBeaconFenceAuthorizationManagerAdapter.h>
#import <locationd/CLEmergencyControllerAdapter.h>
#import <locationd/CLBTLERangeManagerAdapter.h>
#import <locationd/CLTurnStateAdapter.h>
#import <locationd/CLClientAuthorizationCache.h>
#import <locationd/ALCMCalorieData.h>
#import <locationd/CLOnBodyNotifierAdapter.h>
#import <locationd/CLStepCountNotifierAdapter.h>
#import <locationd/CLIndoorSettings.h>
#import <locationd/CLIndoorState.h>
#import <locationd/CLLatLonPolygon.h>
#import <locationd/CLAvailabilityTile.h>
#import <locationd/CLVenueBounds.h>
#import <locationd/CLDaemonTracer.h>
