/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:20 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray;

@interface TRANSITPbRegionPreloadMarket : PBCodable <NSCopying> {

	double _northWestLatitude;
	double _northWestLongitude;
	double _southEastLatitude;
	double _southEastLongitude;
	NSMutableArray* _tiles;
	SCD_Struct_AL3 _has;

}

@property (assign,nonatomic) BOOL hasNorthWestLatitude; 
@property (assign,nonatomic) double northWestLatitude;                //@synthesize northWestLatitude=_northWestLatitude - In the implementation block
@property (assign,nonatomic) BOOL hasNorthWestLongitude; 
@property (assign,nonatomic) double northWestLongitude;               //@synthesize northWestLongitude=_northWestLongitude - In the implementation block
@property (assign,nonatomic) BOOL hasSouthEastLatitude; 
@property (assign,nonatomic) double southEastLatitude;                //@synthesize southEastLatitude=_southEastLatitude - In the implementation block
@property (assign,nonatomic) BOOL hasSouthEastLongitude; 
@property (assign,nonatomic) double southEastLongitude;               //@synthesize southEastLongitude=_southEastLongitude - In the implementation block
@property (nonatomic,retain) NSMutableArray * tiles;                  //@synthesize tiles=_tiles - In the implementation block
-(void)addTiles:(id)arg1 ;
-(unsigned long long)tilesCount;
-(void)clearTiles;
-(id)tilesAtIndex:(unsigned long long)arg1 ;
-(void)setNorthWestLatitude:(double)arg1 ;
-(void)setHasNorthWestLatitude:(BOOL)arg1 ;
-(BOOL)hasNorthWestLatitude;
-(void)setNorthWestLongitude:(double)arg1 ;
-(void)setHasNorthWestLongitude:(BOOL)arg1 ;
-(BOOL)hasNorthWestLongitude;
-(void)setSouthEastLatitude:(double)arg1 ;
-(void)setHasSouthEastLatitude:(BOOL)arg1 ;
-(BOOL)hasSouthEastLatitude;
-(void)setSouthEastLongitude:(double)arg1 ;
-(void)setHasSouthEastLongitude:(BOOL)arg1 ;
-(BOOL)hasSouthEastLongitude;
-(double)northWestLatitude;
-(double)northWestLongitude;
-(double)southEastLatitude;
-(double)southEastLongitude;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setTiles:(NSMutableArray *)arg1 ;
-(NSMutableArray *)tiles;
@end

