/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:27 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/pipelined
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pipelined/pipelined-Structs.h>
@interface DarwinDeviceInfo : NSObject
+(id)currentDevice;
-(vector<int, std::__1::allocator<int> >*)splitSystemVersion;
-(int)hwModel;
-(int)osMajor;
-(id)machine;
-(Info)ws_info;
-(id)name;
-(id)systemVersion;
-(id)systemName;
-(int)manufacturer;
-(int)cellType;
-(int)family;
@end

