/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:27 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/pipelined
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pipelined/pipelined-Structs.h>
@class NSOperationQueue, CMAltimeter;

@interface IOSAltimeter : NSObject {

	NSOperationQueue* _queue;
	CMAltimeter* _altimeter;
	optional<AltimeterSensor>* _sensor;

}
-(BOOL)sensorPresent;
-(Sensor*)getSensor;
-(id)init;
-(void)stop;
-(void)start;
-(id)initWithOperationQueue:(id)arg1 ;
@end

