/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:27 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/pipelined
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, WiFiUtilDelegate;
#import <pipelined/pipelined-Structs.h>
@class NSObject, NSArray;

@interface WiFiUtil : NSObject {

	NSObject*<OS_dispatch_queue> _q;
	WiFiManagerClientRef _wifiClient;
	NSArray* _wifiDevices;
	id<WiFiUtilDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<WiFiUtilDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)onQueueInvalidate;
-(void)onQueueReEnumerateDevices;
-(void)onQueueDeregisterDevices;
-(void)onQueueDeregisterManager;
-(void)onQueueRegisterDevices;
-(void)onQueueRegisterManager;
-(void)deviceAttached:(WiFiDeviceClientRef)arg1 ;
-(void)notifyDevicePowerChanged;
-(void)setDelegate:(id<WiFiUtilDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(id<WiFiUtilDelegate>)delegate;
-(void)invalidate;
-(BOOL)isDisabled;
@end

