/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:08 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/backboardd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <backboardd/backboardd-Structs.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class BKSDisplayRenderOverlayDescriptor, NSData;

@interface _BKDisplayRenderOverlayPersistenceData : NSObject <NSSecureCoding> {

	BKSDisplayRenderOverlayDescriptor* _descriptor;
	CGImageRef _image;
	NSData* _imageData;

}

@property (nonatomic,retain) BKSDisplayRenderOverlayDescriptor * descriptor;              //@synthesize descriptor=_descriptor - In the implementation block
@property (assign,nonatomic) CGImageRef image;                                            //@synthesize image=_image - In the implementation block
+(id)classesRequiredToDecode;
+(BOOL)supportsSecureCoding;
-(id)_initWithDescriptor:(id)arg1 imageData:(id)arg2 ;
-(void)setImage:(CGImageRef)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(CGImageRef)image;
-(void)setDescriptor:(BKSDisplayRenderOverlayDescriptor *)arg1 ;
-(BKSDisplayRenderOverlayDescriptor *)descriptor;
@end

