/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:08 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/backboardd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface BKDisplayRenderOverlayPersistenceCoordinator : NSObject {

	NSString* _rootPersistencePath;

}
+(id)sharedInstance;
-(id)rebuildPersistentOverlays;
-(BOOL)saveOverlay:(id)arg1 ;
-(BOOL)destroyOverlay:(id)arg1 ;
-(id)_fileNameForOverlay:(id)arg1 ;
-(id)_filePathForOverlay:(id)arg1 ;
-(void)dealloc;
-(id)init;
@end

