/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:08 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/backboardd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <backboardd/backboardd-Structs.h>
#import <backboardd/BKDigitizerEventSchedulerBase.h>

@class CADisplayLink, NSThread;

@interface BKDigitizerEventSchedulerWithDisplayLink : BKDigitizerEventSchedulerBase {

	CADisplayLink* _displayLink;
	NSThread* _thread;

}

@property (nonatomic,readonly) CADisplayLink * displayLink;              //@synthesize displayLink=_displayLink - In the implementation block
+(Class)displayLinkClass;
-(void)_thread_displayLinkFired:(id)arg1 ;
-(void)_thread_scheduleEventWithBlock:(/*^block*/id)arg1 event:(IOHIDEventRef)arg2 clientTaskPort:(unsigned)arg3 ;
-(void)_thread_startRunLoop;
-(void)scheduleEvent:(IOHIDEventRef)arg1 fromDigitizer:(id)arg2 toClient:(unsigned)arg3 ;
-(void)dealloc;
-(id)init;
-(CADisplayLink *)displayLink;
-(void)performAsync:(/*^block*/id)arg1 ;
-(void)_performBlock:(/*^block*/id)arg1 ;
-(void)performSync:(/*^block*/id)arg1 ;
@end

