/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:08 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/backboardd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <backboardd/backboardd-Structs.h>
#import <backboardd/BKEntitlementCache.h>

@protocol OS_dispatch_queue;
@class NSObject, BKSystemApplication, NSMutableDictionary, NSString;

@interface BKSystemAppEntitlementCache : NSObject <BKEntitlementCache> {

	NSObject*<OS_dispatch_queue> _queue;
	BKSystemApplication* _systemApp;
	NSMutableDictionary* _cachedEntitlementResults;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)shouldCacheResultForToken:(SCD_Struct_BK5*)arg1 ;
-(BOOL)hasCacheResultForToken:(SCD_Struct_BK5*)arg1 andEntitlement:(id)arg2 result:(BOOL*)arg3 ;
-(void)cacheResult:(BOOL)arg1 forToken:(SCD_Struct_BK5*)arg2 andEntitlement:(id)arg3 ;
-(void)_systemAppChanged:(id)arg1 ;
-(void)lock_setSystemApp:(id)arg1 ;
-(void)dealloc;
-(id)init;
@end

