/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:20:25 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/ServerDocuments.app/Frameworks/ServerDocsClient.framework/ServerDocsClient
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class SVViewOptionsHeaderView, UIScrollView;


@protocol SVFilesChildViewController <NSObject>
@property (nonatomic,readonly) SVViewOptionsHeaderView * viewOptionsHeaderView; 
@property (nonatomic,readonly) UIScrollView * scrollView; 
@required
-(SVViewOptionsHeaderView *)viewOptionsHeaderView;
-(id)showDownloadProgressForItem:(id)arg1;
-(void)cancelDownloadProgressForItem:(id)arg1;
-(void)scrollItemToVisible:(id)arg1 completionHandler:(/*^block*/id)arg2;
-(void)flashToEmphasizeItem:(id)arg1 completionHandler:(/*^block*/id)arg2;
-(UIScrollView *)scrollView;

@end

