/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:08 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/assertiond
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assertiond/BSXPCConnectionListenerHandler.h>

@protocol OS_dispatch_queue;
@class NSObject, NSMutableSet, NSMapTable, NSString;

@interface BKProcessAssertionServer : NSObject <BSXPCConnectionListenerHandler> {

	NSObject*<OS_dispatch_queue> _queue;
	NSMutableSet* _clients;
	NSMapTable* _clientsToAssertions;
	NSMapTable* _identifiersToAssertions;
	NSMapTable* _viewServicesMap;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
-(void)applicationStateChanged:(id)arg1 ;
-(void)_queue_addClient:(id)arg1 forService:(id)arg2 ;
-(void)_queue_resumeViewServiceAssertionsForProcess:(id)arg1 ;
-(void)_queue_suspendViewServiceAssertionsForProcess:(id)arg1 ;
-(id)_queue_wrapperForPID:(int)arg1 ;
-(void)_queue_invalidateAssertion:(id)arg1 client:(id)arg2 informClient:(BOOL)arg3 ;
-(void)_queue_removeClient:(id)arg1 ;
-(void)_queue_handleMessage:(id)arg1 forClient:(id)arg2 ;
-(id)_queue_wrapperForConnection:(id)arg1 ;
-(void)_queue_removeAssertionFromViewServicesList:(id)arg1 ;
-(void)_queue_createAssertion:(id)arg1 ;
-(void)_queue_updateAssertion:(id)arg1 ;
-(void)_queue_destroyAssertion:(id)arg1 client:(id)arg2 ;
-(void)_queue_backgroundTimeRemaining:(id)arg1 client:(id)arg2 ;
-(id)_queue_extractEventFromMessage:(id)arg1 ofType:(Class)arg2 ;
-(BOOL)_queue_assertionAllowedForProcess:(id)arg1 withConnection:(id)arg2 fromPID:(int)arg3 reason:(unsigned)arg4 outServiceHost:(id*)arg5 ;
-(void)_queue_associateAssertion:(id)arg1 toHostedListForProcess:(id)arg2 ;
-(void)dealloc;
-(id)init;
-(NSString *)description;
-(void)run;
-(void)processDidExit:(id)arg1 ;
-(void)handleIncomingConnection:(id)arg1 forService:(id)arg2 ;
@end

