/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:14:20 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDHealthKitIngestionLatencyEvent : PBCodable <NSCopying> {

	long long _endDate;
	long long _maxDelayUs;
	long long _meanDelayUs;
	long long _minDelayUs;
	long long _startDate;
	long long _stdDelayUs;
	unsigned long long _timestamp;
	long long _typeIdentifier;
	BOOL _inSession;
	SCD_Struct_AW11 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasTypeIdentifier; 
@property (assign,nonatomic) long long typeIdentifier;                  //@synthesize typeIdentifier=_typeIdentifier - In the implementation block
@property (assign,nonatomic) BOOL hasInSession; 
@property (assign,nonatomic) BOOL inSession;                            //@synthesize inSession=_inSession - In the implementation block
@property (assign,nonatomic) BOOL hasMinDelayUs; 
@property (assign,nonatomic) long long minDelayUs;                      //@synthesize minDelayUs=_minDelayUs - In the implementation block
@property (assign,nonatomic) BOOL hasMaxDelayUs; 
@property (assign,nonatomic) long long maxDelayUs;                      //@synthesize maxDelayUs=_maxDelayUs - In the implementation block
@property (assign,nonatomic) BOOL hasMeanDelayUs; 
@property (assign,nonatomic) long long meanDelayUs;                     //@synthesize meanDelayUs=_meanDelayUs - In the implementation block
@property (assign,nonatomic) BOOL hasStdDelayUs; 
@property (assign,nonatomic) long long stdDelayUs;                      //@synthesize stdDelayUs=_stdDelayUs - In the implementation block
@property (assign,nonatomic) BOOL hasStartDate; 
@property (assign,nonatomic) long long startDate;                       //@synthesize startDate=_startDate - In the implementation block
@property (assign,nonatomic) BOOL hasEndDate; 
@property (assign,nonatomic) long long endDate;                         //@synthesize endDate=_endDate - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(long long)typeIdentifier;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasTimestamp;
-(void)setHasStartDate:(BOOL)arg1 ;
-(BOOL)hasStartDate;
-(void)setHasEndDate:(BOOL)arg1 ;
-(BOOL)hasEndDate;
-(void)setTypeIdentifier:(long long)arg1 ;
-(void)setHasTypeIdentifier:(BOOL)arg1 ;
-(BOOL)hasTypeIdentifier;
-(void)setInSession:(BOOL)arg1 ;
-(void)setHasInSession:(BOOL)arg1 ;
-(BOOL)hasInSession;
-(void)setMinDelayUs:(long long)arg1 ;
-(void)setHasMinDelayUs:(BOOL)arg1 ;
-(BOOL)hasMinDelayUs;
-(void)setMaxDelayUs:(long long)arg1 ;
-(void)setHasMaxDelayUs:(BOOL)arg1 ;
-(BOOL)hasMaxDelayUs;
-(void)setMeanDelayUs:(long long)arg1 ;
-(void)setHasMeanDelayUs:(BOOL)arg1 ;
-(BOOL)hasMeanDelayUs;
-(void)setStdDelayUs:(long long)arg1 ;
-(void)setHasStdDelayUs:(BOOL)arg1 ;
-(BOOL)hasStdDelayUs;
-(BOOL)inSession;
-(long long)minDelayUs;
-(long long)maxDelayUs;
-(long long)meanDelayUs;
-(long long)stdDelayUs;
-(void)setEndDate:(long long)arg1 ;
-(void)setStartDate:(long long)arg1 ;
-(long long)startDate;
-(long long)endDate;
@end

