/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:10 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/fmfd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <fmfd/FMFAccountManager.h>

@class ACAccountStore, FMFAccount;

@interface FMFAccountManageriOS : FMFAccountManager {

	BOOL _isRenewingAccountCredentials;
	ACAccountStore* _accountStore;
	FMFAccount* _iOSAccount;

}

@property (nonatomic,retain) ACAccountStore * accountStore;                  //@synthesize accountStore=_accountStore - In the implementation block
@property (nonatomic,retain) FMFAccount * iOSAccount;                        //@synthesize iOSAccount=_iOSAccount - In the implementation block
@property (assign,nonatomic) BOOL isRenewingAccountCredentials;              //@synthesize isRenewingAccountCredentials=_isRenewingAccountCredentials - In the implementation block
-(BOOL)hasFirstUnlocked;
-(void)renewAccountCredentials:(BOOL)arg1 ;
-(BOOL)hasCredentials;
-(void)updateAccountInfo;
-(void)setIsRenewingAccountCredentials:(BOOL)arg1 ;
-(FMFAccount *)iOSAccount;
-(void)setIOSAccount:(FMFAccount *)arg1 ;
-(void)updateAccountWithFMFTokens;
-(BOOL)isRenewingAccountCredentials;
-(id)fmfAccountToken;
-(id)init;
-(void)setAccountStore:(ACAccountStore *)arg1 ;
-(ACAccountStore *)accountStore;
-(id)account;
@end

