/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:10 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/fmfd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <fmfd/FMFBaseCmd.h>

@class NSMutableDictionary, NSDictionary;

@interface FMFCheckReachabilityStatus : FMFBaseCmd {

	NSMutableDictionary* _statusMapFromServer;
	NSDictionary* _statusMap;

}

@property (nonatomic,retain) NSMutableDictionary * statusMapFromServer;              //@synthesize statusMapFromServer=_statusMapFromServer - In the implementation block
@property (nonatomic,retain) NSDictionary * statusMap;                               //@synthesize statusMap=_statusMap - In the implementation block
-(id)pathSuffix;
-(void)processCommandResponse:(id)arg1 ;
-(void)setStatusMap:(NSDictionary *)arg1 ;
-(void)setStatusMapFromServer:(NSMutableDictionary *)arg1 ;
-(NSDictionary *)statusMap;
-(NSMutableDictionary *)statusMapFromServer;
-(id)initWithClientSession:(id)arg1 idsClientStatusMap:(id)arg2 ;
-(id)jsonBodyDictionary;
@end

