/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:10 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/fmfd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, NSDictionary, NSSet, NSString, FMFDevice, NSMutableDictionary, NSTimer, FMFDStoreController;

@interface FMFDataManager : NSObject {

	BOOL _followersInfoReceived;
	BOOL _followersFullyInited;
	BOOL _followingInfoReceived;
	BOOL _followingFullyInited;
	BOOL _storedConfigLoaded;
	NSArray* _cachedTapMessages;
	NSDictionary* __configFromServer;
	NSSet* _pendingOfferHandles;
	NSString* _modelVersion;
	NSSet* __devices;
	FMFDevice* __meDevice;
	NSDictionary* __features;
	NSDictionary* __preferences;
	NSDictionary* __myInfo;
	NSDictionary* __followingHandleMapWithIdentifier;
	NSDictionary* __followingHandleMapWithServerId;
	NSDictionary* __followerHandleMapWithIdentifier;
	NSDictionary* __followerHandleMapWithServerId;
	NSSet* __followingHandlesInternal;
	NSSet* __followerHandlesInternal;
	NSSet* __futureFollowingRequestsInternal;
	NSSet* __futureFollowerRequestsInternal;
	NSDictionary* __futureFollowerRequestMapWithIdentifier;
	NSMutableDictionary* __locationDictionary;
	NSDictionary* __favoritesData;
	NSMutableDictionary* _changesToBeNotified;
	NSTimer* _sanitizeLocationsCacheTimer;
	FMFDStoreController* _storeController;
	NSString* _lastLoggedInPrsIdInternal;

}

@property (nonatomic,readonly) NSSet * followingHandles; 
@property (nonatomic,readonly) NSSet * followerHandles; 
@property (nonatomic,retain) NSSet * pendingOfferHandles;                                         //@synthesize pendingOfferHandles=_pendingOfferHandles - In the implementation block
@property (nonatomic,retain) NSString * modelVersion;                                             //@synthesize modelVersion=_modelVersion - In the implementation block
@property (nonatomic,retain) NSArray * cachedTapMessages;                                         //@synthesize cachedTapMessages=_cachedTapMessages - In the implementation block
@property (nonatomic,retain) NSDictionary * _configFromServer;                                    //@synthesize _configFromServer=__configFromServer - In the implementation block
@property (nonatomic,retain) NSSet * _devices;                                                    //@synthesize _devices=__devices - In the implementation block
@property (nonatomic,retain) FMFDevice * _meDevice;                                               //@synthesize _meDevice=__meDevice - In the implementation block
@property (nonatomic,retain) NSDictionary * _features;                                            //@synthesize _features=__features - In the implementation block
@property (nonatomic,retain) NSDictionary * _preferences;                                         //@synthesize _preferences=__preferences - In the implementation block
@property (nonatomic,retain) NSDictionary * _myInfo;                                              //@synthesize _myInfo=__myInfo - In the implementation block
@property (nonatomic,retain) NSDictionary * _followingHandleMapWithIdentifier;                    //@synthesize _followingHandleMapWithIdentifier=__followingHandleMapWithIdentifier - In the implementation block
@property (nonatomic,retain) NSDictionary * _followingHandleMapWithServerId;                      //@synthesize _followingHandleMapWithServerId=__followingHandleMapWithServerId - In the implementation block
@property (nonatomic,retain) NSDictionary * _followerHandleMapWithIdentifier;                     //@synthesize _followerHandleMapWithIdentifier=__followerHandleMapWithIdentifier - In the implementation block
@property (nonatomic,retain) NSDictionary * _followerHandleMapWithServerId;                       //@synthesize _followerHandleMapWithServerId=__followerHandleMapWithServerId - In the implementation block
@property (nonatomic,retain) NSSet * _followingHandlesInternal;                                   //@synthesize _followingHandlesInternal=__followingHandlesInternal - In the implementation block
@property (nonatomic,retain) NSSet * _followerHandlesInternal;                                    //@synthesize _followerHandlesInternal=__followerHandlesInternal - In the implementation block
@property (nonatomic,retain) NSSet * _futureFollowingRequestsInternal;                            //@synthesize _futureFollowingRequestsInternal=__futureFollowingRequestsInternal - In the implementation block
@property (nonatomic,retain) NSSet * _futureFollowerRequestsInternal;                             //@synthesize _futureFollowerRequestsInternal=__futureFollowerRequestsInternal - In the implementation block
@property (nonatomic,retain) NSDictionary * _futureFollowerRequestMapWithIdentifier;              //@synthesize _futureFollowerRequestMapWithIdentifier=__futureFollowerRequestMapWithIdentifier - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * _locationDictionary;                           //@synthesize _locationDictionary=__locationDictionary - In the implementation block
@property (nonatomic,retain) NSDictionary * _favoritesData;                                       //@synthesize _favoritesData=__favoritesData - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * changesToBeNotified;                           //@synthesize changesToBeNotified=_changesToBeNotified - In the implementation block
@property (nonatomic,retain) NSTimer * sanitizeLocationsCacheTimer;                               //@synthesize sanitizeLocationsCacheTimer=_sanitizeLocationsCacheTimer - In the implementation block
@property (assign,nonatomic) BOOL followersInfoReceived;                                          //@synthesize followersInfoReceived=_followersInfoReceived - In the implementation block
@property (assign,nonatomic) BOOL followersFullyInited;                                           //@synthesize followersFullyInited=_followersFullyInited - In the implementation block
@property (assign,nonatomic) BOOL followingInfoReceived;                                          //@synthesize followingInfoReceived=_followingInfoReceived - In the implementation block
@property (assign,nonatomic) BOOL followingFullyInited;                                           //@synthesize followingFullyInited=_followingFullyInited - In the implementation block
@property (assign,nonatomic) BOOL storedConfigLoaded;                                             //@synthesize storedConfigLoaded=_storedConfigLoaded - In the implementation block
@property (nonatomic,retain) FMFDStoreController * storeController;                               //@synthesize storeController=_storeController - In the implementation block
@property (nonatomic,retain) NSString * lastLoggedInPrsIdInternal;                                //@synthesize lastLoggedInPrsIdInternal=_lastLoggedInPrsIdInternal - In the implementation block
+(id)sharedInstance;
-(void)accountWasRemoved;
-(void)cleanupOldModel;
-(double)lazyInitTimeoutInSec;
-(void)digestCommand:(id)arg1 ;
-(NSSet *)followerHandles;
-(id)followingHandleForServerId:(id)arg1 ;
-(double)locationTTL;
-(NSSet *)pendingOfferHandles;
-(double)upsellTimeoutInSeconds;
-(BOOL)locationHidden;
-(id)deviceSharingLocation;
-(id)followerHandleForIdentifier:(id)arg1 ;
-(id)getHandlesWithPendingOffersSync;
-(id)offerExpireDateForHandle:(id)arg1 withGroupId:(id)arg2 ;
-(id)followingHandleForIdentifier:(id)arg1 ;
-(BOOL)hasPendingOfferToHandle:(id)arg1 withGroupId:(id)arg2 ;
-(id)allLocations;
-(BOOL)blockFMFChannel;
-(BOOL)sendOnlyFMFChannel;
-(id)favorites;
-(NSSet *)followingHandles;
-(double)graceInterval401InSec;
-(id)lastLoggedInPrsId;
-(NSArray *)cachedTapMessages;
-(void)setFollowingHandles:(NSSet *)arg1 ;
-(void)setFollowerHandles:(NSSet *)arg1 ;
-(void)set_configFromServer:(NSDictionary *)arg1 ;
-(void)set_devices:(NSSet *)arg1 ;
-(void)set_meDevice:(FMFDevice *)arg1 ;
-(void)set_features:(NSDictionary *)arg1 ;
-(void)set_preferences:(NSDictionary *)arg1 ;
-(void)set_myInfo:(NSDictionary *)arg1 ;
-(void)set_followingHandleMapWithIdentifier:(NSDictionary *)arg1 ;
-(void)set_followingHandleMapWithServerId:(NSDictionary *)arg1 ;
-(void)set_followerHandleMapWithIdentifier:(NSDictionary *)arg1 ;
-(void)set_followerHandleMapWithServerId:(NSDictionary *)arg1 ;
-(void)set_followingHandlesInternal:(NSSet *)arg1 ;
-(void)set_followerHandlesInternal:(NSSet *)arg1 ;
-(void)set_futureFollowingRequestsInternal:(NSSet *)arg1 ;
-(void)set_futureFollowerRequestsInternal:(NSSet *)arg1 ;
-(void)set_futureFollowerRequestMapWithIdentifier:(NSDictionary *)arg1 ;
-(void)set_locationDictionary:(NSMutableDictionary *)arg1 ;
-(void)set_favoritesData:(NSDictionary *)arg1 ;
-(void)setPendingOfferHandles:(NSSet *)arg1 ;
-(void)setFollowersInfoReceived:(BOOL)arg1 ;
-(void)setFollowingInfoReceived:(BOOL)arg1 ;
-(void)setFollowersFullyInited:(BOOL)arg1 ;
-(void)setFollowingFullyInited:(BOOL)arg1 ;
-(FMFDStoreController *)storeController;
-(void)updateSessionCaches:(id)arg1 forSessions:(id)arg2 pushAllData:(BOOL)arg3 ;
-(void)setStoreController:(FMFDStoreController *)arg1 ;
-(void)updateClientsWithLocallyStoredModelCache;
-(void)sanitizeLocationsCache:(id)arg1 ;
-(void)setSanitizeLocationsCacheTimer:(NSTimer *)arg1 ;
-(NSTimer *)sanitizeLocationsCacheTimer;
-(void)cleanupCaches;
-(FMFDevice *)_meDevice;
-(NSMutableDictionary *)changesToBeNotified;
-(BOOL)storedConfigLoaded;
-(void)setStoredConfigLoaded:(BOOL)arg1 ;
-(void)setChangesToBeNotified:(NSMutableDictionary *)arg1 ;
-(NSSet *)_futureFollowerRequestsInternal;
-(void)deltasFromExisting:(id)arg1 usingLatest:(id)arg2 forKey:(id)arg3 ;
-(void)setFutureFollowerRequests:(id)arg1 ;
-(NSSet *)_futureFollowingRequestsInternal;
-(void)applyFavoritesToHandles;
-(NSDictionary *)_preferences;
-(NSDictionary *)_myInfo;
-(void)determineNewMeDevice;
-(NSMutableDictionary *)_locationDictionary;
-(void)notifyClientOfUpdates:(id)arg1 ;
-(NSDictionary *)_favoritesData;
-(NSDictionary *)_followingHandleMapWithServerId;
-(void)updateInited;
-(BOOL)transcriptDelegateStartEnabled;
-(BOOL)followersFullyInited;
-(BOOL)transcriptDelegateStopEnabled;
-(BOOL)followingFullyInited;
-(BOOL)followersInfoReceived;
-(BOOL)followingInfoReceived;
-(NSDictionary *)_followerHandleMapWithIdentifier;
-(NSSet *)_followingHandlesInternal;
-(NSSet *)_followerHandlesInternal;
-(NSDictionary *)_followingHandleMapWithIdentifier;
-(NSDictionary *)_futureFollowerRequestMapWithIdentifier;
-(NSDictionary *)_followerHandleMapWithServerId;
-(id)futureFollowingRequests;
-(id)futureFollowerRequests;
-(NSDictionary *)_configFromServer;
-(id)tapMessagesFromDefaults;
-(void)setCachedTapMessages:(NSArray *)arg1 ;
-(void)storeTapMessagesToDefaults;
-(void)updateLastLoggedInPrsId:(id)arg1 ;
-(id)maxLocationRefreshTimeout;
-(void)setLocationsFromData:(id)arg1 ;
-(id)locationsForHandles:(id)arg1 ;
-(id)friendshipRequestForIdentifier:(id)arg1 ;
-(id)followerHandleForServerId:(id)arg1 ;
-(void)removeFutureFollowerRequest:(id)arg1 ;
-(BOOL)showAirDropImportAlert;
-(BOOL)showAirDropImportUseFMFAppAlert;
-(BOOL)showAirDropImportViewOniCloudAlert;
-(BOOL)canAddFollower;
-(double)minCallbackInterval;
-(double)heartbeatIntervalInSec;
-(double)userLocateWaitIntervalInMS;
-(double)systemInactivityTimeoutInSec;
-(double)maxWaitTimeForRegisterMS;
-(id)maxTriesToRegisterDevice;
-(double)graceInterval5XXInSec;
-(void)cleanupCachedPendingOfferHandles;
-(BOOL)isThisDeviceRegistered;
-(void)updateTapMessagesCache:(id)arg1 ;
-(void)clearTapMessagesCache;
-(NSDictionary *)_features;
-(NSString *)lastLoggedInPrsIdInternal;
-(void)setLastLoggedInPrsIdInternal:(NSString *)arg1 ;
-(void)dealloc;
-(NSSet *)_devices;
-(NSString *)modelVersion;
-(void)setModelVersion:(NSString *)arg1 ;
-(id)locationForHandle:(id)arg1 ;
-(double)maxLocatingInterval;
-(void)getHandlesSharingLocationsWithMe:(/*^block*/id)arg1 ;
-(void)getHandlesSharingLocationsWithMeWithGroupId:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getHandlesSharingMyLocation:(/*^block*/id)arg1 ;
-(void)getHandlesSharingMyLocationWithGroupId:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getHandlesWithPendingOffers:(/*^block*/id)arg1 ;
-(void)getPendingFriendshipRequestsWithCompletion:(/*^block*/id)arg1 ;
-(id)thisDeviceId;
-(id)allDevices;
-(BOOL)canAddFriend;
@end

