/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:10 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/fmfd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface KeychainUtil : NSObject
+(void)hideKeychainUI;
+(void)removeKeychainItemForService:(id)arg1 withUsername:(id)arg2 ;
+(void)restoreKeychainUI;
+(int)keychainItemForService:(id)arg1 withUsername:(id)arg2 returningItem:(id*)arg3 ;
+(void)setKeychainItemForService:(id)arg1 withUsername:(id)arg2 value:(id)arg3 accessibility:(long long)arg4 ;
@end

