/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:38 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/sbin/WirelessRadioManagerd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WirelessRadioManagerd/WCM_RadioController.h>

@interface WCM_FTController : WCM_RadioController {

	unsigned long long _currentCallTargetBitRate;
	unsigned long long _currentBitRate;

}

@property (assign) unsigned long long currentCallTargetBitRate;              //@synthesize currentCallTargetBitRate=_currentCallTargetBitRate - In the implementation block
@property (assign) unsigned long long currentBitRate;                        //@synthesize currentBitRate=_currentBitRate - In the implementation block
-(void)getFaceTimeCallConfig;
-(BOOL)getFTState;
-(void)setFTRate:(unsigned long long)arg1 ;
-(void)resetFTRate;
-(void)handleFaceTimeCallConfig:(id)arg1 ;
-(void)setCurrentCallTargetBitRate:(unsigned long long)arg1 ;
-(unsigned long long)currentCallTargetBitRate;
-(unsigned long long)currentBitRate;
-(void)setCurrentBitRate:(unsigned long long)arg1 ;
-(void)handleMessage:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(id)description;
@end

