/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:38 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/sbin/WirelessRadioManagerd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <WirelessRadioManagerd/WirelessRadioManagerd-Structs.h>
@class NSObject;

@interface WRM_SCService : NSObject {

	NSObject*<OS_dispatch_queue> mQueue;
	SCDynamicStoreRef mStore;
	BOOL mValidDataLqm;
	int mDataLQM;

}
-(int)getCellularDataLQM;
-(void)setCellularDataLQM:(int)arg1 ;
-(void)registerForCellularDataLQM;
-(void)resetCellularDataLQM;
-(BOOL)isDataLQMValid;
-(void)dealloc;
-(id)init;
@end

