/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:38 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/sbin/WirelessRadioManagerd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, CMMotionActivityManager, CMActivityAlarm;

@interface WRM_MotionController : NSObject {

	NSObject*<OS_dispatch_queue> mAlarmQueue;
	CMMotionActivityManager* mMotionAcitivity;
	int mMotionControllerState;
	int myMobilityState;
	int myPrevMobilityState;
	int mDefaultAlarmDuration;
	CMActivityAlarm* mStaticAlarm;
	CMActivityAlarm* mWalkingAlarm;
	CMActivityAlarm* mRunningAlarm;
	CMActivityAlarm* mDrivingAlarm;
	CMActivityAlarm* mPedestrianAfterStatic;

}
-(void)stopMonitoringAlarms;
-(void)waitForStaticState:(unsigned long long)arg1 ;
-(void)stopPendingAlarms;
-(void)notifyHandoverManager:(int)arg1 ;
-(void)waitForActivityState:(unsigned long long)arg1 :(int)arg2 ;
-(void)waitForWalkingState:(unsigned long long)arg1 ;
-(void)waitForRunningState:(unsigned long long)arg1 ;
-(void)waitForDrivingState:(unsigned long long)arg1 ;
-(void)waitForPedestrianState:(unsigned long long)arg1 ;
-(id)getMotionAlarmQueue;
-(int)getMobilityState;
-(int)getPrevMobilityState;
-(void)updateAlarmMonitoringDuration:(int)arg1 ;
-(void)startMonitoringAlarms;
-(void)stopAllAlarms;
-(void)dealloc;
-(id)init;
@end

