/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:47 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UISearchController.h>
#import <MobileCal/ImmunityFromCustomAdaptationOfPresentedViewControllersAcrossSizeClasses.h>

@class NSString;

@interface AdaptiveSearchController : UISearchController <ImmunityFromCustomAdaptationOfPresentedViewControllersAcrossSizeClasses>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)_shouldForwardViewWillTransitionToSize;
-(BOOL)isImmuneToCustomAdaptation;
@end

