/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:46 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, AnchoredValuePair;

@interface AnchoredValueGenerator : NSObject {

	NSMutableArray* _pairs;
	BOOL _needsSorting;
	AnchoredValuePair* _cachedLastResult;
	int _calculationType;
	int _roundingType;

}

@property (assign,nonatomic) int calculationType;              //@synthesize calculationType=_calculationType - In the implementation block
@property (assign,nonatomic) int roundingType;                 //@synthesize roundingType=_roundingType - In the implementation block
+(void)_testInterpolation;
+(void)_testNearest;
+(void)_testLayoutShiftScale;
+(void)_testValue:(double)arg1 expectedValue:(double)arg2 testName:(id)arg3 ;
+(void)runTests;
-(void)setRoundingType:(int)arg1 ;
-(void)addAnchoredValue:(double)arg1 forWindowSizeHeight:(unsigned long long)arg2 ;
-(double)valueForSize:(double)arg1 ;
-(void)addAnchoredValue:(double)arg1 forSize:(double)arg2 layoutShift:(BOOL)arg3 ;
-(void)addAnchoredValue:(double)arg1 forWindowSizeWidth:(unsigned long long)arg2 layoutShift:(BOOL)arg3 ;
-(void)addAnchoredValue:(double)arg1 forWindowSizeHeight:(unsigned long long)arg2 layoutShift:(BOOL)arg3 ;
-(void)_sort;
-(int)calculationType;
-(double)_nearestValueForSize:(double)arg1 ;
-(double)_interpolatedValueForSize:(double)arg1 ;
-(void)_findBoundsForSize:(double)arg1 outLowerBound:(id*)arg2 outUpperBound:(id*)arg3 outExactMatchValue:(double*)arg4 outFoundExactMatch:(BOOL*)arg5 ;
-(double)_roundValue:(double)arg1 ;
-(int)roundingType;
-(void)addAnchoredValue:(double)arg1 forSize:(double)arg2 ;
-(void)setCalculationType:(int)arg1 ;
-(void)addAnchoredValue:(double)arg1 forWindowSizeWidth:(unsigned long long)arg2 ;
-(double)valueForWindowSizeWidth:(unsigned long long)arg1 ;
-(double)valueForWindowSizeHeight:(unsigned long long)arg1 ;
-(id)init;
-(id)description;
@end

