/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:46 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <MobileCal/DayNavigationViewCell.h>

@class NSString, TappableDayNumber, UILabel, EKUITodayCirclePulseView, UIColor, UIView;

@interface CompactDayNavigationViewCell : DayNavigationViewCell {

	BOOL _monthAnimationState;
	BOOL _hasOverlay;
	NSString* _displayString;
	NSString* _overlayString;
	TappableDayNumber* _dateNumber;
	UILabel* _monthAnimationStateDayNumber;
	UILabel* _monthAnimationStateOverlay;
	double _circleDiameter;
	double _circleDiameterOverlay;
	double _circleDiameterOverlayLarge;
	EKUITodayCirclePulseView* _pulseView;
	UIColor* _weekendColor;
	BOOL _verticallyCompressedState;
	double _baselineOffset;
	UIView* _eventCountsSubview;
	UILabel* _label;

}

@property (nonatomic,retain) UIColor * weekendColor; 
@property (assign,nonatomic) double baselineOffset;                       //@synthesize baselineOffset=_baselineOffset - In the implementation block
@property (nonatomic,readonly) CGRect circleFrame; 
@property (nonatomic,retain) UIView * eventCountsSubview;                 //@synthesize eventCountsSubview=_eventCountsSubview - In the implementation block
@property (assign,nonatomic) BOOL monthAnimationState; 
@property (assign,nonatomic) BOOL verticallyCompressedState;              //@synthesize verticallyCompressedState=_verticallyCompressedState - In the implementation block
@property (nonatomic,readonly) UILabel * label;                           //@synthesize label=_label - In the implementation block
+(double)standardCircleDiameter;
+(double)overlayCircleDiameter;
+(double)largeOverlayCircleDiameter;
+(id)_boldFont;
+(id)_overlayFont;
+(void)localeChanged;
+(double)circleDiameter;
-(CGRect)circleFrame;
-(id)initWithFrame:(CGRect)arg1 loadMonthAnimationState:(BOOL)arg2 hasOverlay:(BOOL)arg3 ;
-(void)_createMonthAnimationStateModeSubviews;
-(void)setCircled:(BOOL)arg1 ;
-(void)setIsToday:(BOOL)arg1 ;
-(void)setIsWeekend:(BOOL)arg1 ;
-(void)touchDownOccurred:(id)arg1 ;
-(void)touchUpOccurred:(id)arg1 ;
-(void)_loadMonthAnimationStateOverlayIfNeeded;
-(void)setWeekendColor:(UIColor *)arg1 ;
-(UIColor *)weekendColor;
-(void)setCircled:(BOOL)arg1 animated:(BOOL)arg2 ;
-(UIView *)eventCountsSubview;
-(void)setDate:(id)arg1 forceStringUpdate:(BOOL)arg2 ;
-(void)setDisplayedString:(id)arg1 ;
-(void)updateOverlay;
-(void)_updateDisplayedString;
-(void)setUnderlineThickness:(double)arg1 ;
-(double)_circleDiameter;
-(double)yCenterForDayNumbers;
-(BOOL)verticallyCompressedState;
-(void)setMonthAnimationState:(BOOL)arg1 ;
-(BOOL)monthAnimationState;
-(void)setVerticallyCompressedState:(BOOL)arg1 ;
-(void)setEventCountsSubview:(UIView *)arg1 ;
-(void)setCircleDiameter:(double)arg1 overlayDiameter:(double)arg2 largeOverlayDiameter:(double)arg3 ;
-(double)_circleXForDiameter:(double)arg1 ;
-(void)pulseToday;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setNeedsDisplay;
-(void)setBackgroundColor:(id)arg1 ;
-(void)layoutSubviews;
-(void)prepareForReuse;
-(UILabel *)label;
-(double)baselineOffset;
-(void)setBaselineOffset:(double)arg1 ;
-(void)setDate:(id)arg1 ;
-(void)touchCancelled:(id)arg1 ;
-(void)_createSubviews;
-(void)setOverlayString:(id)arg1 ;
-(void)_updateTextColor;
-(void)stopPulsing;
@end

