/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:47 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/YearViewYearHeader.h>

@interface CompactYearViewYearHeader : YearViewYearHeader
+(double)headerYInset;
+(double)middleHeight;
+(double)headerDaySpacing;
-(id)yearNumberFont;
-(double)yearNumberKerning;
-(id)overlayLegendFont;
-(double)heightBetweenLineAndNumber;
-(double)overlayLegendLineLength;
-(double)overlayLegendRightInset;
-(double)overlayLegendSpacing;
-(double)overlayLegendYearBaseline;
-(double)overlayLegendMonthBaseline;
-(double)overlayLegendYearLineThickness;
-(double)overlayLegendMonthLineThickness;
@end

