/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:47 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <MobileCal/CompactMonthViewController.h>
#import <MobileCal/CompactMonthListViewControllerDelegate.h>
#import <libobjc.A.dylib/EKEventViewDelegate.h>
#import <libobjc.A.dylib/ABPersonViewControllerDelegate.h>
#import <libobjc.A.dylib/EKEventViewDelegatePrivate.h>
#import <UIKit/UIViewControllerPreviewingDelegate.h>
#import <libobjc.A.dylib/_UIInteractionProgressObserver.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol UIViewControllerPreviewing;
@class EKCalendarDate, TappableDayNumber, CompactMonthWeekView, CompactMonthListViewController, UIView, NSCalendar, UIColor, NSArray, UILongPressGestureRecognizer, UITapGestureRecognizer, CompactMonthDayHintCircle, UIInteractionProgress, NSString;

@interface CompactWidthMonthViewController : CompactMonthViewController <CompactMonthListViewControllerDelegate, EKEventViewDelegate, ABPersonViewControllerDelegate, EKEventViewDelegatePrivate, UIViewControllerPreviewingDelegate, _UIInteractionProgressObserver, UIGestureRecognizerDelegate> {

	BOOL _shouldSetSelectedDate;
	EKCalendarDate* _pressedDay;
	TappableDayNumber* _pressHighlight;
	CompactMonthWeekView* _pressedMonthView;
	CompactMonthListViewController* _listViewController;
	UIView* _listViewContainer;
	UIView* _listViewContainerTopLine;
	CompactMonthWeekView* _selectedMonthWeekView;
	BOOL _loadingOccurrenceCache;
	BOOL _needToReloadEventsOnAppear;
	BOOL _eventLoadingSuspendedForScroll;
	BOOL _reloadAfterStoppedScrolling;
	BOOL _dividedListMode;
	BOOL _dividedListModeAnimationInProgress;
	EKCalendarDate* _currentBackButtonDate;
	UIView* _topLineView;
	NSCalendar* _weekCalculationCalendar;
	BOOL _inAnimationSplitState;
	BOOL _splitOpen;
	UIColor* _originalBackgroundColor;
	UIColor* _originalScrollViewBackgroundColor;
	CGRect _splitCutOutRect;
	double _topBoundaryY;
	NSArray* _clipViews;
	NSArray* _originalSubviewYs;
	NSArray* _viewsToMove;
	BOOL _editorDismissedFromDelete;
	id<UIViewControllerPreviewing> _viewControllerPreviewingRegistration;
	BOOL _suspendEventLoading;
	UILongPressGestureRecognizer* _dayCellsScrubbingGestureRecognizer;
	UITapGestureRecognizer* _dayCellsTapGestureRecognizer;
	CompactMonthDayHintCircle* _pressHintDayCircle;
	UIInteractionProgress* _pressHintInteractionProgress;

}

@property (assign,nonatomic) BOOL suspendEventLoading;                                                       //@synthesize suspendEventLoading=_suspendEventLoading - In the implementation block
@property (nonatomic,readonly) BOOL dividedListMode; 
@property (nonatomic,readonly) CGRect frameOfListView; 
@property (nonatomic,retain) UILongPressGestureRecognizer * dayCellsScrubbingGestureRecognizer;              //@synthesize dayCellsScrubbingGestureRecognizer=_dayCellsScrubbingGestureRecognizer - In the implementation block
@property (nonatomic,retain) UITapGestureRecognizer * dayCellsTapGestureRecognizer;                          //@synthesize dayCellsTapGestureRecognizer=_dayCellsTapGestureRecognizer - In the implementation block
@property (nonatomic,retain) CompactMonthDayHintCircle * pressHintDayCircle;                                 //@synthesize pressHintDayCircle=_pressHintDayCircle - In the implementation block
@property (assign,nonatomic,__weak) UIInteractionProgress * pressHintInteractionProgress;                    //@synthesize pressHintInteractionProgress=_pressHintInteractionProgress - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)_shouldForwardViewWillTransitionToSize;
-(void)showEvent:(id)arg1 animated:(BOOL)arg2 showDetails:(BOOL)arg3 ;
-(void)showEvent:(id)arg1 animated:(BOOL)arg2 showDetails:(BOOL)arg3 showComments:(BOOL)arg4 ;
-(void)showEvent:(id)arg1 animated:(BOOL)arg2 ;
-(void)updatePalette:(id)arg1 ;
-(id)bestDateForNewEvent;
-(int)supportedToggleMode;
-(BOOL)shouldUpdateOwnBackButtonWhenTopViewController;
-(id)updateBackButtonWhileTopViewControllerToDate:(id)arg1 ;
-(BOOL)isTodayVisible;
-(id)initWithCalendarDate:(id)arg1 model:(id)arg2 ;
-(BOOL)_isTodayCircleFrameFullyUnobstructed;
-(double)heightForSubviewWithCalendarDate:(id)arg1 ;
-(double)decelerationDistanceThresholdForPreferringMonthBoundary;
-(double)decelerationDistanceThresholdForDisplayingMonthBanner;
-(void)didEndScrolling;
-(void)calendarModelTimeZoneChanged;
-(double)decelerationDistanceThresholdToStopShowingMonthBanner;
-(double)showDateVerticalOffset;
-(void)willEndDraggingWithVelocity:(CGPoint)arg1 targetContentOffset:(inout CGPoint*)arg2 ;
-(CGRect)frameForWeekContainingDate:(id)arg1 ;
-(id)cellFramesForWeekContainingDate:(id)arg1 ;
-(id)pushedDayViewControllerWithDate:(id)arg1 animated:(BOOL)arg2 ;
-(void)enterAnimationSplitStateWithCutOutArea:(CGRect)arg1 topBoundary:(double)arg2 ;
-(void)setSplitStateOpen:(BOOL)arg1 ;
-(void)endAnimationSplitState;
-(void)_occurrencesChanged:(id)arg1 ;
-(void)compactMonthListViewController:(id)arg1 wantsToCommitViewControllerFromPreview:(id)arg2 ;
-(void)compactMonthListViewController:(id)arg1 didSelectEvent:(id)arg2 ;
-(BOOL)dividedListMode;
-(id)pushedListViewControllerWithDate:(id)arg1 animated:(BOOL)arg2 ;
-(id)createInitialViewForDate:(id)arg1 ;
-(double)topInsetForSubviewWithCalendarDate:(id)arg1 ;
-(unsigned long long)maximumCachedReusableViews;
-(BOOL)shouldUpdateSelectedDateWithCentralView;
-(void)didLoadInitialViews;
-(id)newTopViewAboveViewWithCalendarDate:(id)arg1 ;
-(id)newBottomViewBelowViewWithCalendarDate:(id)arg1 ;
-(void)showDate:(id)arg1 animated:(BOOL)arg2 completionBlock:(/*^block*/id)arg3 ;
-(CGRect)frameOfListView;
-(void)_showEventsPreferenceChanged;
-(void)_cachedOccurrencesChanged:(id)arg1 ;
-(void)_setupListViewController;
-(void)_updateListViewFrame;
-(void)_updateDividedListTopLineForDividedMode:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)_setSelectedDay:(id)arg1 onMonthWeekView:(id)arg2 animated:(BOOL)arg3 ;
-(void)_loadEventsForAllSubviews;
-(void)_registerGestureRecognizers;
-(void)_unregisterGestureRecognizers;
-(void)_removeMonthHighlight;
-(BOOL)_isShowingSingleMonthInDividedMode;
-(id)_loadEventsForStartDate:(id)arg1 endDate:(id)arg2 ;
-(BOOL)suspendEventLoading;
-(BOOL)_shouldAnimateDots;
-(void)_updateNavigationControllerBackButton;
-(void)_showDetailsForEvent:(id)arg1 animated:(BOOL)arg2 showComments:(BOOL)arg3 ;
-(id)monthWeekViewForCalendarDate:(id)arg1 ;
-(BOOL)_isTodayHighlightVisible;
-(double)_showDateVerticalOffsetForMode:(BOOL)arg1 ;
-(BOOL)_showSingleMonthOnlyInDividedMode;
-(unsigned long long)_offsetNumberOfWeeksFromSelectedMonthForTopVisibleMonth;
-(id)dateForTopVisibleMonthOnScreen;
-(void)_updateViewsForTimeZoneChange;
-(void)setDayCellsTapGestureRecognizer:(UITapGestureRecognizer *)arg1 ;
-(UITapGestureRecognizer *)dayCellsTapGestureRecognizer;
-(void)_tapGestureCallback:(id)arg1 ;
-(void)setDayCellsScrubbingGestureRecognizer:(UILongPressGestureRecognizer *)arg1 ;
-(UILongPressGestureRecognizer *)dayCellsScrubbingGestureRecognizer;
-(void)_scrubGestureCallback:(id)arg1 ;
-(void)_enableOrb;
-(void)_disableOrb;
-(void)_removePressHintDayCircle;
-(UIInteractionProgress *)pressHintInteractionProgress;
-(void)setPressHintInteractionProgress:(UIInteractionProgress *)arg1 ;
-(void)monthView:(id)arg1 gestureBegan:(id)arg2 ;
-(void)monthView:(id)arg1 gestureEnded:(id)arg2 ;
-(void)monthView:(id)arg1 gestureChanged:(id)arg2 ;
-(void)monthView:(id)arg1 gestureCancelled:(id)arg2 ;
-(void)_initPressHintDayCircleWithLocation:(CGPoint)arg1 inSourceView:(id)arg2 inContainerView:(id)arg3 ;
-(CompactMonthDayHintCircle *)pressHintDayCircle;
-(void)_setSelectedDay:(id)arg1 ;
-(void)setPressHintDayCircle:(CompactMonthDayHintCircle *)arg1 ;
-(void)_animatePressHintDayCircleToPeekStateFromPercentComplete:(double)arg1 ;
-(id)_dayInMonth:(id)arg1 fromGesture:(id)arg2 ;
-(void)_createMonthHighlightForMonthView:(id)arg1 day:(id)arg2 ;
-(id)_viewFromGesture:(id)arg1 ;
-(void)_loadEventsForViewsInRangeStartingAt:(id)arg1 endingAt:(id)arg2 ;
-(double)_scrollViewVerticalVelocity;
-(void)_setDividedListView:(BOOL)arg1 ;
-(void)_setDividedListView:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)_completeDividedListViewAnimation:(BOOL)arg1 animated:(BOOL)arg2 ;
-(unsigned long long)_offsetNumberOfWeeksFromSelectedMonthForBottomVisibleMonth;
-(void)_resetSelectionForDividedListState:(BOOL)arg1 ;
-(id)_monthForLastVisibleMonth;
-(id)_snapshotViewForDividedListTransition:(id)arg1 useFastPath:(BOOL)arg2 ;
-(CGPoint)_originForSelectedMonthViewInScrollViewWithState:(BOOL)arg1 ;
-(void)_setToCompressedState:(BOOL)arg1 darkBackgroundState:(BOOL)arg2 ;
-(CGRect)_rectBoundingVisibleWeekSubviews;
-(unsigned long long)_numberOfWeeksInSelectedMonth;
-(void)_showDetailsForEvent:(id)arg1 animated:(BOOL)arg2 ;
-(long long)eventCountDisplayedForDate:(id)arg1 ;
-(id)dateForCurrentMonthOnScreen;
-(void)forceUpdateListView;
-(void)toggleDividedListView;
-(void)setSuspendEventLoading:(BOOL)arg1 ;
-(void)dealloc;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
-(unsigned long long)supportedInterfaceOrientations;
-(void)loadView;
-(void)interactionProgressDidUpdate:(id)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(id)previewingContext:(id)arg1 viewControllerForLocation:(CGPoint)arg2 ;
-(void)previewingContext:(id)arg1 commitViewController:(id)arg2 ;
-(void)animateRevealWithInteractionProgress:(id)arg1 forPreviewingAtLocation:(CGPoint)arg2 inSourceView:(id)arg3 containerView:(id)arg4 ;
-(void)interactionProgress:(id)arg1 didEnd:(BOOL)arg2 finalVelocity:(double)arg3 ;
-(void)didScroll;
-(void)localeChanged;
-(CGRect)frameForTodayHighlight;
-(BOOL)personViewController:(id)arg1 shouldPerformDefaultActionForPerson:(void*)arg2 property:(int)arg3 identifier:(int)arg4 ;
-(void)significantTimeChangeOccurred;
-(void)eventViewController:(id)arg1 willDismissEditViewController:(id)arg2 deleted:(BOOL)arg3 ;
-(BOOL)eventViewControllerShouldHideInlineEditButton;
-(void)eventViewControllerWillDisappear:(id)arg1 ;
-(void)eventViewController:(id)arg1 didCompleteWithAction:(long long)arg2 ;
@end

