/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:47 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/MonthDayTransitionView.h>

@interface DividedMonthDayTransitionView : MonthDayTransitionView {

	/*^block*/id _completion;

}

@property (nonatomic,copy) id completion;              //@synthesize completion=_completion - In the implementation block
-(void)animateToMonthWithCompletion:(/*^block*/id)arg1 ;
-(void)animateToDayWithCompletion:(/*^block*/id)arg1 ;
-(id)completion;
-(void)setCompletion:(id)arg1 ;
@end

