/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:47 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol EKDayViewControllerDataSource <NSObject>
@required
-(id)dayViewController:(id)arg1 eventsForStartDate:(id)arg2 endDate:(id)arg3;
-(BOOL)dayViewControllerShouldRespondToApplicationDidBecomeActiveStateChange:(id)arg1;

@end

