/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:46 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <UIKit/UIView.h>
#import <MobileCal/InfiniteScrollViewSubview.h>
#import <MobileCal/LargeMonthWeekViewOccurrencesViewDelegate.h>

@protocol LargeMonthWeekViewDataSource, LargeMonthWeekViewDelegate;
@class CALayer, _CircleView, NSArray, UIView, NSMutableDictionary, UIScrollView, UILabel, EKCalendarDate, LargeMonthWeekOccurrencesView, EKEvent, NSString;

@interface LargeMonthWeekView : UIView <InfiniteScrollViewSubview, LargeMonthWeekViewOccurrencesViewDelegate> {

	CALayer* _topBorderLine;
	CALayer* _paddingRowBorderLine;
	_CircleView* _todayCircle;
	NSArray* _dayNumberLabels;
	NSArray* _overlayLabels;
	UIView* _overlayUnderline;
	long long _firstOfOverlayMonthIndex;
	BOOL _isFirstOfOverlayYear;
	NSArray* _weekendDayBackgrounds;
	NSMutableDictionary* _highlightedDays;
	UIScrollView* _occurrencesScrollView;
	BOOL _occurrencesHidden;
	long long _firstDayIndex;
	long long _lastDayIndex;
	CGRect _dayFrames[7];
	double _gridlineThickness;
	BOOL _showingFirstDayOfMonthLabel;
	UILabel* _firstOfMonthLabel;
	UILabel* _firstOfMonthNoDayLabel;
	long long _firstOfMonthIndex;
	UILabel* _weekNumberLabel;
	EKCalendarDate* _startDate;
	EKCalendarDate* _endDate;
	long long _dayCount;
	BOOL _isLastWeekOfMonth;
	LargeMonthWeekOccurrencesView* _occurrencesView;
	BOOL _showsTopBorder;
	BOOL _showsWeekNumber;
	long long _todayDay;
	id<LargeMonthWeekViewDataSource> _dataSource;
	id<LargeMonthWeekViewDelegate> _delegate;
	NSRange _highlightedDayRange;

}

@property (nonatomic,copy) EKCalendarDate * startDate; 
@property (nonatomic,copy) EKCalendarDate * endDate; 
@property (assign,nonatomic) long long dayCount; 
@property (assign,nonatomic) long long todayDay;                                              //@synthesize todayDay=_todayDay - In the implementation block
@property (assign,nonatomic) BOOL showsTopBorder;                                             //@synthesize showsTopBorder=_showsTopBorder - In the implementation block
@property (assign,nonatomic) BOOL showsWeekNumber;                                            //@synthesize showsWeekNumber=_showsWeekNumber - In the implementation block
@property (assign,nonatomic) NSRange highlightedDayRange;                                     //@synthesize highlightedDayRange=_highlightedDayRange - In the implementation block
@property (nonatomic,retain) EKEvent * selectedOccurrence; 
@property (assign,nonatomic,__weak) id<LargeMonthWeekViewDataSource> dataSource;              //@synthesize dataSource=_dataSource - In the implementation block
@property (assign,nonatomic,__weak) id<LargeMonthWeekViewDelegate> delegate;                  //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)initialize;
+(id)gridlineColor;
+(double)topInset;
-(void)_viewTapped:(id)arg1 ;
-(void)_viewDoubleTapped:(id)arg1 ;
-(void)_rebuildDayNumberLabels;
-(id)occurrencesView;
-(id)occurrenceAtPoint:(CGPoint)arg1 ;
-(CGRect)frameForOccurrence:(id)arg1 onDay:(id)arg2 ;
-(CGRect)frameForOccurrenceAfterLastOnDay:(id)arg1 ;
-(void)_updateWeekNumber;
-(void)setShowsFirstDayOfMonthLabel:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)_rebuildOverlayLabels;
-(id)dateAtPoint:(CGPoint)arg1 ;
-(BOOL)_hasPaddingRow;
-(void)_updateDayFrames;
-(long long)dayIndexForToday;
-(void)didCompleteLargeMonthWeekViewBackgroundRendering;
-(void)setOccurrencesHidden:(BOOL)arg1 animate:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(CGRect)frameForDate:(id)arg1 ;
-(id)newFeedbackViewForDraggingOccurrence:(id)arg1 atPoint:(CGPoint)arg2 ;
-(void)setHighlightedDayRange:(NSRange)arg1 ;
-(void)setShowsTopBorder:(BOOL)arg1 ;
-(void)setShowsWeekNumber:(BOOL)arg1 ;
-(void)setDayCount:(long long)arg1 ;
-(long long)dayCount;
-(void)setStartDate:(id)arg1 endDate:(id)arg2 dayCount:(long long)arg3 todayDay:(long long)arg4 ;
-(id)dayFrames;
-(id)snapshotImageForDay:(id)arg1 ;
-(id)weekdayLabels;
-(id)todayCircle;
-(CGRect)circleFrame;
-(long long)todayDay;
-(void)setTodayDay:(long long)arg1 ;
-(BOOL)showsTopBorder;
-(BOOL)showsWeekNumber;
-(NSRange)highlightedDayRange;
-(id)calendarDate;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDataSource:(id<LargeMonthWeekViewDataSource>)arg1 ;
-(void)setDelegate:(id<LargeMonthWeekViewDelegate>)arg1 ;
-(void)reloadData;
-(void)layoutSubviews;
-(NSString *)description;
-(id<LargeMonthWeekViewDataSource>)dataSource;
-(id<LargeMonthWeekViewDelegate>)delegate;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)updateToday;
-(BOOL)containsCalendarDate:(id)arg1 ;
-(CGRect)frameForTodayHighlight;
-(id)endCalendarDate;
-(EKEvent *)selectedOccurrence;
-(void)setSelectedOccurrence:(EKEvent *)arg1 ;
-(void)setEndDate:(EKCalendarDate *)arg1 ;
-(void)setStartDate:(EKCalendarDate *)arg1 ;
-(EKCalendarDate *)startDate;
-(EKCalendarDate *)endDate;
-(double)topInset;
@end

