/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:47 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <MobileCal/YearViewController.h>

@class EKCalendarDate;

@interface LargeYearViewController : YearViewController {

	BOOL _viewIsVisible;
	BOOL _viewHasAppearedBefore;
	long long _orientationForCurrentViewLayout;
	EKCalendarDate* _activeDateDuringRotation;
	EKCalendarDate* _currentYearNumber;

}
+(unsigned long long)monthsPerRow;
+(BOOL)_shouldForwardViewWillTransitionToSize;
-(void)showEvent:(id)arg1 animated:(BOOL)arg2 showDetails:(BOOL)arg3 ;
-(void)showEvent:(id)arg1 animated:(BOOL)arg2 showDetails:(BOOL)arg3 showComments:(BOOL)arg4 ;
-(double)leftBarButtonBlankFixedSpaceWidth;
-(void)updatePalette:(id)arg1 ;
-(void)updateNavigationBarDisplayedDateString;
-(void)didEndScrolling;
-(void)reinitializeAllViewsWithCalendarDate:(id)arg1 ;
-(double)showDateVerticalOffset;
-(BOOL)shouldAnimateScrollToDate:(id)arg1 fromClosestDate:(id)arg2 ;
-(Class)multipleMonthViewClass;
-(unsigned long long)monthsPerRow;
-(BOOL)shouldAnimateTransitionsToMonthView;
-(void)timeZoneDidChange;
-(BOOL)_usePortraitLayoutForSize:(CGSize)arg1 ;
-(long long)_orientationForSize:(CGSize)arg1 ;
-(void)_updateYearNumbersAnimated:(BOOL)arg1 withForce:(BOOL)arg2 ;
-(void)_queueForcedUpdateToYearNumbers;
-(unsigned long long)supportedInterfaceOrientations;
-(void)viewWillLayoutSubviews;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(long long)_currentOrientation;
-(void)didScroll;
-(void)localeDidChange;
@end

