/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:47 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <UIKit/UIView.h>

@class NSMutableArray, TopLineView, UILabel, NSArray;

@interface MonthDayNavigationTransitionView : UIView {

	NSMutableArray* _cells;
	TopLineView* _topLine;
	BOOL _hasOverlay;
	BOOL _showWeekNumber;
	UILabel* _weekNumberLabel;
	BOOL _verticallyCompressedState;
	BOOL _debug;
	NSArray* _weekendIndices;
	long long _selectedIndex;
	long long _todayIndex;
	NSArray* _eventCounts;
	double _firstDayCellInset;
	long long _firstDayCellIndex;
	double _monthRowHeight;
	long long _firstMonthCellIndex;
	NSArray* _monthCellFrames;
	long long _monthBreakIndex;
	CGSize _dayCellSize;
	CGRect _dayFrame;
	CGRect _monthFrame;

}

@property (assign,nonatomic) BOOL verticallyCompressedState;              //@synthesize verticallyCompressedState=_verticallyCompressedState - In the implementation block
@property (nonatomic,retain) NSArray * weekendIndices;                    //@synthesize weekendIndices=_weekendIndices - In the implementation block
@property (assign,nonatomic) long long selectedIndex;                     //@synthesize selectedIndex=_selectedIndex - In the implementation block
@property (assign,nonatomic) long long todayIndex;                        //@synthesize todayIndex=_todayIndex - In the implementation block
@property (nonatomic,retain) NSArray * eventCounts;                       //@synthesize eventCounts=_eventCounts - In the implementation block
@property (assign,nonatomic) CGRect dayFrame;                             //@synthesize dayFrame=_dayFrame - In the implementation block
@property (assign,nonatomic) double firstDayCellInset;                    //@synthesize firstDayCellInset=_firstDayCellInset - In the implementation block
@property (assign,nonatomic) long long firstDayCellIndex;                 //@synthesize firstDayCellIndex=_firstDayCellIndex - In the implementation block
@property (assign,nonatomic) CGSize dayCellSize;                          //@synthesize dayCellSize=_dayCellSize - In the implementation block
@property (assign,nonatomic) CGRect monthFrame;                           //@synthesize monthFrame=_monthFrame - In the implementation block
@property (assign,nonatomic) double monthRowHeight;                       //@synthesize monthRowHeight=_monthRowHeight - In the implementation block
@property (assign,nonatomic) long long firstMonthCellIndex;               //@synthesize firstMonthCellIndex=_firstMonthCellIndex - In the implementation block
@property (nonatomic,retain) NSArray * monthCellFrames;                   //@synthesize monthCellFrames=_monthCellFrames - In the implementation block
@property (assign,nonatomic) long long monthBreakIndex;                   //@synthesize monthBreakIndex=_monthBreakIndex - In the implementation block
@property (assign,nonatomic) BOOL debug;                                  //@synthesize debug=_debug - In the implementation block
-(BOOL)verticallyCompressedState;
-(void)setVerticallyCompressedState:(BOOL)arg1 ;
-(CGSize)dayCellSize;
-(void)animateToMonthLayout;
-(void)_animateView:(id)arg1 toPosition:(CGPoint)arg2 ;
-(void)animateToDayLayout;
-(void)setEventCounts:(NSArray *)arg1 ;
-(NSArray *)eventCounts;
-(void)setDayCellSize:(CGSize)arg1 ;
-(void)setTodayIndex:(long long)arg1 ;
-(void)setStrings:(id)arg1 overlayStrings:(id)arg2 weekNumberString:(id)arg3 ;
-(void)setUnderlineThickness:(double)arg1 forOverlayStringAtIndex:(long long)arg2 ;
-(void)setWeekendIndices:(NSArray *)arg1 ;
-(void)setDayFrame:(CGRect)arg1 ;
-(void)setFirstDayCellInset:(double)arg1 ;
-(void)setFirstDayCellIndex:(long long)arg1 ;
-(void)setMonthFrame:(CGRect)arg1 ;
-(void)setFirstMonthCellIndex:(long long)arg1 ;
-(void)setMonthCellFrames:(NSArray *)arg1 ;
-(void)setMonthRowHeight:(double)arg1 ;
-(void)setMonthBreakIndex:(long long)arg1 ;
-(void)completeSetup;
-(long long)todayIndex;
-(CGRect)dayFrame;
-(CGRect)monthFrame;
-(void)_updateEventIndicatorDots;
-(void)_updateWeekendIndices;
-(double)_yOffsetForMonthCells;
-(NSArray *)weekendIndices;
-(void)_setToMonthStateAnimated:(BOOL)arg1 ;
-(void)_setToDayStateAnimated:(BOOL)arg1 ;
-(double)firstDayCellInset;
-(long long)monthBreakIndex;
-(id)_todayCell;
-(id)_selectedCell;
-(long long)firstMonthCellIndex;
-(NSArray *)monthCellFrames;
-(long long)firstDayCellIndex;
-(double)monthRowHeight;
-(void)setDebug:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(long long)selectedIndex;
-(void)setSelectedIndex:(long long)arg1 ;
-(BOOL)debug;
@end

