/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:28:46 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <MobileCal/InfiniteScrollViewController.h>

@class CalendarModel, EKCalendarDate, MonthTitleView, UIFont;

@interface MonthViewController : InfiniteScrollViewController {

	CalendarModel* _model;
	EKCalendarDate* _backButtonDate;
	BOOL _backButtonShowingInterval;
	double _decelerationTargetY;
	EKCalendarDate* _decelerationTargetDate;
	MonthTitleView* _monthTitleView;
	BOOL _monthTitleViewIsVisible;
	BOOL _shouldShowMonthTitleHUDWhenScrolling;
	UIFont* _headerFont;

}

@property (readonly) UIFont * headerFont;                                            //@synthesize headerFont=_headerFont - In the implementation block
@property (assign,nonatomic) BOOL shouldShowMonthTitleHUDWhenScrolling;              //@synthesize shouldShowMonthTitleHUDWhenScrolling=_shouldShowMonthTitleHUDWhenScrolling - In the implementation block
-(void)showDate:(id)arg1 animated:(BOOL)arg2 ;
-(void)showEvent:(id)arg1 animated:(BOOL)arg2 showDetails:(BOOL)arg3 ;
-(void)showEvent:(id)arg1 animated:(BOOL)arg2 showDetails:(BOOL)arg3 showComments:(BOOL)arg4 ;
-(void)selectDate:(id)arg1 animated:(BOOL)arg2 ;
-(void)updateBackButtonToDate:(id)arg1 ;
-(void)_updateBackButtonOnBackViewControllerToDate:(id)arg1 ;
-(void)showEvent:(id)arg1 animated:(BOOL)arg2 ;
-(BOOL)shouldPushNextLevelViewControllerWhenTodayIsVisible;
-(id)bestDateForNewEvent;
-(BOOL)isTodayVisible;
-(BOOL)allowsOverriddenRightNavigationBarItems;
-(BOOL)allowsOverriddenToolbarItems;
-(id)initWithCalendarDate:(id)arg1 model:(id)arg2 ;
-(void)_calendarModelTimeZoneChanged:(id)arg1 ;
-(void)weekNumbersPrefChanged;
-(void)_selectedDateChanged:(id)arg1 ;
-(id)pastMajorBoundaryCalendarDateForCalendarDate:(id)arg1 ;
-(id)_slowComputeCalendarDateForWeekFromStartDate:(id)arg1 weekOffset:(long long)arg2 ;
-(void)showDate:(id)arg1 animated:(BOOL)arg2 toMonthStart:(BOOL)arg3 ;
-(BOOL)_isTodayCircleFrameFullyUnobstructed;
-(id)calendarDateForSubviewBelowSubviewWithCalendarDate:(id)arg1 ;
-(void)willBeginDragging;
-(void)_updateMonthTitle;
-(double)decelerationDistanceThresholdForPreferringMonthBoundary;
-(CGPoint)nearestMajorBoundaryForPoint:(CGPoint)arg1 ;
-(double)decelerationDistanceThresholdForDisplayingMonthBanner;
-(void)didEndScrolling;
-(void)calendarModelTimeZoneChanged;
-(void)_reloadAllViews;
-(double)decelerationDistanceThresholdToStopShowingMonthBanner;
-(BOOL)shouldAnimateScrollToDate:(id)arg1 fromClosestDate:(id)arg2 ;
-(id)futureMajorBoundaryCalendarDateForCalendarDate:(id)arg1 ;
-(id)calendarDateForSubviewAboveSubviewWithCalendarDate:(id)arg1 ;
-(void)willEndDraggingWithVelocity:(CGPoint)arg1 targetContentOffset:(inout CGPoint*)arg2 ;
-(CGRect)frameForWeekContainingDate:(id)arg1 ;
-(id)cellFramesForWeekContainingDate:(id)arg1 ;
-(id)adjustSelectedDateForNewMonth:(id)arg1 ;
-(BOOL)shouldShowMonthTitleHUDWhenScrolling;
-(void)setShouldShowMonthTitleHUDWhenScrolling:(BOOL)arg1 ;
-(void)dealloc;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)didScroll;
-(void)localeChanged;
-(void)_localeChanged:(id)arg1 ;
-(CGRect)frameForTodayHighlight;
-(void)significantTimeChangeOccurred;
-(UIFont *)headerFont;
-(void)_significantTimeChangeOccurred:(id)arg1 ;
-(id)monthTitleView;
@end

