/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:20:14 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SXItemizedScrollViewDataSource <NSObject>
@optional
-(BOOL)itemizedScrollViewWillReindex:(id)arg1;
-(BOOL)itemizedScrollView:(id)arg1 isAllowedToAddViewInHierarchy:(unsigned long long)arg2;
-(double)gutterBetweenItemsInNotPagingItemizedScrollView:(id)arg1;

@required
-(unsigned long long)numberOfViewsInItemizedScrollView:(id)arg1;
-(CGRect*)itemizedScrollView:(id)arg1 frameForViewAtIndex:(unsigned long long)arg2;
-(id)itemizedScrollView:(id)arg1 viewAtIndex:(unsigned long long)arg2;

@end

