/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 3:20:11 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXJSONObject.h>

@class UIColor;

@interface SXTextStroke : SXJSONObject

@property (nonatomic,readonly) UIColor * color; 
@property (nonatomic,readonly) double width; 
-(double)width;
-(UIColor *)color;
@end

