/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:13 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct sqlite3_stmt* sqlite3_stmtRef;

typedef struct sqlite3* sqlite3Ref;

typedef struct __CFString* CFStringRef;

typedef struct _NSZone* NSZoneRef;

typedef struct NSRange {
	unsigned long long location;
	unsigned long long length;
} NSRange;

typedef struct __SCNetworkReachability* SCNetworkReachabilityRef;

typedef struct __SecTrust* SecTrustRef;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct FairPlayHWInfo_ {
	unsigned IDLength;
	unsigned char ID[20];
} FairPlayHWInfo_;

typedef struct FPSAPContextOpaque_* FPSAPContextOpaque_Ref;

typedef struct {
	unsigned _platform : 8;
	unsigned _prerendered : 1;
	unsigned _supportsLeaderboards : 1;
	unsigned _supportsLeaderboardSets : 1;
	unsigned _hasAggregateLeaderboard : 1;
	unsigned _supportsAchievements : 1;
	unsigned _supportsMultiplayer : 1;
	unsigned _valid : 1;
	unsigned _unused : 1;
	unsigned _supportsTurnBasedMultiplayer : 1;
	unsigned _reserved : 13;
} SCD_Struct_GK10;

typedef union {
	SCD_Struct_GK10 field1;
	unsigned _value;
} SCD_Union_GK11;

typedef struct {
	unsigned _unused : 8;
	unsigned _purpleBuddyAccount : 1;
	unsigned _underage : 1;
	unsigned _photoPending : 1;
	unsigned _findable : 1;
	unsigned _reserved : 18;
} SCD_Struct_GK12;

typedef union {
	SCD_Struct_GK12 field1;
	unsigned _value;
} SCD_Union_GK13;

typedef struct {
	unsigned _maximumPoints : 16;
	unsigned _hidden : 1;
	unsigned _replayable : 1;
	unsigned _reserved : 14;
} SCD_Struct_GK14;

typedef union {
	SCD_Struct_GK14 field1;
	unsigned _value;
} SCD_Union_GK15;

