/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:13 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <gamed/GKService.h>
#import <gamed/GKAccountService.h>

@class NSString;

@interface GKAccountService : GKService <GKAccountService>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(Class)interfaceClass;
+(unsigned long long)requiredEntitlements;
-(void)dealloc;
-(oneway void)authenticatePlayerWithExistingCredentialsWithHandler:(/*^block*/id)arg1 ;
-(oneway void)generateIdentityVerificationSignatureWithHandler:(/*^block*/id)arg1 ;
@end

