/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:12 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSMutableDictionary, NSObject;

@interface GKBadgeController : NSObject {

	NSMutableDictionary* _badgeDictionaries[3];
	NSObject*<OS_dispatch_queue> _syncQueue;
	BOOL _dirty;

}
+(id)sharedController;
-(void)setBadgeCount:(unsigned long long)arg1 forBundleID:(id)arg2 badgeType:(unsigned long long)arg3 ;
-(id)_plistKeyForBadgeType:(unsigned long long)arg1 ;
-(id)_badgeCountURL;
-(BOOL)isBadgingEnabledForBundleID:(id)arg1 ;
-(unsigned long long)_badgeCountForBundleID:(id)arg1 badgeType:(unsigned long long)arg2 ;
-(id)_dictionaryForBadgeType:(unsigned long long)arg1 ;
-(unsigned long long)_totalBadgeCountForBundleID:(id)arg1 ;
-(void)badgeApplicationWithBundleID:(id)arg1 badgeCount:(unsigned long long)arg2 ;
-(unsigned long long)badgeCountForBundleID:(id)arg1 badgeType:(unsigned long long)arg2 ;
-(void)badgeAllApplications;
-(void)unbadgeAllApplications;
-(void)registerBadgePermissionForBundleID:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)synchronize;
@end

