/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:11 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <gamed/gamed-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSString, NSDictionary, BBAction;

@interface GKBulletinAction : NSObject <NSCoding, NSSecureCoding> {

	BOOL _isDestructive;
	BOOL _inAlertView;
	BOOL _inBannerView;
	long long _type;
	NSString* _title;
	NSString* _info;

}

@property (assign) long long type;                                 //@synthesize type=_type - In the implementation block
@property (retain) NSString * title;                               //@synthesize title=_title - In the implementation block
@property (retain) NSString * info;                                //@synthesize info=_info - In the implementation block
@property (assign) BOOL isDestructive;                             //@synthesize isDestructive=_isDestructive - In the implementation block
@property (readonly) NSDictionary * actionDictionary; 
@property (readonly) BBAction * BBAction; 
@property (assign) BOOL inAlertView;                               //@synthesize inAlertView=_inAlertView - In the implementation block
@property (assign) BOOL inBannerView;                              //@synthesize inBannerView=_inBannerView - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)setIsDestructive:(BOOL)arg1 ;
-(void)setInAlertView:(BOOL)arg1 ;
-(BBAction *)BBAction;
-(BOOL)inAlertView;
-(BOOL)inBannerView;
-(NSDictionary *)actionDictionary;
-(void)setInBannerView:(BOOL)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setTitle:(NSString *)arg1 ;
-(id)description;
-(id)initWithDictionary:(id)arg1 ;
-(void)setType:(long long)arg1 ;
-(long long)type;
-(NSString *)title;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)info;
-(BOOL)isDestructive;
-(void)setInfo:(NSString *)arg1 ;
@end

