/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:10 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol GKCacheObjectImageProtocol <NSObject>
@property (nonatomic,retain) NSString * image64; 
@property (nonatomic,retain) NSString * image128; 
@property (nonatomic,retain) NSString * image256; 
@property (nonatomic,retain) NSString * image512; 
@property (nonatomic,retain) NSString * imageTemplate; 
@required
-(void)setImage512:(id)arg1;
-(NSString *)image256;
-(void)setImage256:(id)arg1;
-(NSString *)image512;
-(void)setImage64:(id)arg1;
-(NSString *)image64;
-(void)setImage128:(id)arg1;
-(NSString *)image128;
-(NSString *)imageTemplate;
-(void)setImageTemplate:(id)arg1;

@end

