/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:11 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <gamed/GKCacheObject.h>

@class NSString, GKChallengeCacheObject;

@interface GKChallengeCompatibleBundleID : GKCacheObject

@property (nonatomic,retain) NSString * bundleID; 
@property (nonatomic,retain) GKChallengeCacheObject * challenge; 
+(id)entityName;
-(void)updateWithServerRepresentation:(id)arg1 ;
-(id)internalRepresentation;
@end

