/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:13 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <gamed/GKService.h>
#import <gamed/GKChallengeService.h>

@protocol GKChallengeService <NSObject>
@required
-(oneway void)getChallengesForGameDescriptor:(id)arg1 handler:(/*^block*/id)arg2;
-(oneway void)getChallengeDetailsForChallengeIDs:(id)arg1 handler:(/*^block*/id)arg2;
-(oneway void)getChallengeDetailsForChallengeIDs:(id)arg1 receiverID:(id)arg2 handler:(/*^block*/id)arg3;
-(oneway void)issueChallenge:(id)arg1 toPlayers:(id)arg2 handler:(/*^block*/id)arg3;
-(oneway void)abortChallenges:(id)arg1 handler:(/*^block*/id)arg2;

@end


@class NSString;

@interface GKChallengeService : GKService <GKChallengeService>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(Class)interfaceClass;
+(unsigned long long)requiredEntitlements;
-(void)loadChallengesForGameDescriptor:(id)arg1 context:(id)arg2 handler:(/*^block*/id)arg3 ;
-(void)fetchChallengesForGameDescriptor:(id)arg1 context:(id)arg2 handler:(/*^block*/id)arg3 ;
-(id)_filterChallenges:(id)arg1 compatibleWithBundleID:(id)arg2 ;
-(void)_determineCompatibleGamesForChallenges:(id)arg1 dispatchGroup:(id)arg2 ;
-(void)_updatePlayersForChallenges:(id)arg1 dispatchGroup:(id)arg2 ;
-(void)_updateGamesForChallenges:(id)arg1 dispatchGroup:(id)arg2 ;
-(oneway void)getChallengesForGameDescriptor:(id)arg1 handler:(/*^block*/id)arg2 ;
-(oneway void)getChallengeDetailsForChallengeIDs:(id)arg1 handler:(/*^block*/id)arg2 ;
-(oneway void)getChallengeDetailsForChallengeIDs:(id)arg1 receiverID:(id)arg2 handler:(/*^block*/id)arg3 ;
-(oneway void)issueChallenge:(id)arg1 toPlayers:(id)arg2 handler:(/*^block*/id)arg3 ;
-(oneway void)abortChallenges:(id)arg1 handler:(/*^block*/id)arg2 ;
@end

