/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:10 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <gamed/GKPurgeableCacheObject.h>

@class NSDate;

@interface GKExpiringCacheObject : GKPurgeableCacheObject

@property (nonatomic,retain) NSDate * timeStamp; 
@property (nonatomic,retain) NSDate * expirationDate; 
@property (nonatomic,readonly) BOOL expired; 
+(id)fetchSortDescriptors;
+(void)expireObjectsMatchingPredicate:(id)arg1 context:(id)arg2 ;
+(void)invalidateObjectsMatchingPredicate:(id)arg1 context:(id)arg2 ;
-(void)updateWithServerRepresentation:(id)arg1 ;
-(void)updateWithServerRepresentation:(id)arg1 expirationDate:(id)arg2 ;
-(void)invalidate;
-(BOOL)isValid;
-(void)awakeFromInsert;
-(BOOL)expired;
-(void)expire;
@end

