/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:13 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <gamed/GKUIServiceClientProxy.h>

@interface GKExtensionClientProxy : GKUIServiceClientProxy
-(BOOL)isUIService;
-(void)setExtensionProxy:(id)arg1 forBundleID:(id)arg2 ;
-(void)dealloc;
-(oneway void)setHostPID:(int)arg1 reply:(/*^block*/id)arg2 ;
-(BOOL)isExtension;
@end

