/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:13 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <gamed/GKDataReader.h>

@class NSString, GKDatabaseConnection, GKDataTransport;

@interface GKPlayerProfileReader : NSObject <GKDataReader> {

	NSString* _localPlayerID;
	NSString* _language;
	GKDatabaseConnection* _readerConnection;
	GKDatabaseConnection* _writerConnection;
	GKDataTransport* _transport;

}

@property (nonatomic,retain) NSString * localPlayerID;                             //@synthesize localPlayerID=_localPlayerID - In the implementation block
@property (nonatomic,retain) NSString * language;                                  //@synthesize language=_language - In the implementation block
@property (nonatomic,retain) GKDatabaseConnection * readerConnection;              //@synthesize readerConnection=_readerConnection - In the implementation block
@property (nonatomic,retain) GKDatabaseConnection * writerConnection;              //@synthesize writerConnection=_writerConnection - In the implementation block
@property (nonatomic,retain) GKDataTransport * transport;                          //@synthesize transport=_transport - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)readerWithLocalPlayer:(id)arg1 language:(id)arg2 readerConnection:(id)arg3 writerConnection:(id)arg4 transport:(id)arg5 ;
-(void)setLocalPlayerID:(NSString *)arg1 ;
-(NSString *)localPlayerID;
-(void)readResources:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)setReaderConnection:(GKDatabaseConnection *)arg1 ;
-(void)setWriterConnection:(GKDatabaseConnection *)arg1 ;
-(id)initWithLocalPlayer:(id)arg1 language:(id)arg2 readerConnection:(id)arg3 writerConnection:(id)arg4 transport:(id)arg5 ;
-(int)familiarityForPlayer:(id)arg1 ;
-(void)dealloc;
-(NSString *)language;
-(void)setLanguage:(NSString *)arg1 ;
-(GKDatabaseConnection *)writerConnection;
-(GKDatabaseConnection *)readerConnection;
-(id)poolName;
-(GKDataTransport *)transport;
-(void)setTransport:(GKDataTransport *)arg1 ;
@end

