/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:11 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <gamed/GKClientProxy.h>
#import <gamed/GKUIViewService.h>

@class GKClientProxy, NSString;

@interface GKUIServiceClientProxy : GKClientProxy <GKUIViewService> {

	GKClientProxy* _weakHostClient;

}

@property (assign,nonatomic) GKClientProxy * hostClient;              //@synthesize weakHostClient=_weakHostClient - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)existingViewService;
-(BOOL)isUIService;
-(void)terminateWithCompletionHandler:(/*^block*/id)arg1 ;
-(GKClientProxy *)hostClient;
-(void)setHostClient:(GKClientProxy *)arg1 ;
-(void)setExtensionProxy:(id)arg1 forBundleID:(id)arg2 ;
-(id)viewService;
-(void)dealloc;
-(oneway void)setHostPID:(int)arg1 reply:(/*^block*/id)arg2 ;
-(oneway void)getServicesForPID:(int)arg1 localPlayer:(id)arg2 reply:(/*^block*/id)arg3 ;
-(oneway void)getPrivateServicesForPID:(int)arg1 localPlayer:(id)arg2 reply:(/*^block*/id)arg3 ;
-(void)setViewService:(id)arg1 ;
@end

