/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:27 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/pkd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/LSApplicationWorkspaceObserverProtocol.h>

@protocol PKDatabaseDelegate, OS_dispatch_queue;
@class LSApplicationWorkspace, PKDAnnotationStore, NSObject, NSMutableDictionary, NSString;

@interface PKDatabase : NSObject <LSApplicationWorkspaceObserverProtocol> {

	unsigned _cacheLimit;
	id<PKDatabaseDelegate> _delegate;
	LSApplicationWorkspace* _workspace;
	PKDAnnotationStore* _annotations;
	NSObject*<OS_dispatch_queue> __sync;
	NSMutableDictionary* _cache;

}

@property (__weak) id<PKDatabaseDelegate> delegate;                           //@synthesize delegate=_delegate - In the implementation block
@property (assign) unsigned cacheLimit;                                       //@synthesize cacheLimit=_cacheLimit - In the implementation block
@property (nonatomic,retain) LSApplicationWorkspace * workspace;              //@synthesize workspace=_workspace - In the implementation block
@property (nonatomic,retain) PKDAnnotationStore * annotations;                //@synthesize annotations=_annotations - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> _sync;              //@synthesize _sync=__sync - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * cache;                     //@synthesize cache=_cache - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)annotationForPlugIn:(id)arg1 ;
-(id)addPlugIn:(id)arg1 ;
-(id)removePlugIn:(id)arg1 ;
-(id)findPlugIn:(id)arg1 ;
-(id)setAnnotation:(id)arg1 forPlugIn:(id)arg2 ;
-(id)plugInsWithinApplication:(id)arg1 ;
-(id)findPlugInAtPath:(id)arg1 ;
-(id)findPlugIns:(id)arg1 ;
-(id)createPlugInForProxy:(id)arg1 ;
-(void)autoElect:(id)arg1 ;
-(unsigned)cacheLimit;
-(void)purgeCachesToLimit:(long long)arg1 ;
-(id)plugInForProxy:(id)arg1 ;
-(NSObject*<OS_dispatch_queue>)_sync;
-(void)setDelegate:(id<PKDatabaseDelegate>)arg1 ;
-(id<PKDatabaseDelegate>)delegate;
-(NSMutableDictionary *)cache;
-(void)setCache:(NSMutableDictionary *)arg1 ;
-(void)set_sync:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)setCacheLimit:(unsigned)arg1 ;
-(PKDAnnotationStore *)annotations;
-(LSApplicationWorkspace *)workspace;
-(void)setAnnotations:(PKDAnnotationStore *)arg1 ;
-(void)setWorkspace:(LSApplicationWorkspace *)arg1 ;
-(id)initWithDatabase:(const char*)arg1 ;
-(void)pluginsDidInstall:(id)arg1 ;
-(void)pluginsWillUninstall:(id)arg1 ;
@end

