/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:27 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/pkd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSData, NSString;

@interface PKDPlugInSignature : NSObject {

	NSData* _cdhash;
	NSString* _requirement;

}

@property (retain) NSData * cdhash;                     //@synthesize cdhash=_cdhash - In the implementation block
@property (retain) NSString * requirement;              //@synthesize requirement=_requirement - In the implementation block
-(id)initWithURL:(id)arg1 error:(id*)arg2 ;
-(void)setCdhash:(NSData *)arg1 ;
-(void)setRequirement:(NSString *)arg1 ;
-(NSData *)cdhash;
-(NSString *)requirement;
@end

