/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:26 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/mobileassetd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <mobileassetd/ASURLSessionManager.h>

@protocol OS_dispatch_queue;
@class NSObject, NSMutableDictionary;

@interface ASAssetMetadataDownloader : ASURLSessionManager {

	NSObject*<OS_dispatch_queue> _queue;
	NSMutableDictionary* _data;
	NSMutableDictionary* _completions;
	double _defaultNetworkTimeout;

}

@property (assign,nonatomic) double defaultNetworkTimeout;              //@synthesize defaultNetworkTimeout=_defaultNetworkTimeout - In the implementation block
-(id)sessionConfigurationWithIdentifier:(id)arg1 options:(id)arg2 ;
-(double)defaultNetworkTimeout;
-(void)setDefaultNetworkTimeout:(double)arg1 ;
-(void)downloadMetadataFromURL:(id)arg1 withOptions:(id)arg2 ifNewerThan:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(BOOL)_canUseBackgroundSession;
-(id)_sessionForOptions:(id)arg1 ;
-(id)_lastModifiedDateFromResponse:(id)arg1 ;
-(id)_translateError:(id)arg1 ;
-(void)URLSession:(id)arg1 _willRetryBackgroundDataTask:(id)arg2 ;
-(void)dealloc;
-(id)init;
-(void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3 ;
-(void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3 ;
-(void)URLSession:(id)arg1 _taskIsWaitingForConnection:(id)arg2 ;
@end

