/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:26 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/mobileassetd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSURLSessionDelegate.h>

@class NSString;

@interface ASURLSessionManager : NSObject <NSURLSessionDelegate>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)sessionConfigurationWithIdentifier:(id)arg1 options:(id)arg2 ;
-(id)sessionWithIdentifier:(id)arg1 options:(id)arg2 ;
-(void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2 ;
@end

