/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:01:19 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Cydia/Cydia-Structs.h>
@interface CydiaProgressEvent : NSObject {

	MenesObjectHandle<NSString, 0> message_;
	MenesObjectHandle<NSString, 0> type_;
	MenesObjectHandle<NSArray, 0> item_;
	MenesObjectHandle<NSString, 0> package_;
	MenesObjectHandle<NSString, 0> url_;
	MenesObjectHandle<NSString, 0> version_;

}
+(id)_attributeKeys;
+(id)eventWithMessage:(id)arg1 ofType:(id)arg2 ;
+(id)eventWithMessage:(id)arg1 ofType:(id)arg2 forPackage:(id)arg3 ;
+(id)eventWithMessage:(id)arg1 ofType:(id)arg2 forItemDesc:(ItemDesc*)arg3 ;
+(char)isKeyExcludedFromWebScript:(const char*)arg1 ;
-(id)initWithMessage:(id)arg1 ofType:(id)arg2 ;
-(id)compound:(id)arg1 ;
-(id)compoundMessage;
-(id)compoundTitle;
-(void)setPackage:(id)arg1 ;
-(id)item;
-(id)url;
-(id)type;
-(id)message;
-(void)setURL:(id)arg1 ;
-(void)setItem:(id)arg1 ;
-(void)setVersion:(id)arg1 ;
-(id)version;
-(id)attributeKeys;
-(id)package;
@end

