/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:01:19 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Cydia/Cydia-Structs.h>
@interface CydiaProgressData : NSObject {

	id delegate_;
	BOOL running_;
	float percent_;
	float current_;
	float total_;
	float speed_;
	MenesObjectHandle<NSMutableArray, 0> events_;
	MenesObjectHandle<NSString, 0> title_;
	MenesObjectHandle<NSString, 0> status_;
	MenesObjectHandle<NSString, 0> finish_;

}
+(id)_attributeKeys;
+(char)isKeyExcludedFromWebScript:(const char*)arg1 ;
-(void)setFinish:(id)arg1 ;
-(id)total;
-(void)setTotal:(float)arg1 ;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(void)setTitle:(id)arg1 ;
-(id)delegate;
-(void)setSpeed:(float)arg1 ;
-(id)title;
-(id)speed;
-(id)finish;
-(id)attributeKeys;
-(id)current;
-(void)setCurrent:(float)arg1 ;
-(id)running;
-(void)setRunning:(BOOL)arg1 ;
-(void)addEvent:(id)arg1 ;
-(id)events;
-(id)percent;
-(void)setPercent:(float)arg1 ;
-(void)removeAllEvents;
@end

