/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:01:19 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Cydia/Cydia-Structs.h>
@interface CydiaClause : NSObject {

	MenesObjectHandle<NSString, 0> package_;
	MenesObjectHandle<CydiaOperation, 0> version_;

}
+(id)_attributeKeys;
+(char)isKeyExcludedFromWebScript:(const char*)arg1 ;
-(id)version;
-(id)attributeKeys;
-(id)package;
-(id)initWithIterator:(DepIterator*)arg1 ;
@end

