/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:01:19 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/FilteredPackageListController.h>

@interface SectionController : FilteredPackageListController {

	MenesObjectHandle<NSString, 0> key_;
	MenesObjectHandle<NSString, 0> section_;

}
-(id)navigationURL;
-(id)referrerURL;
-(id)initWithDatabase:(id)arg1 source:(id)arg2 section:(id)arg3 ;
-(void)reloadData;
@end

