/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:01:19 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CyteTableViewCell.h>
#import <Cydia/CyteTableViewCellDelegate.h>
#import <Cydia/SourceDelegate.h>

@interface SourceCell : CyteTableViewCell <CyteTableViewCellDelegate, SourceDelegate> {

	MenesObjectHandle<Source, 1> source_;
	MenesObjectHandle<NSURL, 0> url_;
	MenesObjectHandle<UIImage, 0> icon_;
	MenesObjectHandle<NSString, 0> origin_;
	MenesObjectHandle<NSString, 0> label_;
	MenesObjectHandle<UIActivityIndicatorView, 0> indicator_;

}
-(void)drawContentRect:(CGRect)arg1 ;
-(void)setFetch:(id)arg1 ;
-(void)setAllSource;
-(void)layoutSubviews;
-(void)setSource:(id)arg1 ;
-(id)accessibilityLabel;
-(id)initWithFrame:(CGRect)arg1 reuseIdentifier:(id)arg2 ;
-(void)_setSource:(id)arg1 ;
-(void)_setImage:(id)arg1 ;
@end

