/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 5:15:39 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/aosnotifyd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <aosnotifyd/AOSAccountStoreFMF.h>
#import <aosnotifyd/AOSAccountStore.h>

@class NSMutableArray, AOSLegacyFMFAccount, NSString;

@interface AOSAccountStoreLegacyFMF : AOSAccountStoreFMF <AOSAccountStore> {

	NSMutableArray* _accountsList;
	AOSLegacyFMFAccount* _currentActiveAccount;

}

@property (nonatomic,retain) NSMutableArray * accountsList;                                  //@synthesize accountsList=_accountsList - In the implementation block
@property (assign,nonatomic,__weak) AOSLegacyFMFAccount * currentActiveAccount;              //@synthesize currentActiveAccount=_currentActiveAccount - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)loadExistingAccounts;
-(void)setCurrentActiveAccount:(AOSLegacyFMFAccount *)arg1 ;
-(NSMutableArray *)accountsList;
-(void)setAccountsList:(NSMutableArray *)arg1 ;
-(AOSLegacyFMFAccount *)currentActiveAccount;
-(id)_accountFromLegacyDictionary:(id)arg1 ;
-(void)_saveDictionaryForAccount:(id)arg1 ;
-(id)_accountFromDictionary:(id)arg1 ;
-(void)_removeTokensForAccount:(id)arg1 ;
-(id)_dictionaryFromAccount:(id)arg1 ;
-(void)dealloc;
-(void)saveChanges;
-(void)removeAccount:(id)arg1 ;
-(id)accounts;
-(void)addAccount:(id)arg1 ;
@end

