/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 5:15:39 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/aosnotifyd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface AOSDebug : NSObject
+(void)_storeSyslogIntoDir:(id)arg1 ;
+(void)_storeAppInfoFor:(id)arg1 intoDir:(id)arg2 ;
+(void)dumpDebugSnapshot:(id)arg1 ;
@end

