/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 25, 2017 at 5:15:38 PM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/aosnotifyd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <aosnotifyd/AOSFindBaseServiceProvider.h>
#import <aosnotifyd/FMFFencesMgrDelegate.h>
#import <aosnotifyd/AOSAPSDelegate.h>

@protocol OS_dispatch_semaphore;
@class NSObject, AOSFMRequestCheckMigration, NSTimer, NSString;

@interface AOSFMFServiceProvider : AOSFindBaseServiceProvider <FMFFencesMgrDelegate, AOSAPSDelegate> {

	BOOL _hasCompletedInitialSetup;
	BOOL _waitingForBuddy;
	NSObject*<OS_dispatch_semaphore> _locationManagerSemaphore;
	id _tokenWatcherObserverToken;
	AOSFMRequestCheckMigration* _checkMigrationRequest;
	NSTimer* _buddyWaitTimer;

}

@property (assign,nonatomic) BOOL hasCompletedInitialSetup;                                          //@synthesize hasCompletedInitialSetup=_hasCompletedInitialSetup - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_semaphore> locationManagerSemaphore;              //@synthesize locationManagerSemaphore=_locationManagerSemaphore - In the implementation block
@property (nonatomic,retain) id tokenWatcherObserverToken;                                           //@synthesize tokenWatcherObserverToken=_tokenWatcherObserverToken - In the implementation block
@property (nonatomic,retain) AOSFMRequestCheckMigration * checkMigrationRequest;                     //@synthesize checkMigrationRequest=_checkMigrationRequest - In the implementation block
@property (nonatomic,retain) NSTimer * buddyWaitTimer;                                               //@synthesize buddyWaitTimer=_buddyWaitTimer - In the implementation block
@property (assign,nonatomic) BOOL waitingForBuddy;                                                   //@synthesize waitingForBuddy=_waitingForBuddy - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)_isFMFAppRestrictionSet;
-(void)accountDeactivated;
-(void)accountDidChange;
-(void)deinitializeProvider;
-(void)setLocationManagerSemaphore:(NSObject*<OS_dispatch_semaphore>)arg1 ;
-(void)performInitialSetup;
-(BOOL)hasCompletedInitialSetup;
-(void)requestAuthenticationShouldForce:(BOOL)arg1 ;
-(void)_sendStartupRegister;
-(void)checkForMigration;
-(void)registerCommonNotifications;
-(void)setHasCompletedInitialSetup:(BOOL)arg1 ;
-(void)_checkForBuddyCompletion;
-(void)fmfRestrictionsChanged:(id)arg1 ;
-(void)setTokenWatcherObserverToken:(id)arg1 ;
-(id)tokenWatcherObserverToken;
-(void)deregisterCommonNotifications;
-(NSTimer *)buddyWaitTimer;
-(void)setBuddyWaitTimer:(NSTimer *)arg1 ;
-(void)setWaitingForBuddy:(BOOL)arg1 ;
-(AOSFMRequestCheckMigration *)checkMigrationRequest;
-(void)setCheckMigrationRequest:(AOSFMRequestCheckMigration *)arg1 ;
-(id)_constructStandardDeviceContext;
-(id)_constructVolatileFullDeviceInfo;
-(id)_constructNonVolatileFullDeviceInfo;
-(BOOL)waitingForBuddy;
-(void)buddyDidComplete:(id)arg1 ;
-(void)_buddyCompletionCheckTimerFired:(id)arg1 ;
-(void)sendTriggeredFence:(id)arg1 withTriggerLocation:(id)arg2 ;
-(void)fenceTriggered:(id)arg1 atLocation:(id)arg2 ;
-(id)serviceIdentifierInURL;
-(id)copyHandlerForCommand:(id)arg1 params:(id)arg2 ;
-(BOOL)isProviderEnabledForLocations;
-(id)newLocationManager;
-(void)ackFencesCommand:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)didReceiveAuthFailureForRequest:(id)arg1 ;
-(void)tryToFetchAuthToken;
-(NSObject*<OS_dispatch_semaphore>)locationManagerSemaphore;
-(id)serviceName;
-(id)init;
-(void)stop;
-(void)start;
-(void)didReceiveAPSMessage:(id)arg1 ;
-(void)didReceiveAPSToken:(id)arg1 ;
@end

