/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 26, 2017 at 12:28:26 AM Eastern Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /usr/libexec/networkd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_source;
@class NSDictionary, NSObject, NSURLSession, NSURLSessionDataTask, AWDLBEndpointsFetchReport, NSArray;

@interface NETWaldo : NSObject {

	BOOL _waldoTimerSet;
	BOOL _statsReported;
	NSDictionary* _waldoReply;
	NSObject*<OS_dispatch_source> _waldoTimerSource;
	NSURLSession* _waldoSession;
	NSURLSessionDataTask* _waldoFetchTask;
	unsigned long long _errInWaldoTimer;
	unsigned long long _defaultWaldoTTLBasedTimer;
	AWDLBEndpointsFetchReport* _waldoReport;

}

@property (readonly) NSArray * edges; 
@property (retain) NSDictionary * waldoReply;                                             //@synthesize waldoReply=_waldoReply - In the implementation block
@property (assign) BOOL waldoTimerSet;                                                    //@synthesize waldoTimerSet=_waldoTimerSet - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> waldoTimerSource;              //@synthesize waldoTimerSource=_waldoTimerSource - In the implementation block
@property (nonatomic,retain) NSURLSession * waldoSession;                                 //@synthesize waldoSession=_waldoSession - In the implementation block
@property (nonatomic,retain) NSURLSessionDataTask * waldoFetchTask;                       //@synthesize waldoFetchTask=_waldoFetchTask - In the implementation block
@property (assign) unsigned long long errInWaldoTimer;                                    //@synthesize errInWaldoTimer=_errInWaldoTimer - In the implementation block
@property (assign) unsigned long long defaultWaldoTTLBasedTimer;                          //@synthesize defaultWaldoTTLBasedTimer=_defaultWaldoTTLBasedTimer - In the implementation block
@property (nonatomic,retain) AWDLBEndpointsFetchReport * waldoReport;                     //@synthesize waldoReport=_waldoReport - In the implementation block
@property (assign,nonatomic) BOOL statsReported;                                          //@synthesize statsReported=_statsReported - In the implementation block
+(void)notifyClients:(id)arg1 ;
+(id)copyReply;
+(BOOL)isWaldoHostname:(const char*)arg1 ;
+(void)waldoFellbackToCellular;
+(id)getStateDump;
+(id)url;
+(void)addClient:(id)arg1 ;
+(void)removeClient:(id)arg1 ;
-(NSDictionary *)waldoReply;
-(void)setWaldoTimerSet:(BOOL)arg1 ;
-(NSObject*<OS_dispatch_source>)waldoTimerSource;
-(void)fetchURL;
-(NSURLSessionDataTask *)waldoFetchTask;
-(void)setWaldoFetchTask:(NSURLSessionDataTask *)arg1 ;
-(NSURLSession *)waldoSession;
-(void)setWaldoSession:(NSURLSession *)arg1 ;
-(BOOL)waldoTimerSet;
-(unsigned long long)errInWaldoTimer;
-(unsigned long long)defaultWaldoTTLBasedTimer;
-(BOOL)verifyDictionary:(id)arg1 ;
-(AWDLBEndpointsFetchReport *)waldoReport;
-(void)setWaldoReply:(NSDictionary *)arg1 ;
-(void)setDefaultWaldoTTLBasedTimer:(unsigned long long)arg1 ;
-(void)setErrInWaldoTimer:(unsigned long long)arg1 ;
-(BOOL)statsReported;
-(void)setStatsReported:(BOOL)arg1 ;
-(void)fellbackToCellular;
-(void)setWaldoTimerSource:(NSObject*<OS_dispatch_source>)arg1 ;
-(void)setWaldoReport:(AWDLBEndpointsFetchReport *)arg1 ;
-(void)cancel;
-(void)dealloc;
-(id)init;
-(void)start;
-(void)startTimer;
-(NSArray *)edges;
-(void)handleResponse:(id)arg1 error:(id)arg2 ;
@end

